# Generated by Django 5.1.15 on 2026-06-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='scope_type',
            field=models.CharField(choices=[('all', 'All (network-wide)'), ('entity', 'Legal entity'), ('region', 'Region / state'), ('store_group', 'Store group'), ('store', 'Single store')], default='store', max_length=20),
        ),
    ]
