# Generated by Django 5.1.15 on 2026-07-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_receive_goods_pt_making_rung'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='till_pin_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
