# Generated by Django 5.1.15 on 2026-09-13 14:50

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_authenticationfailure_humanidentity_rolegrant_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0009_voucherseries_tenant_and_more'),
        ('masters', '0011_configdraft_configversion_sitecapabilityevent_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='authenticationfailure',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='humanidentity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='human',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='login', to='accounts.humanidentity'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('email__isnull', False)), name='uq_user_email_lower'),
        ),
        migrations.AddField(
            model_name='rolegrant',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='rolegrant',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand'),
        ),
        migrations.AddField(
            model_name='rolegrant',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='rolegrant',
            name='config_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.configversion'),
        ),
        migrations.AddField(
            model_name='rolegrant',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.legalentity'),
        ),
        migrations.AddField(
            model_name='rolegrant',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='rolegrant',
            name='revokes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revocations', to='accounts.rolegrant'),
        ),
        migrations.AddField(
            model_name='rolegrant',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='rolegrant',
            name='sbu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.sbu'),
        ),
        migrations.AddField(
            model_name='rolegrant',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='rolegrant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='securityguard',
            name='human',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='security_guard', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='securityguard',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='serversession',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='serversession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='server_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staff',
            name='human',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='staff',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='staffassignment',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='staffassignment',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='staffassignment',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='staffassignment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='accounts.staff'),
        ),
        migrations.AddField(
            model_name='staffassignment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddIndex(
            model_name='authenticationfailure',
            index=models.Index(fields=['locked_until'], name='accounts_au_locked__d0f26b_idx'),
        ),
        migrations.AddConstraint(
            model_name='authenticationfailure',
            constraint=models.UniqueConstraint(fields=('tenant', 'identifier_hash'), name='uq_authfailure_identifier'),
        ),
        migrations.AddConstraint(
            model_name='humanidentity',
            constraint=models.UniqueConstraint(fields=('tenant', 'staff_code'), name='uq_humanidentity_staff_code'),
        ),
        migrations.AddIndex(
            model_name='rolegrant',
            index=models.Index(fields=['human', 'scope_kind', 'effective_from'], name='accounts_ro_human_i_88d3c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='rolegrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='accounts_rolegrant_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='rolegrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('brand__isnull', True), ('entity__isnull', True), ('sbu__isnull', True), ('scope_kind', 'tenant'), ('site__isnull', True)), models.Q(('brand__isnull', True), ('entity__isnull', False), ('sbu__isnull', True), ('scope_kind', 'entity'), ('site__isnull', True)), models.Q(('brand__isnull', True), ('entity__isnull', True), ('sbu__isnull', True), ('scope_kind', 'site'), ('site__isnull', False)), models.Q(('brand__isnull', True), ('entity__isnull', True), ('sbu__isnull', False), ('scope_kind', 'sbu'), ('site__isnull', True)), models.Q(('brand__isnull', False), ('entity__isnull', True), ('sbu__isnull', True), ('scope_kind', 'brand'), ('site__isnull', True)), _connector='OR'), name='ck_rolegrant_scope'),
        ),
        migrations.AddIndex(
            model_name='serversession',
            index=models.Index(fields=['user', 'expires_at'], name='accounts_se_user_id_477da9_idx'),
        ),
        migrations.AddConstraint(
            model_name='serversession',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__lte', django.db.models.expressions.CombinedExpression(models.F('issued_at'), '+', models.Value('12 hours', output_field=models.DurationField())))), name='ck_serversession_absolute_life'),
        ),
        migrations.AddIndex(
            model_name='staffassignment',
            index=models.Index(fields=['site', 'effective_from'], name='accounts_st_site_id_71d0dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='accounts_staffassignment_one_actor'),
        ),
    ]
