# Generated by Django 5.2.17 on 2026-09-29 10:11

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_store_roles'),
        ('masters', '0031_staff_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='field_access',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('all_sites', models.BooleanField(default=False)),
                ('site_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, size=None)),
                ('all_brands', models.BooleanField(default=False)),
                ('brand_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, size=None)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='accounts.humanidentity')),
                ('legacy_grant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_assignment', to='accounts.rolegrant')),
                ('legacy_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='migrated_role_assignments', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='accounts.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['human', 'effective_from', 'effective_to'], name='accounts_ro_human_i_34ba10_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='ck_roleassignment_period'), models.CheckConstraint(condition=models.Q(('all_sites', False), ('site_ids', []), _connector='OR'), name='ck_roleassignment_site_flag'), models.CheckConstraint(condition=models.Q(('all_brands', False), ('brand_ids', []), _connector='OR'), name='ck_roleassignment_brand_flag'), models.UniqueConstraint(condition=models.Q(('legacy_grant__isnull', True), ('legacy_user__isnull', False)), fields=('tenant', 'legacy_user'), name='uq_roleassignment_user_fallback')],
            },
        ),
    ]
