# Generated by Django 5.1.15 on 2026-07-29 13:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0005_brand_return_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('in_transit_aging', 'Transfer stuck in transit'), ('return_window', 'Return window closing')], max_length=32, unique=True)),
                ('thresholds_days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), help_text='Days that fire this kind. In-transit aging has one (days overdue); return window has three (days left: 30/15/7).', size=None)),
            ],
            options={
                'verbose_name_plural': 'alert policies',
                'db_table': 'alerts_policy',
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('in_transit_aging', 'Transfer stuck in transit'), ('return_window', 'Return window closing')], max_length=32)),
                ('kind_label', models.CharField(max_length=64)),
                ('title', models.CharField(help_text='Snapshot one-liner the inbox shows — store, brand, days.', max_length=240)),
                ('dedupe_key', models.CharField(help_text='What makes this one instance of this kind — e.g. a transfer id, or a (brand, store, sku, threshold) tuple. The job upserts on (kind, dedupe_key) so a daily re-run never doubles an alert that is still true.', max_length=160)),
                ('brand', models.CharField(blank=True, default='', help_text='Scopes the inbox for a brand-scoped user. Blank means this alert is not about one brand.', max_length=120)),
                ('object_id', models.BigIntegerField(blank=True, help_text='The document this alert is about, if it is about one — a transfer id for in-transit aging. The client maps kind → route, the same way it does for approvals; a return-window alert has none, because it names a holding rather than a document.', null=True)),
                ('due_date', models.DateField(blank=True, help_text='The deadline this alert is counting down to.', null=True)),
                ('threshold_days', models.IntegerField(blank=True, help_text='Which configured threshold this crossing fired at.', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(blank=True, help_text='Scopes the inbox for store-scoped users — the same rule as approvals (ADR-0003).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='masters.store')),
            ],
            options={
                'db_table': 'alerts_alert',
                'ordering': ['due_date', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('kind', 'dedupe_key'), name='uq_alert_open_kind_dedupe')],
            },
        ),
    ]
