# Generated by Django 5.1.15 on 2026-07-31 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_seed_alert_policies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seen_at', models.DateTimeField(help_text='Server clock at the moment they opened the Alerts tab - a client clock is not trusted to decide what counts as unread.')),
                ('user', models.OneToOneField(help_text='One stamp per person; it dies with the account.', on_delete=django.db.models.deletion.CASCADE, related_name='alert_seen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alerts_seen',
            },
        ),
    ]
