# Generated by Django 5.1.15 on 2026-09-13 14:50

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_authenticationfailure_humanidentity_rolegrant_and_more'),
        ('alerts', '0003_alertseen'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('kind', models.CharField(max_length=60)),
                ('subject_key', models.CharField(max_length=100)),
                ('owner_role', models.CharField(max_length=40)),
                ('due_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('reason_code', models.CharField(blank=True, max_length=60, null=True)),
                ('source_event_key', models.UUIDField()),
                ('resolution_event_key', models.UUIDField(blank=True, null=True)),
                ('opened_at', models.DateTimeField()),
                ('allowed_resolution_actions', models.JSONField(default=list)),
                ('revision', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('subject_key', models.CharField(max_length=100)),
                ('event_kind', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=240)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('seen_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExceptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('event_kind', models.CharField(choices=[('opened', 'Opened'), ('assigned', 'Assigned'), ('note', 'Note'), ('resolved', 'Resolved'), ('reopened', 'Reopened')], max_length=10)),
                ('reason_code', models.CharField(blank=True, max_length=60, null=True)),
                ('payload', models.JSONField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
