# Generated by Django 5.1.15 on 2026-09-13 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_goodsexception_goodsnotification_and_more'),
        ('core', '0008_auditevent_chainhead_commandattempt_commandkey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionevent',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
    ]
