# Generated by Django 5.1.15 on 2026-09-13 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_authenticationfailure_humanidentity_rolegrant_and_more'),
        ('alerts', '0005_exceptionevent_command_key'),
        ('core', '0008_auditevent_chainhead_commandattempt_commandkey_and_more'),
        ('masters', '0011_configdraft_configversion_sitecapabilityevent_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='goodsexception',
            name='owner_human',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='goodsexception',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='goodsexception',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='exceptionevent',
            name='exception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='alerts.goodsexception'),
        ),
        migrations.AddField(
            model_name='goodsnotification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='goodsnotification',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand'),
        ),
        migrations.AddField(
            model_name='goodsnotification',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='goodsnotification',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.outboxintent'),
        ),
        migrations.AddField(
            model_name='goodsnotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='goodsnotification',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='goodsnotification',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='notificationacknowledgement',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='notificationacknowledgement',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='notificationacknowledgement',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acks', to='alerts.goodsnotification'),
        ),
        migrations.AddField(
            model_name='notificationacknowledgement',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='notificationacknowledgement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddIndex(
            model_name='goodsexception',
            index=models.Index(fields=['site', 'state', 'due_at'], name='alerts_good_site_id_3cddda_idx'),
        ),
        migrations.AddConstraint(
            model_name='goodsexception',
            constraint=models.UniqueConstraint(fields=('tenant', 'kind', 'source_event_key'), name='uq_goodsexception_source'),
        ),
        migrations.AddIndex(
            model_name='exceptionevent',
            index=models.Index(fields=['exception', 'recorded_at'], name='alerts_exce_excepti_8457fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='exceptionevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='alerts_exceptionevent_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='exceptionevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_kind__in', ['opened', 'reopened']), _negated=True), ('reason_code__isnull', False), _connector='OR'), name='ck_exceptionevent_reason'),
        ),
        migrations.AddIndex(
            model_name='goodsnotification',
            index=models.Index(fields=['recipient', 'created_at'], name='alerts_good_recipie_2e9ec0_idx'),
        ),
        migrations.AddConstraint(
            model_name='goodsnotification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='alerts_goodsnotification_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='goodsnotification',
            constraint=models.UniqueConstraint(fields=('intent', 'recipient'), name='uq_goodsnotification_recipient'),
        ),
        migrations.AddIndex(
            model_name='notificationacknowledgement',
            index=models.Index(fields=['recipient', 'seen_at'], name='alerts_noti_recipie_d22270_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationacknowledgement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='alerts_notificationacknowledgement_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='notificationacknowledgement',
            constraint=models.UniqueConstraint(fields=('notification', 'recipient'), name='uq_notificationack'),
        ),
    ]
