# Generated by Django 5.1.15 on 2026-09-15 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0006_exceptionevent_tenant_goodsexception_owner_human_and_more"),
        ("masters", "0019_backfill_custody_system_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsexception",
            name="calendar_version",
            field=models.ForeignKey(
                blank=True,
                help_text="GSA-T08: the approved working_calendar version `due_at` was computed against, when a working-day SLA had one approved. Frozen at open — reassignment and a later calendar version never recompute an existing exception's due_at.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="masters.configversion",
            ),
        ),
    ]
