# Generated by Django 5.1.15 on 2026-09-16 12:43

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_enforce_role_tenant'),
        ('alerts', '0007_gsa_t08_calendar_evidence'),
        ('core', '0009_voucherseries_tenant_and_more'),
        ('masters', '0019_backfill_custody_system_location'),
        ('ptmapper', '0014_openingmanifest_openingmanifestversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginInvestigationOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('reviewed_hash', models.CharField(max_length=64)),
                ('reason_code', models.CharField(max_length=60)),
                ('evidence_ids', models.JSONField(default=list)),
                ('outcome', models.CharField(choices=[('historical_origin_unavailable', 'Historical Origin Unavailable')], default='historical_origin_unavailable', max_length=32)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('exception', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='alerts.goodsexception')),
                ('manifest_row', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ptmapper.openingmanifestrow')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['exception'], name='alerts_orig_excepti_2ac8a4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='alerts_origininvestigationoutcome_one_actor')],
            },
        ),
    ]
