# Generated by Django 5.1.15 on 2026-09-16 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_origininvestigationoutcome'),
        ('masters', '0019_backfill_custody_system_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsexception',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
    ]
