# Generated by Django 5.1.15 on 2026-09-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_alter_goodsexception_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsexception',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
