# Generated by Django 5.1.15 on 2026-09-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_alter_goodsexception_due_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('in_transit_aging', 'Transfer stuck in transit'), ('return_window', 'Return window closing'), ('document_number', 'Document number problem')], max_length=32),
        ),
        migrations.AlterField(
            model_name='alertpolicy',
            name='kind',
            field=models.CharField(choices=[('in_transit_aging', 'Transfer stuck in transit'), ('return_window', 'Return window closing'), ('document_number', 'Document number problem')], max_length=32, unique=True),
        ),
    ]
