# Generated by Django 5.1.15 on 2026-09-27 19:25

from django.db import migrations, models

# Store operations PRD ST-INV-2 (Anand, B5): in-season stock is flagged after 90
# days with no sale. One number in one place an owner can retune in the admin
# (Rule 12); the Stock Ageing page reads the same row.
STOCK_AGEING_DAYS = [90]


def seed_policy(apps, schema_editor):
    AlertPolicy = apps.get_model("alerts", "AlertPolicy")
    AlertPolicy.objects.get_or_create(
        kind="stock_ageing", defaults={"thresholds_days": STOCK_AGEING_DAYS}
    )


def unseed_policy(apps, schema_editor):
    AlertPolicy = apps.get_model("alerts", "AlertPolicy")
    AlertPolicy.objects.filter(kind="stock_ageing").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0011_document_number_alert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="kind",
            field=models.CharField(
                choices=[
                    ("in_transit_aging", "Transfer stuck in transit"),
                    ("return_window", "Return window closing"),
                    ("document_number", "Document number problem"),
                    ("stock_ageing", "Stock ageing"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="alertpolicy",
            name="kind",
            field=models.CharField(
                choices=[
                    ("in_transit_aging", "Transfer stuck in transit"),
                    ("return_window", "Return window closing"),
                    ("document_number", "Document number problem"),
                    ("stock_ageing", "Stock ageing"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
        migrations.RunPython(seed_policy, unseed_policy),
    ]
