# Generated by Django 5.1.15 on 2026-09-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0012_stock_ageing_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('in_transit_aging', 'Transfer stuck in transit'), ('return_window', 'Return window closing'), ('document_number', 'Document number problem'), ('stock_ageing', 'Stock ageing'), ('broken_size', 'Broken sizes')], max_length=32),
        ),
        migrations.AlterField(
            model_name='alertpolicy',
            name='kind',
            field=models.CharField(choices=[('in_transit_aging', 'Transfer stuck in transit'), ('return_window', 'Return window closing'), ('document_number', 'Document number problem'), ('stock_ageing', 'Stock ageing'), ('broken_size', 'Broken sizes')], max_length=32, unique=True),
        ),
    ]
