# Generated by Django 5.1.15 on 2026-09-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0013_broken_size_alert'),
        ('alerts', '0013_count_due_alert'),
    ]

    operations = [
    ]
