# Generated by Django 5.1.15 on 2026-09-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0013_cash_variance_alert'),
        ('alerts', '0015_alter_alert_kind_alter_alertpolicy_kind'),
    ]

    operations = [
    ]
