# Generated by Django 5.1.15 on 2026-09-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0016_merge_20260928_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('in_transit_aging', 'Transfer stuck in transit'), ('return_window', 'Return window closing'), ('document_number', 'Document number problem'), ('stock_ageing', 'Stock ageing'), ('broken_size', 'Broken sizes'), ('count_due', 'Count due'), ('cash_variance', 'Cash variance')], max_length=32),
        ),
        migrations.AlterField(
            model_name='alertpolicy',
            name='kind',
            field=models.CharField(choices=[('in_transit_aging', 'Transfer stuck in transit'), ('return_window', 'Return window closing'), ('document_number', 'Document number problem'), ('stock_ageing', 'Stock ageing'), ('broken_size', 'Broken sizes'), ('count_due', 'Count due'), ('cash_variance', 'Cash variance')], max_length=32, unique=True),
        ),
    ]
