# Generated by Django 5.1.15 on 2026-09-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0013_customer_reservation'),
        ('alerts', '0018_brand_claims'),
    ]

    operations = [
    ]
