# Generated by Django 5.1.15 on 2026-09-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0020_alter_alert_kind_alter_alertpolicy_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('in_transit_aging', 'Transfer stuck in transit'), ('return_window', 'Return window closing'), ('document_number', 'Document number problem'), ('stock_ageing', 'Stock ageing'), ('broken_size', 'Broken sizes'), ('count_due', 'Count due'), ('cash_variance', 'Cash variance'), ('brand_claim_flagged', 'Brand claim to check'), ('reservation_expiry', 'Reservation expiring'), ('no_bill_return_cap', 'No-bill return cap')], max_length=32),
        ),
        migrations.AlterField(
            model_name='alertpolicy',
            name='kind',
            field=models.CharField(choices=[('in_transit_aging', 'Transfer stuck in transit'), ('return_window', 'Return window closing'), ('document_number', 'Document number problem'), ('stock_ageing', 'Stock ageing'), ('broken_size', 'Broken sizes'), ('count_due', 'Count due'), ('cash_variance', 'Cash variance'), ('brand_claim_flagged', 'Brand claim to check'), ('reservation_expiry', 'Reservation expiring'), ('no_bill_return_cap', 'No-bill return cap')], max_length=32, unique=True),
        ),
    ]
