# Generated by Django 5.1.15 on 2026-09-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0021_no_bill_return_cap'),
        ('alerts', '0021_sor_ageing'),
    ]

    operations = [
    ]
