# Generated by Django 5.2.17 on 2026-09-29 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0024_checklist_missed'),
        ('masters', '0031_staff_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='brand_ref',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand'),
        ),
    ]
