# Generated by Django 5.1.15 on 2026-06-28 20:48

import core.money
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from core.ledger import append_only_reverse_sql, append_only_sql


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ptmapper", "0003_ptfile_booking_ptfile_inward_doc_number"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", core.money.MoneyField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("account", models.CharField(default="CASH", max_length=24)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("receipt", "Receipt (cash in)"),
                            ("payment", "Payment (cash out)"),
                            ("reversal", "Reversal"),
                        ],
                        max_length=12,
                    ),
                ),
                ("doc_number", models.CharField(db_index=True, max_length=128)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=240),
                ),
                ("mode", models.CharField(blank=True, default="", max_length=24)),
                ("link_doc", models.CharField(blank=True, default="", max_length=128)),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_entries",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "finledger_cash_entry",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="VendorLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", core.money.MoneyField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("bill", "Bill / purchase"),
                            ("payment", "Payment"),
                            ("reversal", "Reversal"),
                        ],
                        max_length=12,
                    ),
                ),
                ("doc_number", models.CharField(db_index=True, max_length=128)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=240),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=120)),
                ("mode", models.CharField(blank=True, default="", max_length=24)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_entries",
                        to="vendors.booking",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pt_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendor_entries",
                        to="ptmapper.ptfile",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "finledger_vendor_entry",
                "ordering": ["-created_at", "-id"],
            },
        ),
        # Append-only enforcement (ADR-0004) for both ledger tables.
        migrations.RunSQL(
            sql=append_only_sql("finledger_cash_entry"),
            reverse_sql=append_only_reverse_sql("finledger_cash_entry"),
        ),
        migrations.RunSQL(
            sql=append_only_sql("finledger_vendor_entry"),
            reverse_sql=append_only_reverse_sql("finledger_vendor_entry"),
        ),
    ]
