# Generated by Django 5.1.15 on 2026-06-30 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finledger', '0002_truncate_guard'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashledgerentry',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='finledger.cashledgerentry'),
        ),
        migrations.AddField(
            model_name='vendorledgerentry',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='finledger.vendorledgerentry'),
        ),
    ]
