# Generated by Django 5.1.15 on 2026-07-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finledger', '0003_cashledgerentry_reverses_vendorledgerentry_reverses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashledgerentry',
            name='account',
            field=models.CharField(choices=[('CASH', 'Cash drawer'), ('BANK', 'Bank'), ('CARD', 'Card, awaiting settlement'), ('UPI', 'UPI, awaiting settlement')], default='CASH', max_length=24),
        ),
    ]
