# Generated by Django 5.1.15 on 2026-08-04 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_bank_reconciliation'),
        ('finledger', '0005_partnerledgerentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_label', models.CharField(blank=True, default='', max_length=80)),
                ('row_count', models.IntegerField(default=0)),
                ('matched_count', models.IntegerField(default=0)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statement_import', to='files.storedfile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finledger_bank_statement_import',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('txn_date', models.DateField()),
                ('narration', models.CharField(blank=True, default='', max_length=500)),
                ('debit_paise', models.BigIntegerField(default=0)),
                ('credit_paise', models.BigIntegerField(default=0)),
                ('balance_paise', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('review', 'Needs review'), ('unmatched', 'Unmatched'), ('ignored', 'Ignored')], default='unmatched', max_length=12)),
                ('match_confidence', models.IntegerField(default=0)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finledger.bankstatementimport')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('matched_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_line', to='finledger.cashledgerentry')),
            ],
            options={
                'db_table': 'finledger_bank_statement_line',
                'ordering': ['-txn_date', '-id'],
            },
        ),
    ]
