# Generated by Django 5.1.15 on 2026-09-28 11:09

import core.goods_base
import core.money
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

from core.dbroles import tenant_rls_sql

#: All three tables behind the tenant wall. What an invoice owes and how it falls
#: due are frozen when it is recorded, what a payment paid is frozen too, a
#: cancelled row is final, an allocation is never changed, and nothing is deleted
#: (ticket 28).
GUARDS = f"""
{tenant_rls_sql("finledger_payable_invoice")}
{tenant_rls_sql("finledger_payable_payment")}
{tenant_rls_sql("finledger_payable_allocation")}
CREATE OR REPLACE FUNCTION kdps_payable_final() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'payables are never deleted (%)', TG_TABLE_NAME;
    END IF;
    IF TG_TABLE_NAME = 'finledger_payable_allocation' THEN
        RAISE EXCEPTION 'where a payment went is never changed';
    END IF;
    IF OLD.status = 'cancelled' THEN
        RAISE EXCEPTION 'a cancelled payable is never edited (%)', TG_TABLE_NAME;
    END IF;
    IF TG_TABLE_NAME = 'finledger_payable_invoice' THEN
        IF (NEW.tenant_id, NEW.store_id, NEW.vendor_id, NEW.brand_id, NEW.season_id,
            NEW.invoice_number, NEW.invoice_date, NEW.amount_paise, NEW.model,
            NEW.terms_version_id, NEW.payment_days, NEW.due_date, NEW.recorded_by_id,
            NEW.created_at, NEW.note)
           IS DISTINCT FROM
           (OLD.tenant_id, OLD.store_id, OLD.vendor_id, OLD.brand_id, OLD.season_id,
            OLD.invoice_number, OLD.invoice_date, OLD.amount_paise, OLD.model,
            OLD.terms_version_id, OLD.payment_days, OLD.due_date, OLD.recorded_by_id,
            OLD.created_at, OLD.note) THEN
            RAISE EXCEPTION 'what a payable invoice owes is frozen when it is recorded';
        END IF;
    ELSE
        IF (NEW.tenant_id, NEW.store_id, NEW.vendor_id, NEW.paid_on, NEW.amount_paise,
            NEW.mode, NEW.reference, NEW.recorded_by_id, NEW.created_at, NEW.note)
           IS DISTINCT FROM
           (OLD.tenant_id, OLD.store_id, OLD.vendor_id, OLD.paid_on, OLD.amount_paise,
            OLD.mode, OLD.reference, OLD.recorded_by_id, OLD.created_at, OLD.note) THEN
            RAISE EXCEPTION 'what a payment paid is frozen when it is recorded';
        END IF;
    END IF;
    -- Who cancelled, when and why is written only by the cancel itself.
    IF NEW.status = OLD.status
       AND (NEW.cancelled_by_id, NEW.cancelled_at, NEW.cancel_reason)
           IS DISTINCT FROM (OLD.cancelled_by_id, OLD.cancelled_at, OLD.cancel_reason) THEN
        RAISE EXCEPTION 'a payable is cancelled only by cancelling it (%)', TG_TABLE_NAME;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER finledger_payable_invoice_final BEFORE UPDATE OR DELETE
    ON finledger_payable_invoice FOR EACH ROW EXECUTE FUNCTION kdps_payable_final();
CREATE TRIGGER finledger_payable_payment_final BEFORE UPDATE OR DELETE
    ON finledger_payable_payment FOR EACH ROW EXECUTE FUNCTION kdps_payable_final();
CREATE TRIGGER finledger_payable_allocation_final BEFORE UPDATE OR DELETE
    ON finledger_payable_allocation FOR EACH ROW EXECUTE FUNCTION kdps_payable_final();
"""

UNGUARD = """
DROP TRIGGER IF EXISTS finledger_payable_invoice_final ON finledger_payable_invoice;
DROP TRIGGER IF EXISTS finledger_payable_payment_final ON finledger_payable_payment;
DROP TRIGGER IF EXISTS finledger_payable_allocation_final ON finledger_payable_allocation;
DROP FUNCTION IF EXISTS kdps_payable_final();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('finledger', '0007_remove_vendorledgerentry_pt_file'),
        ('masters', '0030_customer_merge_and_numbers'),
        ('vendors', '0010_bookingline_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayableInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=60)),
                ('invoice_date', models.DateField()),
                ('amount_paise', core.money.MoneyField()),
                ('model', models.CharField(choices=[('outright', 'Outright'), ('unknown', 'Model unknown')], max_length=10)),
                ('terms_version_id', models.UUIDField(blank=True, null=True)),
                ('payment_days', models.PositiveIntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=240)),
                ('status', models.CharField(choices=[('open', 'Recorded'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=240)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.season')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('tenant', models.ForeignKey(db_default=core.goods_base.CurrentTenant(), editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vendors.vendor')),
            ],
            options={
                'db_table': 'finledger_payable_invoice',
                'ordering': ['invoice_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayablePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_on', models.DateField()),
                ('amount_paise', core.money.MoneyField()),
                ('mode', models.CharField(choices=[('bank', 'Bank transfer'), ('cheque', 'Cheque'), ('upi', 'UPI'), ('cash', 'Cash')], max_length=10)),
                ('reference', models.CharField(max_length=60)),
                ('note', models.CharField(blank=True, default='', max_length=240)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('cancelled', 'Cancelled')], default='recorded', max_length=10)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=240)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('tenant', models.ForeignKey(db_default=core.goods_base.CurrentTenant(), editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vendors.vendor')),
            ],
            options={
                'db_table': 'finledger_payable_payment',
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayableAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paise', core.money.MoneyField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(db_default=core.goods_base.CurrentTenant(), editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finledger.payableinvoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finledger.payablepayment')),
            ],
            options={
                'db_table': 'finledger_payable_allocation',
            },
        ),
        migrations.AddIndex(
            model_name='payableinvoice',
            index=models.Index(fields=['store', 'vendor'], name='finledger_p_store_i_7ce054_idx'),
        ),
        migrations.AddIndex(
            model_name='payableinvoice',
            index=models.Index(fields=['brand'], name='finledger_p_brand_i_4629db_idx'),
        ),
        migrations.AddIndex(
            model_name='payableinvoice',
            index=models.Index(fields=['status'], name='finledger_p_status_4a3c91_idx'),
        ),
        migrations.AddConstraint(
            model_name='payableinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='ck_payableinvoice_amount'),
        ),
        migrations.AddConstraint(
            model_name='payableinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('model__in', ['outright', 'unknown'])), name='ck_payableinvoice_model'),
        ),
        migrations.AddConstraint(
            model_name='payableinvoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('due_date__isnull', True), ('payment_days__isnull', True)), models.Q(('due_date__isnull', False), ('payment_days__isnull', False)), _connector='OR'), name='ck_payableinvoice_due'),
        ),
        migrations.AddConstraint(
            model_name='payableinvoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), models.Q(('cancel_reason', ''), _negated=True), _connector='OR'), name='ck_payableinvoice_cancel_reason'),
        ),
        migrations.AddConstraint(
            model_name='payableinvoice',
            constraint=models.UniqueConstraint(models.F('tenant'), models.F('vendor'), django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('invoice_number')), condition=models.Q(('status', 'open')), name='uq_payableinvoice_vendor_number'),
        ),
        migrations.AddIndex(
            model_name='payablepayment',
            index=models.Index(fields=['store', 'vendor'], name='finledger_p_store_i_6fbce7_idx'),
        ),
        migrations.AddConstraint(
            model_name='payablepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='ck_payablepayment_amount'),
        ),
        migrations.AddConstraint(
            model_name='payablepayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), models.Q(('cancel_reason', ''), _negated=True), _connector='OR'), name='ck_payablepayment_cancel_reason'),
        ),
        migrations.AddConstraint(
            model_name='payableallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='ck_payableallocation_amount'),
        ),
        migrations.AddConstraint(
            model_name='payableallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'invoice'), name='uq_payableallocation_payment_invoice'),
        ),
        migrations.RunSQL(GUARDS, UNGUARD),
    ]
