# Generated by Django 5.1.15 on 2026-06-28 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemTaxonomy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item", models.CharField(max_length=160, unique=True)),
                (
                    "sub_category",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("type", models.CharField(blank=True, default="", max_length=60)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaxonomyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pattern", models.CharField(max_length=160)),
                ("gender", models.CharField(blank=True, default="", max_length=40)),
                (
                    "sub_category",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("type", models.CharField(blank=True, default="", max_length=60)),
                ("item", models.CharField(blank=True, default="", max_length=160)),
                ("fit", models.CharField(blank=True, default="", max_length=80)),
                ("priority", models.IntegerField(default=100)),
            ],
            options={
                "ordering": ["-priority", "pattern"],
            },
        ),
        migrations.CreateModel(
            name="ControlledValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("season", "Season"),
                            ("brand", "Brand"),
                            ("color", "Color"),
                            ("gender", "Gender"),
                            ("sub_category", "Sub Category"),
                            ("type", "Type"),
                            ("item", "Item"),
                            ("fit", "Fit"),
                            ("size", "Size"),
                            ("gst", "GST %"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=160)),
            ],
            options={
                "ordering": ["dimension", "value"],
                "unique_together": {("dimension", "value")},
            },
        ),
        migrations.CreateModel(
            name="Lookup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dimension", models.CharField(max_length=20)),
                ("source_key", models.CharField(max_length=240)),
                ("target_value", models.CharField(max_length=160)),
            ],
            options={
                "ordering": ["dimension", "source_key"],
                "unique_together": {("dimension", "source_key")},
            },
        ),
        migrations.CreateModel(
            name="PtFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "brand_guess",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "profile_code",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "profile_name",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("archetype", models.CharField(blank=True, default="", max_length=4)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("needs_review", "Needs review"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="needs_review",
                        max_length=20,
                    ),
                ),
                ("row_count", models.IntegerField(default=0)),
                ("blank_cell_count", models.IntegerField(default=0)),
                ("unresolved_count", models.IntegerField(default=0)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("error", models.CharField(blank=True, default="", max_length=400)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stored_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="files.storedfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PtRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_no", models.IntegerField(default=0)),
                ("data", models.JSONField(default=dict)),
                ("blanks", models.JSONField(default=list)),
                (
                    "pt_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="ptmapper.ptfile",
                    ),
                ),
            ],
            options={
                "ordering": ["line_no"],
            },
        ),
        migrations.CreateModel(
            name="ReviewItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dimension", models.CharField(max_length=20)),
                ("raw_value", models.CharField(max_length=300)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                (
                    "resolved_value",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("occurrences", models.IntegerField(default=1)),
            ],
            options={
                "ordering": ["status", "-occurrences", "dimension", "raw_value"],
                "unique_together": {("dimension", "raw_value")},
            },
        ),
    ]
