# Generated by Django 5.1.15 on 2026-06-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ptmapper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ptfile",
            name="manually_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ptfile",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ptfile",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ptfile",
            name="stage",
            field=models.CharField(
                choices=[
                    ("mapping", "Mapping (Warehouse)"),
                    ("sent", "Sent to Patna"),
                    ("posted", "Posted to system"),
                ],
                default="mapping",
                max_length=12,
            ),
        ),
    ]
