# Generated by Django 5.1.15 on 2026-06-28 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ptmapper", "0002_ptfile_manually_edited_ptfile_posted_at_and_more"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ptfile",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pt_files",
                to="vendors.booking",
            ),
        ),
        migrations.AddField(
            model_name="ptfile",
            name="inward_doc_number",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
