# Generated by Django 5.1.15 on 2026-06-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmapper', '0004_remove_ptfile_inward_doc_number_remove_ptfile_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptrow',
            name='provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
