# Generated by Django 5.1.15 on 2026-07-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmapper', '0005_ptrow_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptrow',
            name='raw',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
