# Generated by Django 5.1.15 on 2026-07-02 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmapper', '0006_ptrow_raw'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('line_no', models.IntegerField(default=0)),
                ('brand', models.CharField(blank=True, default='', max_length=160)),
                ('column', models.CharField(max_length=40)),
                ('dimension', models.CharField(blank=True, default='', max_length=20)),
                ('raw_value', models.CharField(blank=True, default='', max_length=300)),
                ('old_value', models.CharField(blank=True, default='', max_length=300)),
                ('new_value', models.CharField(blank=True, default='', max_length=300)),
                ('provenance_before', models.CharField(blank=True, default='', max_length=20)),
                ('edit_kind', models.CharField(choices=[('cell', 'Cell edit'), ('fill_blank', 'Fill blank cells'), ('fill_all', 'Fill all cells'), ('fill_match_raw', 'Fill cells matching a raw value')], default='cell', max_length=16)),
                ('remember', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pt_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_events', to='ptmapper.ptfile')),
                ('pt_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_events', to='ptmapper.ptrow')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dimension', 'raw_value'], name='ptmapper_co_dimensi_f5b933_idx'), models.Index(fields=['brand', 'dimension'], name='ptmapper_co_brand_041a25_idx'), models.Index(fields=['created_at'], name='ptmapper_co_created_67eb17_idx')],
            },
        ),
    ]
