# Generated by Django 5.1.15 on 2026-07-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmapper', '0007_correctionevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lookup',
            options={'ordering': ['dimension', 'brand', 'source_key']},
        ),
        migrations.AlterUniqueTogether(
            name='lookup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lookup',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterUniqueTogether(
            name='lookup',
            unique_together={('dimension', 'source_key', 'brand')},
        ),
    ]
