# Generated by Django 5.1.15 on 2026-07-02 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptmapper', '0008_alter_lookup_options_alter_lookup_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LookupProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dimension', models.CharField(max_length=20)),
                ('source_key', models.CharField(max_length=240)),
                ('target_value', models.CharField(max_length=160)),
                ('brand', models.CharField(blank=True, default='', max_length=160)),
                ('origin', models.CharField(choices=[('review', 'Review resolution'), ('remember', 'Remember this'), ('mined', 'Deterministic miner'), ('llm', 'LLM miner')], max_length=12)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_rejected', 'Auto-rejected (shadow conflict)')], default='proposed', max_length=16)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'proposed')), fields=('dimension', 'source_key', 'brand'), name='uniq_open_lookup_proposal')],
            },
        ),
    ]
