# Generated by Django 5.1.15 on 2026-07-02 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0004_remove_grn_status'),
        ('ptmapper', '0010_trigram'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptfile',
            name='grn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pt_files', to='inbound.grn'),
        ),
        migrations.AddField(
            model_name='ptfile',
            name='source',
            field=models.CharField(choices=[('brand_file', 'Brand PT file'), ('invoice', 'Authored from GRN / invoice')], default='brand_file', max_length=12),
        ),
    ]
