# Generated by Django 5.1.15 on 2026-07-03 13:57

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def check_no_duplicate_live_pts(apps, schema_editor):
    """Guard the constraint: fail loudly (never silently) if any GRN already carries
    two live (non-cancelled) PTs, so the AddConstraint can't blow up mid-DDL. If this
    raises, resolve the duplicates (cancel/reverse the extra PTs) and re-run."""
    PtFile = apps.get_model("ptmapper", "PtFile")
    dupes = (
        PtFile.objects.exclude(docstatus=2)  # 2 = DocStatus.CANCELLED
        .filter(grn__isnull=False)
        .values("grn_id")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )
    offenders = {row["grn_id"]: row["n"] for row in dupes}
    if offenders:
        raise RuntimeError(
            "Cannot add uniq_live_pt_per_grn: these GRNs already have more than one "
            f"live PT — cancel/reverse the extras first: {offenders}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_glentry'),
        ('files', '0001_initial'),
        ('inbound', '0005_grn_kind'),
        ('ptmapper', '0012_seed_authoring_vocabulary'),
        ('vendors', '0002_moneyfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(check_no_duplicate_live_pts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='ptfile',
            constraint=models.UniqueConstraint(condition=models.Q(('docstatus', 2), _negated=True), fields=('grn',), name='uniq_live_pt_per_grn'),
        ),
    ]
