# Generated by Django 5.1.15 on 2026-09-13 15:25

import core.goods_fields
import django.contrib.postgres.constraints
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_tenant_authenticationfailure_tenant_and_more'),
        ('core', '0009_voucherseries_tenant_and_more'),
        ('files', '0004_evidencelink_tenant_evidenceobject_actor_and_more'),
        ('inbound', '0006_arrivaldecision_arrivalhead_countergrndraft_and_more'),
        ('masters', '0012_style_productsku_identitypick_skualias_and_more'),
        ('outbound', '0026_gapresolution_goodscountpass_goodsmovement_and_more'),
        ('ptmapper', '0013_ptfile_uniq_live_pt_per_grn'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningManifest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('dataset_key', models.CharField(max_length=100)),
                ('batch_key', models.CharField(max_length=100)),
                ('revision', models.IntegerField(default=1)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningManifestVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('revision', models.IntegerField()),
                ('cutoff_at', models.DateTimeField()),
                ('content_hash', models.CharField(max_length=64)),
                ('row_count', models.IntegerField(default=0)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='ptmapper.openingmanifest')),
                ('profile_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.configversion')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('source_evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.evidenceobject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningManifestRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('source_row_key', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('verification', models.JSONField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
                ('manifest_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='ptmapper.openingmanifestversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='openingmanifest',
            name='approved_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ptmapper.openingmanifestversion'),
        ),
        migrations.AddField(
            model_name='openingmanifest',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ptmapper.openingmanifestversion'),
        ),
        migrations.CreateModel(
            name='GoodsPt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('receipt_kind', models.CharField(blank=True, choices=[('primary', 'Primary'), ('supplement', 'Supplement')], max_length=10, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='goods_pt', to='core.documentidentity')),
                ('grn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pts', to='inbound.goodsgrn')),
                ('preparer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pts', to='outbound.goodstransfer')),
                ('manifest_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pts', to='ptmapper.openingmanifestversion')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningVariance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('decision', models.JSONField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('manifest_row', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variances', to='ptmapper.openingmanifestrow')),
                ('profile_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.configversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('lines', models.JSONField()),
                ('label_profile', models.JSONField()),
                ('reason_code', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(choices=[('prepared', 'Prepared'), ('attempted', 'Attempted'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='prepared', max_length=10)),
                ('revision', models.IntegerField(default=1)),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.evidenceobject')),
                ('pt_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.officialversion')),
                ('reprint_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reprints', to='ptmapper.printjob')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('template_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.configversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PrintEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('outcome', models.CharField(choices=[('attempted', 'Attempted'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('unknown', 'Unknown'), ('scan_verified', 'Scan Verified')], max_length=14)),
                ('details', models.JSONField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='ptmapper.printjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('dataset_key', models.CharField(max_length=100)),
                ('source_row_key', models.CharField(max_length=100)),
                ('portion', core.goods_fields.PortionField()),
                ('pt_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.officialversion')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
                ('manifest_row', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ptmapper.openingmanifestrow')),
            ],
            options={
                'indexes': [models.Index(fields=['pt_version'], name='ptmapper_op_pt_vers_6c18e9_idx')],
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('tenant', '='), ('dataset_key', '='), ('site', '='), ('source_row_key', '='), ('portion', '&&')], name='ex_openingclaim_overlap')],
            },
        ),
        migrations.AddConstraint(
            model_name='openingmanifestversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='ptmapper_openingmanifestversion_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='openingmanifestversion',
            constraint=models.UniqueConstraint(fields=('manifest', 'revision'), name='uq_manifestversion_revision'),
        ),
        migrations.AddConstraint(
            model_name='openingmanifestrow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='ptmapper_openingmanifestrow_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='openingmanifestrow',
            constraint=models.UniqueConstraint(fields=('manifest_version', 'source_row_key'), name='uq_manifestrow_key'),
        ),
        migrations.AddConstraint(
            model_name='openingmanifest',
            constraint=models.UniqueConstraint(fields=('tenant', 'site', 'batch_key'), name='uq_openingmanifest_batch'),
        ),
        migrations.AddConstraint(
            model_name='goodspt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('grn__isnull', False), ('manifest_version__isnull', True), ('transfer__isnull', True)), models.Q(('grn__isnull', True), ('manifest_version__isnull', False), ('transfer__isnull', True)), models.Q(('grn__isnull', True), ('manifest_version__isnull', True), ('transfer__isnull', False)), _connector='OR'), name='ck_goodspt_one_purpose'),
        ),
        migrations.AddConstraint(
            model_name='goodspt',
            constraint=models.CheckConstraint(condition=models.Q(('grn__isnull', True), ('receipt_kind__isnull', False), _connector='OR'), name='ck_goodspt_receipt_kind'),
        ),
        migrations.AddConstraint(
            model_name='goodspt',
            constraint=models.UniqueConstraint(condition=models.Q(('receipt_kind', 'primary')), fields=('grn',), name='uq_goodspt_primary_per_grn'),
        ),
        migrations.AddConstraint(
            model_name='openingvariance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='ptmapper_openingvariance_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='openingvariance',
            constraint=models.CheckConstraint(condition=models.Q(('maker', models.F('approved_by')), _negated=True), name='ck_openingvariance_distinct'),
        ),
        migrations.AddConstraint(
            model_name='printjob',
            constraint=models.CheckConstraint(condition=models.Q(('reprint_of__isnull', True), ('reason_code__isnull', False), _connector='OR'), name='ck_printjob_reprint_reason'),
        ),
        migrations.AddIndex(
            model_name='printevent',
            index=models.Index(fields=['job', 'recorded_at'], name='ptmapper_pr_job_id_d0b6ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='printevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='ptmapper_printevent_one_actor'),
        ),
    ]
