# Generated by Django 5.1.15 on 2026-09-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_enforce_role_tenant'),
        ('core', '0009_voucherseries_tenant_and_more'),
        ('inbound', '0008_observation_alias_context'),
        ('masters', '0019_backfill_custody_system_location'),
        ('outbound', '0027_countsnapshot_lot_countsnapshot_site_and_more'),
        ('ptmapper', '0015_printjob_partial_outcome'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='goodspt',
            constraint=models.UniqueConstraint(condition=models.Q(('manifest_version__isnull', False)), fields=('manifest_version',), name='uq_goodspt_per_manifest_version'),
        ),
    ]
