# Generated by Django 5.1.15 on 2026-09-21 22:05

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_store_roles'),
        ('core', '0010_documentidentity_site_unless_booking'),
        ('masters', '0021_season_historical_unknown_and_more'),
        ('ptmapper', '0016_goodspt_per_manifest_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningSeasonCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=500)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('from_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.season')),
                ('manifest_row', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='season_corrections', to='ptmapper.openingmanifestrow')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
                ('to_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.season')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['manifest_row', 'recorded_at'], name='ptmapper_op_manifes_e35281_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='ptmapper_openingseasoncorrection_one_actor'), models.CheckConstraint(condition=models.Q(('from_season', models.F('to_season')), _negated=True), name='ck_openingseasoncorrection_changes_season')],
            },
        ),
    ]
