# Generated by Django 5.2.17 on 2026-09-30 04:48

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_installationregistration'),
        ('approvals', '0016_so03_authority_pin'),
        ('core', '0012_customer_reservation'),
        ('files', '0004_evidencelink_tenant_evidenceobject_actor_and_more'),
        ('masters', '0033_first_store_controls'),
        ('ptmapper', '0018_delete_legacy_pt_mapper'),
    ]

    operations = [
        migrations.CreateModel(
            name='SohImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('source_hash', models.CharField(max_length=64)),
                ('source_name', models.CharField(max_length=240)),
                ('source_metadata', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(default='uploaded', max_length=20)),
                ('cutoff_at', models.DateTimeField(null=True)),
                ('configuration', models.JSONField(default=dict)),
                ('reviewed_hash', models.CharField(blank=True, max_length=64)),
                ('reconciliation', models.JSONField(default=dict)),
                ('approval_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='approvals.approvalrequest')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('source_evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.evidenceobject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
            ],
        ),
        migrations.CreateModel(
            name='SohImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('batch_index', models.PositiveIntegerField()),
                ('row_count', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('manifest', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='soh_batch', to='ptmapper.openingmanifest')),
                ('source_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='ptmapper.sohimport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SohImportReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('revision', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('source_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='ptmapper.sohimport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SohImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('ordinal', models.PositiveIntegerField()),
                ('source_row_key', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=128)),
                ('source_brand', models.CharField(max_length=240)),
                ('quantity', models.IntegerField()),
                ('mrp_paise', models.BigIntegerField(null=True)),
                ('source_rate_paise', models.BigIntegerField(null=True)),
                ('source', models.JSONField(default=dict)),
                ('mapping', models.JSONField(default=dict)),
                ('verification', models.JSONField(default=dict)),
                ('exclusion_reason', models.CharField(blank=True, max_length=500)),
                ('source_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='ptmapper.sohimport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sohimport',
            constraint=models.UniqueConstraint(fields=('tenant', 'site', 'source_hash'), name='uq_soh_source_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='sohimportbatch',
            constraint=models.UniqueConstraint(fields=('source_import', 'batch_index'), name='uq_soh_child_batch'),
        ),
        migrations.AddConstraint(
            model_name='sohimportreview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='ptmapper_sohimportreview_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='sohimportreview',
            constraint=models.UniqueConstraint(fields=('source_import', 'revision'), name='uq_soh_review_revision'),
        ),
        migrations.AddConstraint(
            model_name='sohimportrow',
            constraint=models.UniqueConstraint(fields=('source_import', 'ordinal'), name='uq_soh_source_row'),
        ),
        migrations.AddConstraint(
            model_name='sohimportrow',
            constraint=models.UniqueConstraint(fields=('source_import', 'barcode'), name='uq_soh_source_barcode'),
        ),
    ]
