from collections.abc import Iterator
from io import BytesIO
from typing import Any

class Cell:
    v: Any

class Worksheet:
    def __enter__(self) -> Worksheet: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...
    def rows(self) -> Iterator[list[Cell]]: ...

class Workbook:
    sheets: list[str]
    def __enter__(self) -> Workbook: ...
    def __exit__(self, exc_type: object, exc_value: object, traceback: object) -> None: ...
    def get_sheet(self, name: str) -> Worksheet: ...

def open_workbook(source: BytesIO) -> Workbook: ...
