# Generated by Django 5.1.15 on 2026-07-06 06:58

import core.money
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0005_glentry"),
        ("masters", "0004_seed_default_category_margin"),
        ("vendors", "0003_bookingline_store"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnToVendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "idempotency_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "docstatus",
                    models.IntegerField(
                        choices=[(0, "draft"), (1, "submitted"), (2, "cancelled")],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "return_type",
                    models.CharField(
                        choices=[
                            ("defective", "Defective / GR return"),
                            ("seasonal", "Season-end return"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "logistics_route",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("store_pickup", "Brand collects from store (Madura)"),
                            ("warehouse", "Consolidated at warehouse"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("season", models.CharField(blank=True, default="", max_length=120)),
                (
                    "return_window_date",
                    models.DateField(
                        blank=True,
                        help_text="Deadline for seasonal return (alerts at 30/15/7 days).",
                        null=True,
                    ),
                ),
                ("credit_note_received", models.BooleanField(default=False)),
                ("credit_note_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rtvs",
                        to="masters.brand",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rtvs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.voucherseries",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rtvs",
                        to="masters.store",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rtvs",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "outbound_return_to_vendor",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReturnToVendorLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku_code", models.CharField(max_length=64)),
                ("design", models.CharField(blank=True, default="", max_length=120)),
                ("color", models.CharField(blank=True, default="", max_length=60)),
                ("size", models.CharField(blank=True, default="", max_length=24)),
                ("brand", models.CharField(blank=True, default="", max_length=120)),
                ("season", models.CharField(blank=True, default="", max_length=120)),
                ("item", models.CharField(blank=True, default="", max_length=120)),
                ("hsn", models.CharField(blank=True, default="", max_length=24)),
                ("qty", models.IntegerField()),
                ("unit_cost_paise", core.money.MoneyField(default=0)),
                (
                    "rtv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="outbound.returntovendor",
                    ),
                ),
            ],
            options={
                "db_table": "outbound_return_to_vendor_line",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "idempotency_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "docstatus",
                    models.IntegerField(
                        choices=[(0, "draft"), (1, "submitted"), (2, "cancelled")],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("shrinkage", "Shrinkage"),
                            ("miscount", "Miscount"),
                            ("damage", "Damage"),
                            ("surplus_found", "Surplus found"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required for variances above tolerance.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjustments_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjustments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.voucherseries",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="masters.store",
                    ),
                ),
            ],
            options={
                "db_table": "outbound_stock_adjustment",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StockAdjustmentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku_code", models.CharField(max_length=64)),
                ("design", models.CharField(blank=True, default="", max_length=120)),
                ("color", models.CharField(blank=True, default="", max_length=60)),
                ("size", models.CharField(blank=True, default="", max_length=24)),
                ("brand", models.CharField(blank=True, default="", max_length=120)),
                ("season", models.CharField(blank=True, default="", max_length=120)),
                ("item", models.CharField(blank=True, default="", max_length=120)),
                ("hsn", models.CharField(blank=True, default="", max_length=24)),
                ("book_qty", models.IntegerField()),
                ("counted_qty", models.IntegerField()),
                (
                    "adj_qty",
                    models.IntegerField(
                        help_text="counted − book; + surplus, − shrinkage"
                    ),
                ),
                ("unit_cost_paise", core.money.MoneyField(default=0)),
                (
                    "adjustment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="outbound.stockadjustment",
                    ),
                ),
            ],
            options={
                "db_table": "outbound_stock_adjustment_line",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StoreTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "idempotency_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "docstatus",
                    models.IntegerField(
                        choices=[(0, "draft"), (1, "submitted"), (2, "cancelled")],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("store_split", "Store split (warehouse → store)"),
                            ("inter_store", "Inter-store transfer"),
                        ],
                        default="inter_store",
                        max_length=16,
                    ),
                ),
                (
                    "is_cross_state",
                    models.BooleanField(
                        default=False,
                        help_text="Auto-set: True when source & destination GSTINs differ.",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sister_store_request", "Sister store request"),
                            ("slow_mover", "Slow mover"),
                            ("seasonal_swap", "Seasonal swap"),
                            ("free_floor_space", "Free floor space"),
                            ("customer_waiting", "Customer waiting"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                (
                    "transport_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("public_bus", "Public bus"),
                            ("courier", "Courier"),
                            ("own_vehicle", "Own vehicle"),
                            ("hand_carried", "Hand-carried"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "transport_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bus number / courier AWB / vehicle plate",
                        max_length=120,
                    ),
                ),
                (
                    "dispatcher_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "expected_arrival_note",
                    models.CharField(blank=True, default="", max_length=240),
                ),
                (
                    "eway_bill_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Mandatory for cross-state (Bihar ↔ Jharkhand).",
                        max_length=60,
                    ),
                ),
                ("dispatch_date", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="masters.store",
                    ),
                ),
                (
                    "dispatched_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_dispatched",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.voucherseries",
                    ),
                ),
                (
                    "source_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="masters.store",
                    ),
                ),
            ],
            options={
                "db_table": "outbound_store_transfer",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StoreTransferLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku_code", models.CharField(max_length=64)),
                ("design", models.CharField(blank=True, default="", max_length=120)),
                ("color", models.CharField(blank=True, default="", max_length=60)),
                ("size", models.CharField(blank=True, default="", max_length=24)),
                ("brand", models.CharField(blank=True, default="", max_length=120)),
                ("season", models.CharField(blank=True, default="", max_length=120)),
                ("item", models.CharField(blank=True, default="", max_length=120)),
                ("hsn", models.CharField(blank=True, default="", max_length=24)),
                ("qty_dispatched", models.IntegerField()),
                ("qty_received", models.IntegerField(default=0)),
                ("unit_cost_paise", core.money.MoneyField(default=0)),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="outbound.storetransfer",
                    ),
                ),
            ],
            options={
                "db_table": "outbound_store_transfer_line",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TransferReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("receipt_date", models.DateTimeField(auto_now_add=True)),
                (
                    "receipt_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("complete", "Complete"),
                            ("shortfall", "Shortfall"),
                        ],
                        default="complete",
                        max_length=12,
                    ),
                ),
                ("shortfall_notes", models.TextField(blank=True, default="")),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transfer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt",
                        to="outbound.storetransfer",
                    ),
                ),
            ],
            options={
                "db_table": "outbound_transfer_receipt",
                "ordering": ["-receipt_date"],
            },
        ),
        migrations.CreateModel(
            name="VFlip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "idempotency_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "docstatus",
                    models.IntegerField(
                        choices=[(0, "draft"), (1, "submitted"), (2, "cancelled")],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("season", models.CharField(blank=True, default="", max_length=120)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        help_text="Owner or Finance role required.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vflips_authorized",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vflips_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vflips",
                        to="masters.brand",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.voucherseries",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vflips",
                        to="masters.store",
                    ),
                ),
            ],
            options={
                "db_table": "outbound_vflip",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VFlipLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku_code", models.CharField(max_length=64)),
                ("design", models.CharField(blank=True, default="", max_length=120)),
                ("color", models.CharField(blank=True, default="", max_length=60)),
                ("size", models.CharField(blank=True, default="", max_length=24)),
                ("brand", models.CharField(blank=True, default="", max_length=120)),
                ("season", models.CharField(blank=True, default="", max_length=120)),
                ("item", models.CharField(blank=True, default="", max_length=120)),
                ("hsn", models.CharField(blank=True, default="", max_length=24)),
                ("qty", models.IntegerField()),
                ("unit_cost_paise", core.money.MoneyField(default=0)),
                (
                    "vflip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="outbound.vflip",
                    ),
                ),
            ],
            options={
                "db_table": "outbound_vflip_line",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="WriteOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "idempotency_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "docstatus",
                    models.IntegerField(
                        choices=[(0, "draft"), (1, "submitted"), (2, "cancelled")],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="writeoffs_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="writeoffs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.voucherseries",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="writeoffs",
                        to="masters.store",
                    ),
                ),
            ],
            options={
                "db_table": "outbound_write_off",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WriteOffLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku_code", models.CharField(max_length=64)),
                ("design", models.CharField(blank=True, default="", max_length=120)),
                ("color", models.CharField(blank=True, default="", max_length=60)),
                ("size", models.CharField(blank=True, default="", max_length=24)),
                ("brand", models.CharField(blank=True, default="", max_length=120)),
                ("season", models.CharField(blank=True, default="", max_length=120)),
                ("item", models.CharField(blank=True, default="", max_length=120)),
                ("hsn", models.CharField(blank=True, default="", max_length=24)),
                ("qty", models.IntegerField()),
                ("unit_cost_paise", core.money.MoneyField(default=0)),
                (
                    "writeoff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="outbound.writeoff",
                    ),
                ),
            ],
            options={
                "db_table": "outbound_write_off_line",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="returntovendor",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("docstatus", 0), ("doc_number__isnull", False), _connector="OR"
                ),
                name="outbound_returntovendor_posted_has_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="returntovendor",
            constraint=models.CheckConstraint(
                condition=models.Q(("docstatus__in", [0, 1, 2])),
                name="outbound_returntovendor_docstatus_domain",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("docstatus", 0), ("doc_number__isnull", False), _connector="OR"
                ),
                name="outbound_stockadjustment_posted_has_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(("docstatus__in", [0, 1, 2])),
                name="outbound_stockadjustment_docstatus_domain",
            ),
        ),
        migrations.AddConstraint(
            model_name="storetransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("docstatus", 0), ("doc_number__isnull", False), _connector="OR"
                ),
                name="outbound_storetransfer_posted_has_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="storetransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("docstatus__in", [0, 1, 2])),
                name="outbound_storetransfer_docstatus_domain",
            ),
        ),
        migrations.AddConstraint(
            model_name="vflip",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("docstatus", 0), ("doc_number__isnull", False), _connector="OR"
                ),
                name="outbound_vflip_posted_has_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="vflip",
            constraint=models.CheckConstraint(
                condition=models.Q(("docstatus__in", [0, 1, 2])),
                name="outbound_vflip_docstatus_domain",
            ),
        ),
        migrations.AddConstraint(
            model_name="writeoff",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("docstatus", 0), ("doc_number__isnull", False), _connector="OR"
                ),
                name="outbound_writeoff_posted_has_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="writeoff",
            constraint=models.CheckConstraint(
                condition=models.Q(("docstatus__in", [0, 1, 2])),
                name="outbound_writeoff_docstatus_domain",
            ),
        ),
    ]
