# Generated by Django 5.1.15 on 2026-07-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0002_fsm_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetransferline',
            name='qty_planned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storetransferline',
            name='qty_dispatched',
            field=models.IntegerField(default=0),
        ),
    ]
