# Generated by Django 5.1.15 on 2026-07-23 19:37

import core.money
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_glentry'),
        ('masters', '0004_seed_default_category_margin'),
        ('outbound', '0003_storetransferline_qty_planned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkDamaged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('idempotency_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('docstatus', models.IntegerField(choices=[(0, 'draft'), (1, 'submitted'), (2, 'cancelled')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, default='', max_length=240)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_marks_created', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.voucherseries')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_marks', to='masters.store')),
            ],
            options={
                'db_table': 'outbound_mark_damaged',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarkDamagedLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku_code', models.CharField(max_length=64)),
                ('design', models.CharField(blank=True, default='', max_length=120)),
                ('color', models.CharField(blank=True, default='', max_length=60)),
                ('size', models.CharField(blank=True, default='', max_length=24)),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('season', models.CharField(blank=True, default='', max_length=120)),
                ('item', models.CharField(blank=True, default='', max_length=120)),
                ('hsn', models.CharField(blank=True, default='', max_length=24)),
                ('qty', models.IntegerField()),
                ('unit_cost_paise', core.money.MoneyField(default=0)),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='outbound.markdamaged')),
            ],
            options={
                'db_table': 'outbound_mark_damaged_line',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='markdamaged',
            constraint=models.CheckConstraint(condition=models.Q(('docstatus', 0), ('doc_number__isnull', False), _connector='OR'), name='outbound_markdamaged_posted_has_number'),
        ),
        migrations.AddConstraint(
            model_name='markdamaged',
            constraint=models.CheckConstraint(condition=models.Q(('docstatus__in', [0, 1, 2])), name='outbound_markdamaged_docstatus_domain'),
        ),
    ]
