# Generated by Django 5.1.15 on 2026-07-24 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0005_mark_damaged_fsm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Stamped by the approvals inbox on approve — never typed (#70).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vflip',
            name='authorized_by',
            field=models.ForeignKey(blank=True, help_text='Stamped by the approvals inbox on approve — never typed (#70).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vflips_authorized', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='writeoff',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Stamped by the approvals inbox on approve — never typed (#70).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='writeoffs_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
