# Generated by Django 5.1.15 on 2026-07-26 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0010_gap_closure_fsm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='markdamaged',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, help_text='Stamped by the approvals inbox on confirm — never typed (#138).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_marks_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='markdamaged',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Who reported the damage — kept for good, on the piece (#138).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_marks_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
