# Generated by Django 5.1.15 on 2026-07-26 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_seed_default_category_margin'),
        ('outbound', '0012_alter_transferreceiptexception_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open — counting'), ('submitted', 'Submitted'), ('closed', 'Closed — variance applied')], default='open', max_length=12)),
                ('note', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment', models.ForeignKey(blank=True, help_text='The correction this count produced, once its variance was applied.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktakes', to='outbound.stockadjustment')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocktakes_opened', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktakes', to='masters.store')),
            ],
            options={
                'db_table': 'outbound_stocktake',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CountSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('store', 'Whole store'), ('brand', 'One brand'), ('section', 'One section')], max_length=8)),
                ('scope_value', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('open', 'Open — counting'), ('submitted', 'Submitted'), ('closed', 'Closed — variance applied')], default='open', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='count_sessions', to=settings.AUTH_USER_MODEL)),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='outbound.stocktake')),
            ],
            options={
                'db_table': 'outbound_count_session',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CountSessionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=64)),
                ('design', models.CharField(blank=True, default='', max_length=120)),
                ('color', models.CharField(blank=True, default='', max_length=60)),
                ('size', models.CharField(blank=True, default='', max_length=24)),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('season', models.CharField(blank=True, default='', max_length=120)),
                ('item', models.CharField(blank=True, default='', max_length=120)),
                ('hsn', models.CharField(blank=True, default='', max_length=24)),
                ('counted_qty', models.IntegerField(default=0)),
                ('book_qty', models.IntegerField(blank=True, help_text='The book at submit. Null while the session is open — blind (#76).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='outbound.countsession')),
            ],
            options={
                'db_table': 'outbound_count_session_line',
                'ordering': ['sku_code'],
                'constraints': [models.UniqueConstraint(fields=('session', 'sku_code'), name='uq_count_session_line_sku')],
            },
        ),
    ]
