# Generated by Django 5.1.15 on 2026-07-27 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outbound", "0015_backfill_transfer_pt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="storetransfer",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Stamped from the approvals inbox at dispatch — never typed (#137).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
