"""Return to brand, rebuilt around the returnable pool (#75).

Mostly additive. The one destructive part is deliberate: ``credit_note_received``
and ``credit_note_date`` leave the document and become the ``ReturnCreditNote``
companion, because a posted document is immutable at the kernel and a credit note
arrives days or weeks *after* the return posts — the two columns could never have
been written on a real return. Any value an install does hold is carried across
before the columns go, so nothing recorded is lost.
"""

# Generated by Django 5.1.15 on 2026-07-28 04:20

import core.money
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def carry_credit_notes(apps, schema_editor):
    """Move any recorded credit note onto the companion before the columns go.

    A note with no date cannot become a row — ``received_on`` is the whole point
    of the record — so the handful of "received, date unknown" rows (if an
    install has any) are left for a person to re-enter rather than given an
    invented date.
    """
    ReturnToVendor = apps.get_model("outbound", "ReturnToVendor")
    ReturnCreditNote = apps.get_model("outbound", "ReturnCreditNote")
    for rtv in ReturnToVendor.objects.filter(
        credit_note_received=True, credit_note_date__isnull=False
    ):
        ReturnCreditNote.objects.get_or_create(
            rtv_id=rtv.pk, defaults={"received_on": rtv.credit_note_date}
        )


def return_credit_notes(apps, schema_editor):
    """Reverse: put the dates back on the documents the columns are returning to."""
    ReturnCreditNote = apps.get_model("outbound", "ReturnCreditNote")
    ReturnToVendor = apps.get_model("outbound", "ReturnToVendor")
    for note in ReturnCreditNote.objects.all():
        ReturnToVendor.objects.filter(pk=note.rtv_id).update(
            credit_note_received=True, credit_note_date=note.received_on
        )


class Migration(migrations.Migration):
    dependencies = [
        ("outbound", "0019_stock_request_fsm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="returntovendor",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Stamped by the approvals inbox on approve — never typed (#75).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rtvs_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="returntovendor",
            name="cap_allowance_paise",
            field=core.money.MoneyField(default=0),
        ),
        migrations.AddField(
            model_name="returntovendor",
            name="cap_exceeded_by_paise",
            field=core.money.MoneyField(
                default=0,
                help_text="How far past the allowance this return goes. Flagged, never blocked (Rule 5) — the pieces are already defective or already unsold, and refusing the document would only mean nobody records where they went.",
            ),
        ),
        migrations.AddField(
            model_name="returntovendor",
            name="cap_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="The brand's negotiated allowance percentage on the day. 0 for the three models that have no cap.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="returntovendor",
            name="cap_used_before_paise",
            field=core.money.MoneyField(default=0),
        ),
        migrations.AddField(
            model_name="returntovendor",
            name="via_transfer",
            field=models.ForeignKey(
                blank=True,
                help_text="The store→warehouse transfer that brought these pieces here, for the consolidated route. Required for it: 'via warehouse' is a claim that a movement already happened, and a claim with nothing behind it is how stock goes missing between two documents (#75).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consolidated_returns",
                to="outbound.storetransfer",
            ),
        ),
        migrations.AddField(
            model_name="returntovendorline",
            name="source",
            field=models.CharField(
                choices=[
                    ("quarantine", "Confirmed damaged (quarantine)"),
                    ("season_end", "Season-end unsold stock"),
                ],
                default="season_end",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="returntovendor",
            name="logistics_route",
            field=models.CharField(
                blank=True,
                choices=[
                    ("store_pickup", "Brand collects from store"),
                    ("store_dispatch", "Store sends to brand"),
                    ("warehouse", "Consolidated at warehouse"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="returntovendor",
            name="return_window_date",
            field=models.DateField(
                blank=True,
                help_text="The earliest deadline on this return's lines, snapshotted at draft time. The screen counts down to it and turns amber inside the last fortnight.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ReturnCreditNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("received_on", models.DateField(help_text="The date on the brand's credit note.")),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The brand's own credit-note number, where the paper carries one.",
                        max_length=120,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_notes_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rtv",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_note",
                        to="outbound.returntovendor",
                    ),
                ),
            ],
            options={
                "db_table": "outbound_return_credit_note",
                "ordering": ["-received_on"],
            },
        ),
        migrations.RunPython(carry_credit_notes, return_credit_notes),
        migrations.RemoveField(
            model_name="returntovendor",
            name="credit_note_date",
        ),
        migrations.RemoveField(
            model_name="returntovendor",
            name="credit_note_received",
        ),
    ]
