# Generated by Django 5.1.15 on 2026-07-29 14:13

import core.money
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0021_backfill_return_approvals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustmentline',
            name='reason',
            field=models.CharField(blank=True, choices=[('shrinkage', 'Shrinkage'), ('miscount', 'Miscount'), ('damage', 'Damage'), ('surplus_found', 'Surplus found'), ('other', 'Other')], default='', help_text="Why *this* piece is off, where a recount said so (#78). The document's own reason is the whole correction's; one count can find a theft on one rail and a miscount on the next, and a single column would have to lose one of them.", max_length=16),
        ),
        migrations.CreateModel(
            name='Recount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=64)),
                ('book_qty', models.IntegerField(help_text='The book snapshot the first count was measured against.')),
                ('first_counted_qty', models.IntegerField(help_text='What the first count merged to.')),
                ('counted_qty', models.IntegerField(help_text='What the recount found — the number that posts.')),
                ('unit_cost_paise', core.money.MoneyField(default=0, help_text="What the books said one piece was worth when the second person looked — the trail's record of what was at stake, never the source the band or the posting reads. Never from the payload (#103).")),
                ('reason', models.CharField(choices=[('shrinkage', 'Shrinkage'), ('miscount', 'Miscount'), ('damage', 'Damage'), ('surplus_found', 'Surplus found'), ('other', 'Other')], help_text='Why the difference is there — theft, miscount, damage or found.', max_length=16)),
                ('recounted_at', models.DateTimeField(auto_now=True, help_text='When the answer on this row was last given. ``auto_now``, not ``auto_now_add``, because a recounter may correct their own answer — a fat finger on a phone is not an audit event — and the row should then date from the answer it actually holds. ``created_at`` keeps when the piece was first recounted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recounted_by', models.ForeignKey(blank=True, help_text='Never anyone who counted this piece the first time — a floor rule (#78).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recounts', to=settings.AUTH_USER_MODEL)),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recounts', to='outbound.stocktake')),
            ],
            options={
                'db_table': 'outbound_recount',
                'ordering': ['sku_code'],
                'constraints': [models.UniqueConstraint(fields=('stocktake', 'sku_code'), name='uq_recount_sku')],
            },
        ),
    ]
