# Generated by Django 5.1.15 on 2026-07-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0023_move_stock_request_approvals_to_asker'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='expected_arrival_at',
            field=models.DateTimeField(blank=True, help_text='The time the counter quoted the waiting customer. A quote, never a promise: no hold is placed on the piece (#175).', null=True),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='source',
            field=models.CharField(choices=[('manual', 'Raised by hand'), ('cross_store_search', 'From cross-store search')], default='manual', help_text='How the ask was raised — by hand, or from the cross-store search (#175).', max_length=24),
        ),
    ]
