# Generated by Django 5.1.15 on 2026-08-03 19:55

import core.money
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outbound", "0024_stock_request_source_and_expected_arrival"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="storetransfer",
            name="partner_billing_value_paise",
            field=core.money.MoneyField(
                blank=True,
                help_text="Set at dispatch, only when the destination is a partner store: qty dispatched × the books' Purchase Price. Always computed for the record; whether it also posts a receivable is `BillingPolicy.current()`.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storetransfer",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sister_store_request", "Sister store request"),
                    ("slow_mover", "Slow mover"),
                    ("seasonal_swap", "Seasonal swap"),
                    ("free_floor_space", "Free floor space"),
                    ("customer_waiting", "Customer waiting"),
                    ("warehouse_allocation", "Warehouse allocation"),
                    ("other", "Other"),
                ],
                default="",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="BillingPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("informational", "Informational only — no ledger entry"),
                            ("gl_posting", "Post a receivable at Purchase Price"),
                        ],
                        default="informational",
                        max_length=16,
                    ),
                ),
                (
                    "set_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who last chose this dial.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_policies_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "billing policies",
                "db_table": "outbound_billing_policy",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="ck_billingpolicy_singleton"
                    )
                ],
            },
        ),
    ]
