# Generated by Django 5.1.15 on 2026-09-13 15:25

import core.goods_fields
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_tenant_authenticationfailure_tenant_and_more'),
        ('core', '0009_voucherseries_tenant_and_more'),
        ('masters', '0012_style_productsku_identitypick_skualias_and_more'),
        ('outbound', '0025_storetransfer_partner_billing_value_paise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GapResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('kind', models.CharField(choices=[('short', 'Short'), ('damage', 'Damage'), ('excess', 'Excess')], max_length=8)),
                ('pairing_key', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='GoodsCountPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('pass_no', models.IntegerField()),
                ('scope', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted'), ('selected', 'Selected'), ('superseded', 'Superseded')], default='open', max_length=10)),
                ('observation_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('revision', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('kind', models.CharField(choices=[('bin_move', 'Bin Move'), ('hold', 'Hold'), ('release', 'Release'), ('adjustment_up', 'Adjustment Up'), ('adjustment_down', 'Adjustment Down'), ('writeoff', 'Writeoff'), ('shrinkage', 'Shrinkage'), ('rtv', 'Rtv'), ('transit_shortage', 'Transit Shortage'), ('rtv_cancel', 'Rtv Cancel')], max_length=20)),
                ('rtv_state', models.CharField(blank=True, choices=[('approved', 'approved'), ('dispatched', 'dispatched'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], max_length=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsStocktake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('scope', models.JSONField()),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('requested', 'Requested'), ('open', 'Open'), ('review', 'Review'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='requested', max_length=10)),
                ('last_activity_at', models.DateTimeField()),
                ('revision', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('transport', models.JSONField(default=dict)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('eway_state', models.CharField(choices=[('present', 'present'), ('not_present', 'not_present'), ('manually_verified', 'manually_verified')], default='not_present', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransferEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('dispatch', 'Dispatch'), ('arrival', 'Arrival'), ('check', 'Check'), ('accept', 'Accept'), ('putaway', 'Putaway'), ('eway_added', 'Eway Added'), ('eway_verified', 'Eway Verified'), ('cancelled', 'Cancelled')], max_length=14)),
                ('actual_at', models.DateTimeField()),
                ('details', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('observation_hash', models.CharField(max_length=64)),
                ('variances', models.JSONField()),
                ('stale_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.documentidentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('scope', models.JSONField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='outbound.countdecision')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('portion', core.goods_fields.PortionField()),
                ('address', models.JSONField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
