# Generated by Django 5.1.15 on 2026-09-13 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_tenant_authenticationfailure_tenant_and_more'),
        ('core', '0009_voucherseries_tenant_and_more'),
        ('masters', '0012_style_productsku_identitypick_skualias_and_more'),
        ('outbound', '0026_gapresolution_goodscountpass_goodsmovement_and_more'),
        ('stockledger', '0009_acceptancesession_allocationguard_custodylot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countsnapshot',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stockledger.custodylot'),
        ),
        migrations.AddField(
            model_name='countsnapshot',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='countsnapshot',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='gapresolution',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gap_resolution', to='core.documentidentity'),
        ),
        migrations.AddField(
            model_name='gapresolution',
            name='related_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.documentidentity'),
        ),
        migrations.AddField(
            model_name='gapresolution',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='goodscountpass',
            name='counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='goodscountpass',
            name='entry_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='goodscountpass',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='outbound.goodscountpass'),
        ),
        migrations.AddField(
            model_name='goodscountpass',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='countselection',
            name='count_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='outbound.goodscountpass'),
        ),
        migrations.AddField(
            model_name='goodsmovement',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='goods_movement', to='core.documentidentity'),
        ),
        migrations.AddField(
            model_name='goodsmovement',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.documentidentity'),
        ),
        migrations.AddField(
            model_name='goodsmovement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='goodsstocktake',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='goods_stocktake', to='core.documentidentity'),
        ),
        migrations.AddField(
            model_name='goodsstocktake',
            name='non_trading_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.sitecapabilityevent'),
        ),
        migrations.AddField(
            model_name='goodsstocktake',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='goodsstocktake',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='goodsmovement',
            name='count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='outbound.goodsstocktake'),
        ),
        migrations.AddField(
            model_name='goodscountpass',
            name='stocktake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passes', to='outbound.goodsstocktake'),
        ),
        migrations.AddField(
            model_name='countsnapshot',
            name='stocktake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot', to='outbound.goodsstocktake'),
        ),
        migrations.AddField(
            model_name='countdecision',
            name='stocktake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='outbound.goodsstocktake'),
        ),
        migrations.AddField(
            model_name='goodstransfer',
            name='corrective_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='outbound.goodstransfer'),
        ),
        migrations.AddField(
            model_name='goodstransfer',
            name='destination_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='goodstransfer',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='goods_transfer', to='core.documentidentity'),
        ),
        migrations.AddField(
            model_name='goodstransfer',
            name='source_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='goodstransfer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='gapresolution',
            name='corrective_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='outbound.goodstransfer'),
        ),
        migrations.AddField(
            model_name='gapresolution',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gap_resolutions', to='outbound.goodstransfer'),
        ),
        migrations.AddField(
            model_name='transferevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='transferevent',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='transferevent',
            name='journal_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stockledger.journalbatch'),
        ),
        migrations.AddField(
            model_name='transferevent',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='transferevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='transferevent',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='outbound.goodstransfer'),
        ),
        migrations.AddIndex(
            model_name='countselection',
            index=models.Index(fields=['count_pass'], name='outbound_co_count_p_cbe134_idx'),
        ),
        migrations.AddConstraint(
            model_name='countselection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='outbound_countselection_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='countselection',
            constraint=models.UniqueConstraint(fields=('decision', 'count_pass'), name='uq_countselection'),
        ),
        migrations.AddIndex(
            model_name='goodsstocktake',
            index=models.Index(fields=['site', 'state'], name='outbound_go_site_id_a4aa3c_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsstocktake',
            index=models.Index(fields=['state', 'last_activity_at'], name='outbound_go_state_a34935_idx'),
        ),
        migrations.AddIndex(
            model_name='goodscountpass',
            index=models.Index(fields=['stocktake', 'state'], name='outbound_go_stockta_6c7e59_idx'),
        ),
        migrations.AddConstraint(
            model_name='goodscountpass',
            constraint=models.UniqueConstraint(fields=('stocktake', 'counter', 'pass_no'), name='uq_countpass_counter_no'),
        ),
        migrations.AddConstraint(
            model_name='countsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='outbound_countsnapshot_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='countsnapshot',
            constraint=models.UniqueConstraint(fields=('stocktake', 'lot', 'portion'), name='uq_countsnapshot_portion'),
        ),
        migrations.AddConstraint(
            model_name='countdecision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='outbound_countdecision_one_actor'),
        ),
        migrations.AddIndex(
            model_name='goodstransfer',
            index=models.Index(fields=['source_site'], name='outbound_go_source__cf380f_idx'),
        ),
        migrations.AddIndex(
            model_name='goodstransfer',
            index=models.Index(fields=['destination_site'], name='outbound_go_destina_299758_idx'),
        ),
        migrations.AddConstraint(
            model_name='goodstransfer',
            constraint=models.CheckConstraint(condition=models.Q(('source_site', models.F('destination_site')), _negated=True), name='ck_goodstransfer_sites'),
        ),
        migrations.AddIndex(
            model_name='gapresolution',
            index=models.Index(fields=['transfer', 'pairing_key'], name='outbound_ga_transfe_2690f0_idx'),
        ),
        migrations.AddIndex(
            model_name='transferevent',
            index=models.Index(fields=['transfer', 'recorded_at'], name='outbound_tr_transfe_0444f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='outbound_transferevent_one_actor'),
        ),
    ]
