# Generated by Django 5.1.15 on 2026-09-21 23:51

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_store_roles'),
        ('core', '0010_documentidentity_site_unless_booking'),
        ('inbound', '0010_duplicatearrivalacknowledgement_and_more'),
        ('masters', '0021_season_historical_unknown_and_more'),
        ('outbound', '0027_countsnapshot_lot_countsnapshot_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('reported_at', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('lines', models.JSONField()),
                ('reason_code', models.CharField(max_length=60)),
                ('evidence_id', models.UUIDField(blank=True, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('disposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inbound.disposition')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.documentidentity')),
                ('release_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.documentidentity')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'state'], name='outbound_da_site_id_1a27bd_idx'), models.Index(fields=['state', 'reported_at'], name='outbound_da_state_6e6fbe_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_damagereport_quantity'), models.CheckConstraint(condition=models.Q(models.Q(('disposition__isnull', True), ('movement__isnull', False)), models.Q(('disposition__isnull', False), ('movement__isnull', True)), _connector='OR'), name='ck_damagereport_one_source')],
            },
        ),
    ]
