# Generated by Django 5.1.15 on 2026-09-22 00:28

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_store_roles'),
        ('core', '0010_documentidentity_site_unless_booking'),
        ('inbound', '0010_duplicatearrivalacknowledgement_and_more'),
        ('masters', '0021_season_historical_unknown_and_more'),
        ('outbound', '0028_damagereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('sequence_no', models.IntegerField()),
                ('dispatched_at', models.DateTimeField()),
                ('transport', models.JSONField(default=dict)),
                ('lines', models.JSONField()),
                ('state', models.CharField(choices=[('in_transit', 'In Transit'), ('counted', 'Counted'), ('accepted', 'Accepted'), ('returned_to_source', 'Returned To Source')], default='in_transit', max_length=20)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('count', models.JSONField(blank=True, default=dict)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('requested_at', models.DateTimeField()),
                ('lines', models.JSONField()),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('state', models.CharField(choices=[('open', 'Open'), ('drafted', 'Drafted'), ('closed', 'Closed')], default='open', max_length=8)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='damagereport',
            name='ck_damagereport_one_source',
        ),
        migrations.AddField(
            model_name='goodstransfer',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('dispatching', 'Dispatching'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=12),
        ),
        migrations.AlterField(
            model_name='transferevent',
            name='kind',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('dispatch', 'Dispatch'), ('arrival', 'Arrival'), ('check', 'Check'), ('accept', 'Accept'), ('putaway', 'Putaway'), ('returned', 'Returned'), ('completed', 'Completed'), ('eway_added', 'Eway Added'), ('eway_verified', 'Eway Verified'), ('cancelled', 'Cancelled')], max_length=14),
        ),
        migrations.AddIndex(
            model_name='goodstransfer',
            index=models.Index(fields=['state'], name='outbound_go_state_20983b_idx'),
        ),
        migrations.AddField(
            model_name='transferdispatch',
            name='counted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='transferdispatch',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='transferdispatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='transferdispatch',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='outbound.goodstransfer'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='dispatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='outbound.transferdispatch'),
        ),
        migrations.AddConstraint(
            model_name='damagereport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dispatch__isnull', True), ('disposition__isnull', True), ('movement__isnull', False)), models.Q(('dispatch__isnull', True), ('disposition__isnull', False), ('movement__isnull', True)), models.Q(('dispatch__isnull', False), ('disposition__isnull', True), ('movement__isnull', True)), _connector='OR'), name='ck_damagereport_one_source'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='destination_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='source_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='outbound.goodstransfer'),
        ),
        migrations.AddIndex(
            model_name='transferdispatch',
            index=models.Index(fields=['transfer', 'state'], name='outbound_tr_transfe_01b29c_idx'),
        ),
        migrations.AddIndex(
            model_name='transferdispatch',
            index=models.Index(fields=['state'], name='outbound_tr_state_f6c63e_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferdispatch',
            constraint=models.UniqueConstraint(fields=('transfer', 'sequence_no'), name='uq_transferdispatch_sequence'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['source_site', 'state'], name='outbound_tr_source__6e1750_idx'),
        ),
        migrations.AddIndex(
            model_name='transferrequest',
            index=models.Index(fields=['destination_site', 'state'], name='outbound_tr_destina_6b1053_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferrequest',
            constraint=models.CheckConstraint(condition=models.Q(('source_site', models.F('destination_site')), _negated=True), name='ck_transferrequest_sites'),
        ),
    ]
