# Generated by Django 5.1.15 on 2026-09-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0029_transferdispatch_transferrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferevent',
            name='kind',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('dispatch', 'Dispatch'), ('arrival', 'Arrival'), ('check', 'Check'), ('accept', 'Accept'), ('putaway', 'Putaway'), ('returned', 'Returned'), ('completed', 'Completed'), ('eway_added', 'Eway Added'), ('eway_verified', 'Eway Verified'), ('cancelled', 'Cancelled'), ('damage_rejected', 'Damage Rejected')], max_length=20),
        ),
    ]
