# Generated by Django 5.1.15 on 2026-09-24 17:18

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_store_roles'),
        ('core', '0011_alter_documentidentity_purpose'),
        ('masters', '0022_crosswalk_attribute_kinds'),
        ('outbound', '0030_transferevent_damage_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodstransfer',
            name='eway_state',
        ),
        migrations.AddField(
            model_name='transferdispatch',
            name='arrival_recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='transferdispatch',
            name='eway_at_dispatch',
            field=models.CharField(blank=True, choices=[('present', 'present'), ('not_present', 'not_present')], max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='DispatchPreparation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('state', models.CharField(choices=[('open', 'Open'), ('dispatched', 'Dispatched'), ('invalidated', 'Invalidated')], default='open', max_length=12)),
                ('revision', models.IntegerField(default=1)),
                ('content_hash', models.CharField(max_length=64)),
                ('opened_at', models.DateTimeField()),
                ('last_activity_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_reason', models.CharField(blank=True, max_length=40, null=True)),
                ('dispatch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preparation', to='outbound.transferdispatch')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.officialversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparations', to='outbound.goodstransfer')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('scan_key', models.UUIDField()),
                ('line_key', models.UUIDField()),
                ('origin_id', models.UUIDField(blank=True, null=True)),
                ('qty', models.IntegerField()),
                ('alias_value', models.CharField(max_length=128)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='outbound.dispatchpreparation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='dispatchpreparation',
            index=models.Index(fields=['transfer', 'state'], name='outbound_di_transfe_126d45_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispatchpreparation',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'open')), fields=('transfer',), name='uq_dispatchpreparation_one_open'),
        ),
        migrations.AddIndex(
            model_name='dispatchscan',
            index=models.Index(fields=['preparation', 'recorded_at'], name='outbound_di_prepara_2da2c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispatchscan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='outbound_dispatchscan_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='dispatchscan',
            constraint=models.UniqueConstraint(fields=('preparation', 'scan_key'), name='uq_dispatchscan_key'),
        ),
        migrations.AddConstraint(
            model_name='dispatchscan',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='ck_dispatchscan_qty'),
        ),
    ]
