# Generated by Django 5.1.15 on 2026-09-24 19:03

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


def _backfill_returned_qty(apps, schema_editor):
    """An OPS-06 return brought the whole shipment back, so all of it is returned."""
    dispatch = apps.get_model("outbound", "TransferDispatch")
    for row in dispatch.objects.filter(state="returned_to_source"):
        row.returned_qty = sum(int(line["qty"]) for line in row.lines)
        row.save(update_fields=["returned_qty"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_store_roles'),
        ('core', '0011_alter_documentidentity_purpose'),
        ('masters', '0022_crosswalk_attribute_kinds'),
        ('outbound', '0031_dispatch_preparation_eway_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdispatch',
            name='returned_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(_backfill_returned_qty, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='transferdispatch',
            name='state',
            field=models.CharField(choices=[('in_transit', 'In Transit'), ('counted', 'Counted'), ('accepted', 'Accepted'), ('partly_returned', 'Partly Returned'), ('returned_to_source', 'Returned To Source')], default='in_transit', max_length=20),
        ),
        migrations.CreateModel(
            name='TransferReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('receipt_key', models.UUIDField()),
                ('reason', models.CharField(max_length=500)),
                ('evidence_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('lines', models.JSONField()),
                ('quantity', models.IntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='outbound.transferdispatch')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['dispatch', 'recorded_at'], name='outbound_tr_dispatc_a38d99_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='outbound_transferreturn_one_actor'), models.UniqueConstraint(fields=('dispatch', 'receipt_key'), name='uq_transferreturn_key'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ck_transferreturn_qty')],
            },
        ),
    ]
