# Generated by Django 5.1.15 on 2026-09-25 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_store_roles'),
        ('core', '0011_alter_documentidentity_purpose'),
        ('masters', '0022_crosswalk_attribute_kinds'),
        ('outbound', '0032_transfer_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='gapresolution',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gapresolution',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='gapresolution',
            name='decision_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gapresolution',
            name='dispatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gap_resolutions', to='outbound.transferdispatch'),
        ),
        migrations.AddField(
            model_name='gapresolution',
            name='proposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gapresolution',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='gapresolution',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gapresolution',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='transferevent',
            name='kind',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('dispatch', 'Dispatch'), ('arrival', 'Arrival'), ('check', 'Check'), ('accept', 'Accept'), ('putaway', 'Putaway'), ('returned', 'Returned'), ('completed', 'Completed'), ('eway_added', 'Eway Added'), ('eway_verified', 'Eway Verified'), ('cancelled', 'Cancelled'), ('damage_rejected', 'Damage Rejected'), ('shortage_proposed', 'Shortage Proposed'), ('shortage_resolved', 'Shortage Resolved'), ('shortage_rejected', 'Shortage Rejected')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='gapresolution',
            index=models.Index(fields=['dispatch', 'state'], name='outbound_ga_dispatc_da5f0c_idx'),
        ),
    ]
