# Generated by Django 5.1.15 on 2026-09-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0033_gap_resolution_shortage'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstransfer',
            name='custody',
            field=models.CharField(choices=[('ordinary', 'Ordinary'), ('quarantine', 'Quarantine')], default='ordinary', max_length=12),
        ),
    ]
