# Generated by Django 5.1.15 on 2026-09-25 20:41

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_merge_store_roles"),
        ("core", "0011_alter_documentidentity_purpose"),
        ("masters", "0022_crosswalk_attribute_kinds"),
        ("outbound", "0035_transfer_custody_pre_pt"),
        ("stockledger", "0018_remove_stockledgerentry_pt_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsmovement",
            name="rtv_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("initiated", "initiated"),
                    ("completed", "completed"),
                    ("closed_partially_returned", "closed_partially_returned"),
                    ("cancelled", "cancelled"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RtvEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "service_code",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("event_at", models.DateTimeField()),
                (
                    "recorded_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "previous_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("row_hash", models.CharField(max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[("pickup", "Pickup"), ("withdrawal", "Withdrawal")],
                        max_length=12,
                    ),
                ),
                ("sequence_no", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("lines", models.JSONField()),
                ("details", models.JSONField()),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.humanidentity",
                    ),
                ),
                (
                    "command_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.commandkey",
                    ),
                ),
                (
                    "journal_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="stockledger.journalbatch",
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rtv_events",
                        to="outbound.goodsmovement",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["movement", "recorded_at"],
                        name="outbound_rt_movemen_eb53ba_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("actor__isnull", False), ("service_code__isnull", True)),
                            models.Q(("actor__isnull", True), ("service_code__isnull", False)),
                            _connector="OR",
                        ),
                        name="outbound_rtvevent_one_actor",
                    ),
                    models.UniqueConstraint(
                        fields=("movement", "sequence_no"), name="uq_rtvevent_sequence"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)), name="ck_rtvevent_qty"
                    ),
                ],
            },
        ),
    ]
