# Generated by Django 5.1.15 on 2026-09-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outbound", "0036_rtv_pickups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="damagereport",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("rejected", "Rejected"),
                    ("closed", "Closed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
