# Generated by Django 5.1.15 on 2026-09-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outbound", "0037_damage_report_closed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsmovement",
            name="kind",
            field=models.CharField(
                choices=[
                    ("bin_move", "Bin Move"),
                    ("hold", "Hold"),
                    ("release", "Release"),
                    ("adjustment_up", "Adjustment Up"),
                    ("adjustment_down", "Adjustment Down"),
                    ("writeoff", "Writeoff"),
                    ("shrinkage", "Shrinkage"),
                    ("rtv", "Rtv"),
                    ("transit_shortage", "Transit Shortage"),
                    ("rtv_cancel", "Rtv Cancel"),
                    ("disposal", "Disposal"),
                ],
                max_length=20,
            ),
        ),
    ]
