# Generated by Django 5.1.15 on 2026-09-26 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_merge_store_roles"),
        ("core", "0011_alter_documentidentity_purpose"),
        ("masters", "0022_crosswalk_attribute_kinds"),
        ("outbound", "0038_disposal_movement_kind"),
        ("stockledger", "0020_disposal_posting_kind"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rtvevent",
            name="ck_rtvevent_qty",
        ),
        migrations.AddField(
            model_name="rtvevent",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipment_facts",
                to="outbound.rtvevent",
            ),
        ),
        migrations.AlterField(
            model_name="rtvevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("pickup", "Pickup"),
                    ("withdrawal", "Withdrawal"),
                    ("shipment", "Shipment"),
                    ("acknowledgement", "Acknowledgement"),
                    ("source_return", "Source Return"),
                    ("putaway", "Putaway"),
                    ("eway_attached", "Eway Attached"),
                    ("eway_verified", "Eway Verified"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="rtvevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity__gt", 0),
                    models.Q(
                        (
                            "kind__in",
                            ["acknowledgement", "eway_attached", "eway_verified"],
                        ),
                        ("quantity", 0),
                    ),
                    _connector="OR",
                ),
                name="ck_rtvevent_qty",
            ),
        ),
        migrations.AddConstraint(
            model_name="rtvevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "kind__in",
                            [
                                "acknowledgement",
                                "source_return",
                                "putaway",
                                "eway_attached",
                                "eway_verified",
                            ],
                        ),
                        ("shipment__isnull", False),
                    ),
                    models.Q(
                        ("kind__in", ["pickup", "withdrawal", "shipment"]),
                        ("shipment__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_rtvevent_shipment_link",
            ),
        ),
    ]
