# Generated by Django 5.1.15 on 2026-09-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_merge_store_roles"),
        ("core", "0011_alter_documentidentity_purpose"),
        ("masters", "0022_crosswalk_attribute_kinds"),
        ("outbound", "0039_rtv_shipments"),
        ("stockledger", "0020_disposal_posting_kind"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rtvevent",
            name="ck_rtvevent_shipment_link",
        ),
        migrations.AlterField(
            model_name="rtvevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("pickup", "Pickup"),
                    ("withdrawal", "Withdrawal"),
                    ("shipment", "Shipment"),
                    ("acknowledgement", "Acknowledgement"),
                    ("source_return", "Source Return"),
                    ("putaway", "Putaway"),
                    ("eway_attached", "Eway Attached"),
                    ("eway_verified", "Eway Verified"),
                    ("shortfall_proposal", "Shortfall Proposal"),
                    ("shortfall_closure", "Shortfall Closure"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="rtvevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "kind__in",
                            [
                                "acknowledgement",
                                "source_return",
                                "putaway",
                                "eway_attached",
                                "eway_verified",
                                "shortfall_proposal",
                                "shortfall_closure",
                            ],
                        ),
                        ("shipment__isnull", False),
                    ),
                    models.Q(
                        ("kind__in", ["pickup", "withdrawal", "shipment"]),
                        ("shipment__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_rtvevent_shipment_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="rtvevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "shortfall_closure")),
                fields=("shipment",),
                name="uq_rtvevent_one_shortfall_closure",
            ),
        ),
    ]
