# Generated by Django 5.1.15 on 2026-09-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outbound", "0040_rtv_shortfall_closure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gapresolution",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="transferevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("dispatch", "Dispatch"),
                    ("arrival", "Arrival"),
                    ("check", "Check"),
                    ("accept", "Accept"),
                    ("putaway", "Putaway"),
                    ("returned", "Returned"),
                    ("completed", "Completed"),
                    ("eway_added", "Eway Added"),
                    ("eway_verified", "Eway Verified"),
                    ("cancelled", "Cancelled"),
                    ("damage_rejected", "Damage Rejected"),
                    ("shortage_proposed", "Shortage Proposed"),
                    ("shortage_resolved", "Shortage Resolved"),
                    ("shortage_rejected", "Shortage Rejected"),
                    ("corrective_proposed", "Corrective Proposed"),
                    ("corrective_matched", "Corrective Matched"),
                    ("corrective_withdrawn", "Corrective Withdrawn"),
                ],
                max_length=20,
            ),
        ),
    ]
