# Generated by Django 5.1.15 on 2026-09-26 03:48

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_merge_store_roles"),
        ("core", "0011_alter_documentidentity_purpose"),
        ("masters", "0022_crosswalk_attribute_kinds"),
        ("outbound", "0041_transfer_excess_corrective"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountAffirmation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "service_code",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("event_at", models.DateTimeField()),
                (
                    "recorded_at",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("row_hash", models.CharField(max_length=64)),
                ("scope_hash", models.CharField(max_length=64)),
                ("observation_hash", models.CharField(max_length=64)),
                ("observation_revision", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="goodscountpass",
            name="last_activity_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goodscountpass",
            name="reason_code",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="goodscountpass",
            name="stale_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goodscountpass",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="goodscountpass",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "open")),
                fields=("stocktake", "counter"),
                name="uq_countpass_one_open",
            ),
        ),
        migrations.AddConstraint(
            model_name="goodsstocktake",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ("requested", "open", "review"))),
                fields=("site",),
                name="uq_stocktake_one_unfinished",
            ),
        ),
        migrations.AddField(
            model_name="countaffirmation",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounts.humanidentity",
            ),
        ),
        migrations.AddField(
            model_name="countaffirmation",
            name="command_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.commandkey",
            ),
        ),
        migrations.AddField(
            model_name="countaffirmation",
            name="count_pass",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="affirmations",
                to="outbound.goodscountpass",
            ),
        ),
        migrations.AddField(
            model_name="countaffirmation",
            name="counter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounts.humanidentity",
            ),
        ),
        migrations.AddField(
            model_name="countaffirmation",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="masters.tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="countaffirmation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("actor__isnull", False), ("service_code__isnull", True)),
                    models.Q(("actor__isnull", True), ("service_code__isnull", False)),
                    _connector="OR",
                ),
                name="outbound_countaffirmation_one_actor",
            ),
        ),
        migrations.AddConstraint(
            model_name="countaffirmation",
            constraint=models.UniqueConstraint(
                fields=("count_pass",), name="uq_countaffirmation_pass"
            ),
        ),
    ]
