# Generated by Django 5.1.15 on 2026-09-27 22:10

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masters", "0028_season_ended_on"),
        ("outbound", "0042_count_capture"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "every",
                    models.CharField(
                        choices=[
                            ("week", "Every week"),
                            ("month", "Every month"),
                            ("quarter", "Every 3 months"),
                        ],
                        max_length=8,
                    ),
                ),
                ("first_due_on", models.DateField()),
                ("judged_from", models.DateField()),
                ("active", models.BooleanField(default=True)),
                ("revision", models.IntegerField(default=1)),
                ("updated_at", models.DateTimeField()),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.brand",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.store",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["site", "active"], name="outbound_co_site_id_d5442e_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("tenant", "site", "brand"),
                        name="uq_countschedule_active_scope",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
    ]
