# Generated by Django 5.1.15 on 2026-09-28 08:11

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_store_roles'),
        ('masters', '0029_customer_corrected_at'),
        ('outbound', '0043_count_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeBalanceSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('lines', models.JSONField()),
                ('pieces', models.PositiveIntegerField()),
                ('mrp_paise', models.BigIntegerField()),
                ('mrp_unknown_pieces', models.PositiveIntegerField(default=0)),
                ('rule', models.CharField(max_length=40)),
                ('rule_settings', models.JSONField(default=dict)),
                ('made_at', models.DateTimeField()),
                ('checked_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('pending', 'Waiting for a decision'), ('approved', 'Approved: a transfer request was raised'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn by the daily check')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('withdrawn_reason', models.CharField(blank=True, choices=[('replaced', 'The daily check found a different transfer between these stores'), ('not_needed', 'The sizes are no longer missing, or no longer spare there'), ('not_checked', 'Switched off, or no longer checked, at one of the two stores')], max_length=12)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('destination_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('source_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
                ('transfer_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='outbound.transferrequest')),
            ],
            options={
                'ordering': ['made_at'],
                'indexes': [models.Index(fields=['destination_site', 'state'], name='outbound_si_destina_f2709d_idx'), models.Index(fields=['source_site', 'state'], name='outbound_si_source__40fcfa_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('tenant', 'destination_site', 'source_site'), name='uq_sizebalance_pending_pair'), models.CheckConstraint(condition=models.Q(('source_site', models.F('destination_site')), _negated=True), name='ck_sizebalance_two_stores'), models.CheckConstraint(condition=models.Q(models.Q(('state', 'approved'), _negated=True), ('transfer_request__isnull', False), _connector='OR'), name='ck_sizebalance_approved_raises'), models.CheckConstraint(condition=models.Q(models.Q(('state', 'rejected'), _negated=True), models.Q(('reason', ''), _negated=True), _connector='OR'), name='ck_sizebalance_rejected_says_why'), models.CheckConstraint(condition=models.Q(models.Q(('state', 'withdrawn'), _negated=True), models.Q(('withdrawn_reason', ''), _negated=True), _connector='OR'), name='ck_sizebalance_withdrawn_says_why')],
            },
        ),
    ]
