# Generated by Django 5.1.15 on 2026-09-28 08:12

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_merge_store_roles"),
        ("masters", "0029_customer_corrected_at"),
        ("outbound", "0043_count_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("delivery_challan", "Delivery challan"),
                            ("tax_invoice", "Tax invoice"),
                        ],
                        max_length=16,
                    ),
                ),
                ("number", models.CharField(max_length=16)),
                ("issued_on", models.DateField()),
                ("parties", models.JSONField()),
                (
                    "tax_kind",
                    models.CharField(
                        choices=[
                            ("none", "No tax"),
                            ("cgst_sgst", "CGST and SGST"),
                            ("igst", "IGST"),
                        ],
                        max_length=10,
                    ),
                ),
                ("tax_version", models.PositiveIntegerField(blank=True, null=True)),
                ("lines", models.JSONField()),
                ("taxable_paise", models.BigIntegerField(blank=True, null=True)),
                ("tax_paise", models.BigIntegerField(default=0)),
                ("total_paise", models.BigIntegerField(blank=True, null=True)),
                (
                    "destination_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.store",
                    ),
                ),
                (
                    "dispatch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document",
                        to="outbound.transferdispatch",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.humanidentity",
                    ),
                ),
                (
                    "source_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.store",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "number"), name="uq_transferdocument_number"
                    )
                ],
            },
        ),
    ]
