# Generated by Django 5.1.15 on 2026-09-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0044_size_balancing'),
        ('outbound', '0044_transfer_document'),
    ]

    operations = [
    ]
