# Generated by Django 5.2.17 on 2026-09-30 07:33

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_installationregistration'),
        ('approvals', '0016_so03_authority_pin'),
        ('core', '0012_customer_reservation'),
        ('masters', '0033_first_store_controls'),
        ('outbound', '0046_so03_brand_identity'),
        ('ptmapper', '0019_sohimport_sohimportbatch_sohimportreview_and_more'),
        ('stockledger', '0024_stockledgerentry_brand_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='SohReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('revision', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(default='frozen', max_length=20)),
                ('frozen_at', models.DateTimeField()),
                ('content_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('approval_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='approvals.approvalrequest')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.documentidentity')),
                ('journal_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stockledger.journalbatch')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('official_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.officialversion')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('source_import', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reconciliation', to='ptmapper.sohimport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SohReconciliationEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('revision', models.PositiveIntegerField()),
                ('outcome', models.CharField(max_length=20)),
                ('content_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='outbound.sohreconciliation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='sohreconciliation',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['frozen', 'submitted'])), fields=('site',), name='uq_soh_count_open_site'),
        ),
        migrations.AddConstraint(
            model_name='sohreconciliationevidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='outbound_sohreconciliationevidence_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='sohreconciliationevidence',
            constraint=models.UniqueConstraint(fields=('reconciliation', 'revision'), name='uq_soh_count_evidence_revision'),
        ),
    ]
