# Generated by Django 5.2.17 on 2026-09-30 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0033_first_store_controls'),
        ('outbound', '0047_soh_reconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsstocktake',
            name='till_pause_evidence',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='goodsstocktake',
            name='non_trading_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.sitecapabilityevent'),
        ),
    ]
