# Generated by Django 5.1.15 on 2026-08-01 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_address', models.EmailField(help_text='The Google address that actually consented, read back from Google rather than typed. A person may sign into KDPS as one name and hold mail at another, and the address shown must be the one whose mail is on screen.', max_length=254)),
                ('refresh_token_enc', models.TextField(blank=True, default='', help_text="Fernet ciphertext (mail.crypto). Never read this column directly - use the refresh_token property, which is also the only place that knows an unreadable value means 'reconnect'.")),
                ('access_token_enc', models.TextField(blank=True, default='')),
                ('access_expires_at', models.DateTimeField(blank=True, help_text='When the short-lived access token dies. Refreshed a minute early (see google.py) so a call never starts on a token that expires mid-flight.', null=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('needs_reconnect', 'Needs reconnecting'), ('disconnected', 'Disconnected')], default='connected', max_length=20)),
                ('history_id', models.CharField(blank=True, default='', help_text="Gmail's watermark. Sync asks 'what changed since this?' rather than re-listing the mailbox, which is what keeps a refresh cheap enough to run every time the popup opens. Blank means the next sync is a first backfill.", max_length=40)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.CharField(blank=True, default='', help_text='Why the last pull failed, shown to the person as a quiet line. An inbox that silently stops updating is worse than one that says it could not reach Google.', max_length=300)),
                ('user', models.OneToOneField(help_text='The KDPS login this mailbox belongs to. CASCADE on purpose - deleting a person must take their stored mail credentials with it.', on_delete=django.db.models.deletion.CASCADE, related_name='mail_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mail_account',
            },
        ),
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_id', models.CharField(help_text="Gmail's own message id.", max_length=64)),
                ('thread_id', models.CharField(db_index=True, max_length=64)),
                ('rfc_message_id', models.CharField(blank=True, default='', help_text="The RFC 5322 Message-ID header - a different thing from google_id, and the only one the rest of the world threads on. A reply that puts Gmail's own id in In-Reply-To lands outside the conversation in the recipient's client.", max_length=500)),
                ('rfc_references', models.TextField(blank=True, default='', help_text="The References header as it arrived. A reply appends the parent's Message-ID to this chain rather than starting a new one, which is what keeps a long vendor thread from splitting in two.")),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('from_name', models.CharField(blank=True, default='', max_length=200)),
                ('from_email', models.CharField(blank=True, default='', max_length=320)),
                ('to_emails', models.TextField(blank=True, default='', help_text='Comma-joined, as Gmail returns them.')),
                ('cc_emails', models.TextField(blank=True, default='')),
                ('snippet', models.CharField(blank=True, default='', max_length=500)),
                ('body_html', models.TextField(blank=True, default='')),
                ('body_text', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(db_index=True)),
                ('is_unread', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('label_ids', models.JSONField(blank=True, default=list)),
                ('account', models.ForeignKey(help_text="The only route to a message. Every query in views.py starts from request.user's account, never from a message id - an id-first lookup is how one person ends up reading another's mail.", on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mail.mailaccount')),
            ],
            options={
                'db_table': 'mail_message',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_attachment_id', models.TextField(help_text="Gmail's handle for the bytes. Long - these are not short ids.")),
                ('filename', models.CharField(max_length=300)),
                ('mime_type', models.CharField(blank=True, default='', max_length=200)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.mailmessage')),
            ],
            options={
                'db_table': 'mail_attachment',
                'ordering': ['filename'],
            },
        ),
        migrations.CreateModel(
            name='MailOAuthFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(help_text='The random value handed to Google as ?state=. Unique and single-use: a state that has already come back cannot come back again.', max_length=64, unique=True)),
                ('handoff', models.CharField(blank=True, db_index=True, default='', help_text='Minted when Google returns, and the only thing the browser is told. Blank means this flow has not been back from Google yet, which is also what makes the claim a one-shot.', max_length=64)),
                ('code_enc', models.TextField(blank=True, default='', help_text="Fernet ciphertext of Google's authorization code (mail.crypto).")),
                ('user', models.ForeignKey(help_text='Who pressed Connect. The mailbox may only ever attach to this person, and only when this person is the one finishing.', on_delete=django.db.models.deletion.CASCADE, related_name='mail_oauth_flows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mail_oauth_flow',
            },
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['account', '-sent_at'], name='ix_mail_msg_acct_sent'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['account', 'is_unread'], name='ix_mail_msg_acct_unread'),
        ),
        migrations.AddConstraint(
            model_name='mailmessage',
            constraint=models.UniqueConstraint(fields=('account', 'google_id'), name='uq_mail_message_account_google'),
        ),
    ]
