# Generated by Django 5.1.15 on 2026-07-24 05:50

import core.money
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('masters', '0004_seed_default_category_margin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(help_text="Machine code of the document family, e.g. 'writeoff'. The client maps it to a route; the server never branches on it.", max_length=32)),
                ('kind_label', models.CharField(max_length=64)),
                ('title', models.CharField(help_text='Snapshot one-liner shown in the inbox (store, lines, pieces).', max_length=240)),
                ('object_id', models.BigIntegerField()),
                ('value_paise', core.money.MoneyField(default=0, help_text='Value at stake, snapshotted — the input to value-banded approval.')),
                ('approver_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, help_text='Role codes that may decide this one. Data, not code (Rule 12).', size=None)),
                ('status', models.CharField(choices=[('pending', 'Waiting for approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='', help_text='Required on reject; free for approve.')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals_decided', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals_requested', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, help_text='Scopes the inbox for store-scoped users (ADR-0003).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='masters.store')),
            ],
            options={
                'db_table': 'approvals_approval',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='approval_status_recent_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='uq_approval_subject'), models.CheckConstraint(condition=models.Q(('decided_by', models.F('requested_by')), _negated=True), name='approval_maker_is_not_checker'), models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('decided_by__isnull', True), ('status', 'pending')), models.Q(('decided_at__isnull', False), ('decided_by__isnull', False), ('status__in', ['approved', 'rejected'])), _connector='OR'), name='approval_decision_is_complete'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), models.Q(('reason', ''), _negated=True), _connector='OR'), name='approval_reject_has_reason')],
            },
        ),
    ]
