# Generated by Django 5.1.15 on 2026-07-24 07:25

import core.money
import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('masters', '0004_seed_default_category_margin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(help_text="Document family this governs, e.g. 'adjustment'.", max_length=32, unique=True)),
                ('tolerance_paise', core.money.MoneyField(default=0, help_text='Value at stake at or below which no second person is asked — the document posts and the decision is logged. 0 disables the tolerance: every document of this kind needs a checker.')),
                ('band_paise', core.money.MoneyField(default=0, help_text='Up to this value the in-charge roles may approve; above it, only the escalated roles. 0 sends every one straight to HO.')),
                ('band_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, help_text='Role codes that may approve within the band (in-charge + HO).', size=None)),
                ('escalated_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, help_text='Role codes that may approve above the band (HO only).', size=None)),
            ],
            options={
                'verbose_name_plural': 'approval policies',
                'db_table': 'approvals_policy',
                'ordering': ['kind'],
            },
        ),
        migrations.AlterModelOptions(
            name='approval',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.RemoveConstraint(
            model_name='approval',
            name='uq_approval_subject',
        ),
        migrations.RemoveConstraint(
            model_name='approval',
            name='approval_decision_is_complete',
        ),
        migrations.AlterField(
            model_name='approval',
            name='reason',
            field=models.TextField(blank=True, default='', help_text="Required on reject; free for approve; the policy note on 'not_required'."),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('pending', 'Waiting for approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('not_required', 'No second person needed')], default='pending', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='approval',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('content_type', 'object_id'), name='uq_approval_subject_pending'),
        ),
        migrations.AddConstraint(
            model_name='approval',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', True), ('decided_by__isnull', True), ('status__in', ['pending', 'not_required'])), models.Q(('decided_at__isnull', False), ('decided_by__isnull', False), ('status__in', ['approved', 'rejected'])), _connector='OR'), name='approval_decision_is_complete'),
        ),
    ]
