# Generated by Django 5.1.15 on 2026-07-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0005_seed_stock_request_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='brand',
            field=models.CharField(blank=True, default='', help_text='Scopes the inbox for brand-scoped users — a brand manager, whose boundary is brands and not stores (ADR-0003). Snapshotted as the brand *name*, like every other brand on a ledger row, so this table still imports no business model. Blank means the decision is not about one brand, and a brand-scoped user never sees it (#75).', max_length=120),
        ),
    ]
