# Generated by Django 5.1.15 on 2026-07-30 05:33

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0006_approval_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(help_text="Document family this routes, e.g. 'stock_request'. Matches Approval.kind.", max_length=32, unique=True)),
                ('steps', models.JSONField(default=list, help_text='Ordered steps: [{order, roles | roles_from_policy, label, later_step_may_short_circuit}].')),
            ],
            options={
                'db_table': 'approvals_approvalroute',
                'ordering': ['kind'],
            },
        ),
        migrations.AddField(
            model_name='approval',
            name='current_step',
            field=models.IntegerField(default=0, help_text='Zero-based position in the route. 0 on an unrouted approval, where it means nothing; on a routed one it is the step now waiting, and once approved it sits past the last step.'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='approver_roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, help_text="Role codes that may decide this one *right now*. Data, not code (Rule 12). On a routed approval this is the current step's roles plus any later step allowed to close it, rewritten as the chain advances — so the inbox query never has to know routes exist.", size=None),
        ),
        migrations.AddField(
            model_name='approval',
            name='route',
            field=models.ForeignKey(blank=True, help_text='The chain this request walks. Null is the ordinary single-step approval every other family uses.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='approvals.approvalroute'),
        ),
        migrations.CreateModel(
            name='ApprovalStepDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_order', models.IntegerField(help_text='Zero-based position in the route at the time.')),
                ('step_label', models.CharField(blank=True, default='', help_text="The step's name, snapshotted — the route is editable data (Rule 6).", max_length=64)),
                ('decided_at', models.DateTimeField()),
                ('short_circuited', models.BooleanField(default=False, help_text='Closed from a later step rather than cleared by its own approver.')),
                ('note', models.TextField(blank=True, default='')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_decisions', to='approvals.approval')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps_decided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approvals_step_decision',
                'ordering': ['approval_id', 'step_order'],
                'constraints': [models.UniqueConstraint(fields=('approval', 'step_order'), name='uq_approval_step_once')],
            },
        ),
    ]
