# Generated by Django 5.1.15 on 2026-09-13 14:50

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_authenticationfailure_humanidentity_rolegrant_and_more'),
        ('approvals', '0008_seed_stock_request_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('outcome', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('refused', 'Refused'), ('superseded', 'Superseded')], max_length=12)),
                ('reviewed_hash', models.CharField(max_length=64)),
                ('reason_code', models.CharField(blank=True, max_length=60, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('subject_kind', models.CharField(choices=[('document', 'Document'), ('configuration', 'Configuration'), ('manifest', 'Manifest'), ('opening_variance', 'Opening Variance'), ('disposition', 'Disposition'), ('count', 'Count'), ('master_proposal', 'Master Proposal')], max_length=20)),
                ('subject_key', models.CharField(max_length=100)),
                ('revision', models.IntegerField()),
                ('reviewed_hash', models.CharField(max_length=64)),
                ('requested_action', models.CharField(max_length=60)),
                ('required_roles', models.JSONField(default=list)),
                ('require_distinct', models.BooleanField(default=True)),
                ('scope', models.JSONField()),
                ('reconciliation', models.JSONField(blank=True, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='pending', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(default='', max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='ActionDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('subject_kind', models.CharField(choices=[('opening_variance', 'Opening Variance')], max_length=20)),
                ('subject_key', models.CharField(max_length=100)),
                ('revision', models.IntegerField(default=1)),
                ('payload', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
            ],
        ),
    ]
