# Generated by Django 5.1.15 on 2026-09-13 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_authenticationfailure_humanidentity_rolegrant_and_more'),
        ('approvals', '0009_approvaldecision_approvalrequest_actiondraft'),
        ('core', '0008_auditevent_chainhead_commandattempt_commandkey_and_more'),
        ('masters', '0011_configdraft_configversion_sitecapabilityevent_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiondraft',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='policy_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.configversion'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='approvaldecision',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='approvals.approvalrequest'),
        ),
        migrations.AddIndex(
            model_name='actiondraft',
            index=models.Index(fields=['maker', 'created_at'], name='approvals_a_maker_i_9105ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='actiondraft',
            constraint=models.UniqueConstraint(fields=('tenant', 'subject_kind', 'subject_key', 'revision'), name='uq_actiondraft_revision'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['state', 'created_at'], name='approvals_a_state_3a2e59_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('tenant', 'subject_kind', 'subject_key', 'requested_action'), name='uq_approvalrequest_pending'),
        ),
        migrations.AddIndex(
            model_name='approvaldecision',
            index=models.Index(fields=['request', 'recorded_at'], name='approvals_a_request_ee5869_idx'),
        ),
        migrations.AddConstraint(
            model_name='approvaldecision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='approvals_approvaldecision_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='approvaldecision',
            constraint=models.UniqueConstraint(condition=models.Q(('outcome__in', ['approved', 'rejected'])), fields=('request',), name='uq_approvaldecision_once'),
        ),
    ]
