# Generated by Django 5.1.15 on 2026-09-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0010_actiondraft_tenant_approvaldecision_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='policy_basis',
            field=models.JSONField(default=dict),
        ),
    ]
