# Generated by Django 5.1.15 on 2026-09-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approvals", "0013_owner_and_brand_manager_beside_ops_head"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalrequest",
            name="subject_kind",
            field=models.CharField(
                choices=[
                    ("document", "Document"),
                    ("configuration", "Configuration"),
                    ("manifest", "Manifest"),
                    ("opening_variance", "Opening Variance"),
                    ("disposition", "Disposition"),
                    ("count", "Count"),
                    ("master_proposal", "Master Proposal"),
                    ("rtv_shortfall", "Rtv Shortfall"),
                ],
                max_length=20,
            ),
        ),
    ]
