# Generated by Django 5.2.17 on 2026-09-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0016_so03_authority_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaldecision',
            name='outcome',
            field=models.CharField(choices=[('step_approved', 'Step Approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refused', 'Refused'), ('superseded', 'Superseded')], max_length=16),
        ),
    ]
