# Generated by Django 5.2.17 on 2026-09-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0017_transfer_route_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='subject_kind',
            field=models.CharField(choices=[('document', 'Document'), ('transfer', 'Transfer'), ('configuration', 'Configuration'), ('manifest', 'Manifest'), ('opening_variance', 'Opening Variance'), ('disposition', 'Disposition'), ('count', 'Count'), ('master_proposal', 'Master Proposal'), ('rtv_shortfall', 'Rtv Shortfall')], max_length=20),
        ),
    ]
