# Generated by Django 5.1.15 on 2026-07-30 08:40

import core.money
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_external_number_acceptance'),
        ('masters', '0006_storetarget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('idempotency_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('docstatus', models.IntegerField(choices=[(0, 'draft'), (1, 'submitted'), (2, 'cancelled')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fy', models.CharField(max_length=7)),
                ('till_seq', models.IntegerField(help_text='The number the till assigned, before syncing.')),
                ('origin', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('paper', 'Re-entered from a paper bill')], default='offline', max_length=8)),
                ('billed_at', models.DateTimeField(help_text="The till's clock at Save & Print.")),
                ('customer_name', models.CharField(blank=True, default='', max_length=120)),
                ('customer_mobile', models.CharField(blank=True, db_index=True, default='', max_length=15)),
                ('buyer_gstin', models.CharField(blank=True, default='', help_text='Present = a B2B tax invoice.', max_length=15)),
                ('b2b_tax_kind', models.CharField(choices=[('none', 'Not a B2B bill'), ('cgst_sgst', 'CGST + SGST (same state)'), ('igst', 'IGST (different state)')], default='none', max_length=10)),
                ('gross_paise', core.money.MoneyField(default=0)),
                ('discount_paise', core.money.MoneyField(default=0)),
                ('net_paise', core.money.MoneyField(default=0, help_text='What the customer pays. May be negative - an exchange whose returns outweigh its sales issues a credit note for the difference.')),
                ('gst_paise', core.money.MoneyField(default=0)),
                ('round_paise', core.money.MoneyField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_billed', to=settings.AUTH_USER_MODEL)),
                ('exchange_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanges', to='sell.sale')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.voucherseries')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='masters.store')),
            ],
            options={
                'db_table': 'sell_sale',
                'ordering': ['-billed_at', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IrnQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_on', models.DateField(help_text='billed_at + 30 days.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('irn', models.CharField(blank=True, default='', max_length=64)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='irn_queue_item', to='sell.sale')),
            ],
            options={
                'db_table': 'sell_irn_queue',
                'ordering': ['due_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('idempotency_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('docstatus', models.IntegerField(choices=[(0, 'draft'), (1, 'submitted'), (2, 'cancelled')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fy', models.CharField(max_length=7)),
                ('customer_name', models.CharField(blank=True, default='', max_length=120)),
                ('customer_mobile', models.CharField(blank=True, default='', max_length=15)),
                ('value_paise', core.money.MoneyField(help_text='Face value at issue, in integer paise. Never changes.')),
                ('expires_on', models.DateField(help_text='Validity is data (grill Q7); set from SellPolicy at issue.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.voucherseries')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes_issued', to='masters.store')),
                ('source_sale', models.ForeignKey(blank=True, help_text='The bill that issued it - an exchange whose returns exceeded its sales.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes_issued', to='sell.sale')),
            ],
            options={
                'db_table': 'sell_credit_note',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContinuityFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('number_hole', 'Bills missing before this one'), ('cn_unverified', 'Credit note taken without verification'), ('return_orig_missing', 'Returned against a bill we do not hold'), ('offer_mismatch', 'Offer applied differs from the rulebook'), ('gst_mismatch', 'Tax charged differs from the dated slab'), ('aged_uncosted', 'Sold before inward, still unpriced')], max_length=24)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='open', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='continuity_flags', to='masters.store')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags', to='sell.sale')),
            ],
            options={
                'db_table': 'sell_continuity_flag',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_no', models.IntegerField()),
                ('direction', models.CharField(choices=[('sale', 'Sold'), ('return', 'Returned (exchange leg)')], default='sale', max_length=8)),
                ('barcode', models.CharField(db_index=True, max_length=64)),
                ('season', models.CharField(blank=True, default='', max_length=120)),
                ('design', models.CharField(blank=True, default='', max_length=120)),
                ('color', models.CharField(blank=True, default='', max_length=60)),
                ('size', models.CharField(blank=True, default='', max_length=24)),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('item', models.CharField(blank=True, default='', max_length=120)),
                ('hsn', models.CharField(blank=True, default='', max_length=24)),
                ('qty', models.IntegerField()),
                ('mrp_paise', core.money.MoneyField(default=0)),
                ('disc_paise', core.money.MoneyField(default=0)),
                ('net_paise', core.money.MoneyField(default=0, help_text='GST-inclusive line value; on a return leg, the refund.')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_paise', core.money.MoneyField(default=0)),
                ('unit_cost_paise', core.money.MoneyField(default=0, help_text='Cost of record from the cohort, frozen at billing. Zero only on a line the books cannot price yet (sold before inward).')),
                ('offer_evidence', models.JSONField(blank=True, default=dict, help_text="Which rule won, what it beat, and by how much (B3). The FK onto offers.Offer arrives with the offer engine; until then the winner's id rides inside this evidence.")),
                ('manual_desc', models.CharField(blank=True, default='', help_text='A line the scan could not resolve.', max_length=200)),
                ('sold_before_inward', models.BooleanField(default=False)),
                ('costing_status', models.CharField(choices=[('posted', 'Costed'), ('deferred', 'Waiting on the paperwork')], default='posted', max_length=8)),
                ('return_reason', models.CharField(blank=True, default='', max_length=40)),
                ('condition', models.CharField(blank=True, choices=[('good', 'Good - back on the shelf'), ('damaged', 'Damaged - into quarantine')], default='', max_length=8)),
                ('original_line', models.ForeignKey(blank=True, help_text='The line on the original bill this exchange leg gives back.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_by', to='sell.saleline')),
                ('override_by', models.ForeignKey(blank=True, help_text="The manager whose OK let this line's discount past the cap (H3).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines_overridden', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sell.sale')),
            ],
            options={
                'db_table': 'sell_sale_line',
                'ordering': ['sale_id', 'line_no'],
            },
        ),
        migrations.CreateModel(
            name='DeferredCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(db_index=True, max_length=64)),
                ('season', models.CharField(blank=True, default='', max_length=120)),
                ('qty', models.IntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting on inward'), ('posted', 'Posted')], default='waiting', max_length=8)),
                ('posted_doc_number', models.CharField(blank=True, default='', max_length=128)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deferred_costings', to='masters.store')),
                ('sale_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deferred_costing', to='sell.saleline')),
            ],
            options={
                'db_table': 'sell_deferred_costing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salesmen', to='masters.store')),
            ],
            options={
                'db_table': 'sell_salesman',
                'ordering': ['store__code', 'code'],
            },
        ),
        migrations.AddField(
            model_name='saleline',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='sell.salesman'),
        ),
        migrations.AddField(
            model_name='sale',
            name='salesman_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sell.salesman'),
        ),
        migrations.CreateModel(
            name='SaleTender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('credit_note', 'Credit note')], max_length=12)),
                ('amount_paise', core.money.MoneyField()),
                ('credit_note', models.ForeignKey(blank=True, help_text="Set when the note was recognised. A note the till could not verify is taken on a manager's OK and flagged, so this stays empty there.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenders', to='sell.creditnote')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='sell.sale')),
            ],
            options={
                'db_table': 'sell_sale_tender',
                'ordering': ['sale_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SellPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manual_discount_cap_percent', models.DecimalField(decimal_places=2, default=0, help_text='Discount a cashier may key in without a manager, as a percent of MRP.', max_digits=5)),
                ('credit_note_validity_days', models.IntegerField(default=180, help_text='How many days a credit note issued at the counter stays spendable.')),
            ],
            options={
                'verbose_name_plural': 'sell policies',
                'db_table': 'sell_policy',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='ck_sellpolicy_singleton'), models.CheckConstraint(condition=models.Q(('manual_discount_cap_percent__gte', 0), ('manual_discount_cap_percent__lte', 100)), name='ck_sellpolicy_cap_is_a_percent'), models.CheckConstraint(condition=models.Q(('credit_note_validity_days__gt', 0)), name='ck_sellpolicy_validity_is_positive')],
            },
        ),
        migrations.CreateModel(
            name='CreditNoteRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paise', core.money.MoneyField()),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='sell.creditnote')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_spends', to='sell.sale')),
            ],
            options={
                'db_table': 'sell_credit_note_redemption',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('credit_note', 'sale'), name='uq_redemption_note_sale'), models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='ck_redemption_amount_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.CheckConstraint(condition=models.Q(('docstatus', 0), ('doc_number__isnull', False), _connector='OR'), name='sell_creditnote_posted_has_number'),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.CheckConstraint(condition=models.Q(('docstatus__in', [0, 1, 2])), name='sell_creditnote_docstatus_domain'),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.CheckConstraint(condition=models.Q(('value_paise__gt', 0)), name='ck_creditnote_value_positive'),
        ),
        migrations.AddIndex(
            model_name='continuityflag',
            index=models.Index(fields=['store', 'status'], name='continuityflag_store_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesman',
            constraint=models.UniqueConstraint(fields=('store', 'code'), name='uq_salesman_store_code'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.UniqueConstraint(fields=('sale', 'line_no'), name='uq_saleline_sale_line_no'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='ck_saleline_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction', 'sale'), _negated=True), ('salesman__isnull', False), _connector='OR'), name='ck_saleline_sale_has_salesman'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store', 'billed_at'], name='sale_store_billed_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['store', 'origin'], name='sale_store_origin_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('docstatus', 0), ('doc_number__isnull', False), _connector='OR'), name='sell_sale_posted_has_number'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('docstatus__in', [0, 1, 2])), name='sell_sale_docstatus_domain'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('store', 'fy', 'till_seq'), name='uq_sale_store_fy_seq'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('till_seq__gt', 0)), name='ck_sale_till_seq_positive'),
        ),
        migrations.AddConstraint(
            model_name='saletender',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='ck_saletender_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='saletender',
            constraint=models.CheckConstraint(condition=models.Q(('credit_note__isnull', True), ('mode', 'credit_note'), _connector='OR'), name='ck_saletender_note_only_on_note_mode'),
        ),
    ]
