# Generated by Django 5.1.15 on 2026-07-30 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_deferredcosting_reason'),
        ('vendors', '0004_booking_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='cost_book',
            field=models.CharField(blank=True, choices=[('own', 'KDPS-owned - out of our own inventory'), ('brand', 'Brand-owned - against what we owe the brand')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='saleline',
            name='cost_vendor',
            field=models.ForeignKey(blank=True, help_text='Who the brand-owned piece is settled with, frozen at billing. PROTECT because a return reverses the accrual against this row.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines_accrued', to='vendors.vendor'),
        ),
    ]
