# Generated by Django 5.1.15 on 2026-07-30 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('sell', '0004_saleline_cost_book_saleline_cost_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='offer',
            field=models.ForeignKey(blank=True, help_text="The brand-layer rule that won this line. An add-on that stacked on top is in the evidence, not here: this is 'which offer was this sold under', which has exactly one answer.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='saleline',
            name='offer_evidence',
            field=models.JSONField(blank=True, default=dict, help_text='Which rule won, what it beat, and by how much (B3). Kept beside the FK rather than replaced by it: the rule can be ended and replaced, and what this bill was priced under has to stay readable afterwards (Rule 3).'),
        ),
    ]
