# Generated by Django 5.1.15 on 2026-07-31 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_dataset_watermarks'),
        ('sell', '0009_alter_continuityflag_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fy', models.CharField(max_length=7)),
                ('reason', models.CharField(max_length=240)),
                ('last_accepted_seq', models.IntegerField()),
                ('hole_count', models.IntegerField(default=0)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_handovers', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_handovers', to='masters.store')),
            ],
            options={
                'db_table': 'sell_register_handover',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['store', '-created_at'], name='handover_store_idx')],
            },
        ),
    ]
