# Generated by Django 5.1.15 on 2026-08-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0016_discount_policy_dials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deferredcosting',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting on inward'), ('posted', 'Posted'), ('returned', 'Given back before it could be priced'), ('cancelled', 'The bill was cancelled')], default='waiting', max_length=12),
        ),
    ]
