# Generated by Django 5.1.15 on 2026-09-21 21:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0020_sbu_revision_and_history'),
        ('sell', '0017_alter_deferredcosting_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredTill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counter_id', models.CharField(max_length=12)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('authority_until', models.DateTimeField(blank=True, null=True)),
                ('series_prefix', models.CharField(max_length=32)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_tills', to=settings.AUTH_USER_MODEL)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='registered_till', to='masters.store')),
            ],
            options={
                'db_table': 'sell_registered_till',
                'ordering': ['store_id'],
            },
        ),
    ]
