# Generated by Django 5.1.15 on 2026-09-22 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0021_season_historical_unknown_and_more'),
        ('sell', '0018_registeredtill'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='goods_allocations',
            field=models.JSONField(blank=True, default=list, help_text='Which goods pieces this line actually consumed, at a goods-v1 store: one entry per receipt lot portion, with the origin it was valued under and the cost frozen on that origin. Written once, at billing, and never recomputed - the bill keeps its own origin outcome (overall PRD R-POS-009), and an exchange against this line gives back these exact pieces at these exact costs. Empty at a legacy store, where the cohort carries the cost instead.'),
        ),
        migrations.CreateModel(
            name='WorkingSetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.BigIntegerField(default=1)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='working_set_version', to='masters.store')),
            ],
            options={
                'db_table': 'sell_working_set_version',
                'ordering': ['store_id'],
            },
        ),
    ]
