# Generated by Django 5.1.15 on 2026-09-22 06:28

import core.money
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0019_saleline_goods_allocations_workingsetversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash_received_paise',
            field=core.money.MoneyField(blank=True, default=None, null=True),
        ),
    ]
