# Generated by Django 5.1.15 on 2026-09-22 07:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0021_season_historical_unknown_and_more'),
        ('sell', '0020_sale_cash_received_paise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantinedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_uuid', models.UUIDField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'sell_quarantined_upload',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TillAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.BigIntegerField()),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, default='', max_length=240)),
            ],
            options={
                'db_table': 'sell_till_allocation',
                'ordering': ['-issued_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='registeredtill',
            options={'ordering': ['store_id', '-registered_at']},
        ),
        migrations.AddField(
            model_name='registeredtill',
            name='device_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='registeredtill',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payload_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='sale',
            name='till_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='sellpolicy',
            name='cached_bill_days',
            field=models.IntegerField(default=30, help_text="How many days of this store's own bills the till caches, so an exchange can be taken offline against one (OPS-09, PRD §10.3)."),
        ),
        migrations.AlterField(
            model_name='registeredtill',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_tills', to='masters.store'),
        ),
        migrations.AddConstraint(
            model_name='registeredtill',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('store',), name='uq_registered_till_active_store'),
        ),
        migrations.AddConstraint(
            model_name='registeredtill',
            constraint=models.UniqueConstraint(fields=('store', 'counter_id'), name='uq_registered_till_counter'),
        ),
        migrations.AddField(
            model_name='quarantinedupload',
            name='first_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sell.sale'),
        ),
        migrations.AddField(
            model_name='quarantinedupload',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quarantined_uploads', to='masters.store'),
        ),
        migrations.AddField(
            model_name='tillallocation',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='till_allocation_releases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tillallocation',
            name='till',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='sell.registeredtill'),
        ),
        migrations.AddIndex(
            model_name='quarantinedupload',
            index=models.Index(fields=['store', '-received_at'], name='quarantupload_store_idx'),
        ),
        migrations.AddIndex(
            model_name='tillallocation',
            index=models.Index(fields=['till', 'released_at'], name='tillalloc_live_idx'),
        ),
    ]
