# Generated by Django 5.1.15 on 2026-09-25 07:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0021_ops09_offline_till'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuityflag',
            name='kind',
            field=models.CharField(choices=[('number_hole', 'Bills missing before this one'), ('cn_unverified', 'Credit note taken without verification'), ('return_orig_missing', 'Returned against a bill we do not hold'), ('offer_mismatch', 'Offer applied differs from the rulebook'), ('gst_mismatch', 'Tax charged differs from the dated slab'), ('aged_uncosted', 'Sold before inward, still unpriced'), ('gstin_invalid', "The buyer's GSTIN is not well formed"), ('billed_while_paused', 'Billed while the counter was paused'), ('return_late', 'Taken back after the return window closed'), ('return_uncosted', 'Given back before the books could price it'), ('employee_returns', 'One seller took back an unusual number')], max_length=24),
        ),
        migrations.CreateModel(
            name='TillPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fy', models.CharField(max_length=7)),
                ('next_seq', models.IntegerField()),
                ('paused_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(max_length=240)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('resumed_next_seq', models.IntegerField(blank=True, null=True)),
                ('allocation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pause', to='sell.tillallocation')),
                ('paused_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='till_pauses', to=settings.AUTH_USER_MODEL)),
                ('resumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='till_resumes', to=settings.AUTH_USER_MODEL)),
                ('till', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pauses', to='sell.registeredtill')),
            ],
            options={
                'db_table': 'sell_till_pause',
                'ordering': ['-paused_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resumed_at__isnull', True)), fields=('till',), name='tillpause_one_live_per_till')],
            },
        ),
    ]
