# Generated by Django 5.1.15 on 2026-09-26 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0025_document_series'),
        ('sell', '0024_sale_tax_setting_version_alter_continuityflag_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tax_invoice_number',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='continuityflag',
            name='kind',
            field=models.CharField(choices=[('number_hole', 'Bills missing before this one'), ('cn_unverified', 'Credit note taken without verification'), ('return_orig_missing', 'Returned against a bill we do not hold'), ('offer_mismatch', 'Offer applied differs from the rulebook'), ('gst_mismatch', 'Tax charged differs from the dated slab'), ('aged_uncosted', 'Sold before inward, still unpriced'), ('gstin_invalid', "The buyer's GSTIN is not well formed"), ('billed_while_paused', 'Billed while the counter was paused'), ('return_late', 'Taken back after the return window closed'), ('return_uncosted', 'Given back before the books could price it'), ('employee_returns', 'One seller took back an unusual number'), ('tax_version_mismatch', 'Taxed under another tax version'), ('tax_rule_missing', "No tax rule for an item's HSN"), ('invoice_number_missing', 'No number in the new invoice series'), ('invoice_number_problem', 'Invoice number needs checking')], max_length=24),
        ),
        migrations.CreateModel(
            name='TillNumberBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix_code', models.CharField(max_length=3)),
                ('fy', models.CharField(max_length=5)),
                ('month', models.DateField()),
                ('first_n', models.BigIntegerField()),
                ('last_n', models.BigIntegerField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_count', models.IntegerField(default=0)),
                ('prefix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.documentprefix')),
                ('till', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='number_blocks', to='sell.registeredtill')),
            ],
            options={
                'db_table': 'sell_till_number_block',
                'ordering': ['month', 'first_n'],
                'indexes': [models.Index(fields=['till', 'month'], name='till_block_month_idx'), models.Index(fields=['prefix', 'fy', 'first_n'], name='till_block_range_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('first_n__gte', 1), ('last_n__gte', models.F('first_n'))), name='ck_till_number_block_range')],
            },
        ),
    ]
