# Generated by Django 5.1.15 on 2026-09-27 10:04

import core.money
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_merge_store_roles"),
        ("sell", "0029_drop_old_salesperson_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="continuityflag",
            name="kind",
            field=models.CharField(
                choices=[
                    ("number_hole", "Bills missing before this one"),
                    ("cn_unverified", "Credit note taken without verification"),
                    ("return_orig_missing", "Returned against a bill we do not hold"),
                    ("offer_mismatch", "Offer applied differs from the rulebook"),
                    ("gst_mismatch", "Tax charged differs from the dated slab"),
                    ("aged_uncosted", "Sold before inward, still unpriced"),
                    ("gstin_invalid", "The buyer's GSTIN is not well formed"),
                    ("billed_while_paused", "Billed while the counter was paused"),
                    ("return_late", "Taken back after the return window closed"),
                    ("return_uncosted", "Given back before the books could price it"),
                    ("employee_returns", "One seller took back an unusual number"),
                    ("tax_version_mismatch", "Taxed under another tax version"),
                    ("tax_rule_missing", "No tax rule for an item's HSN"),
                    ("invoice_number_missing", "No number in the new invoice series"),
                    ("invoice_number_problem", "Invoice number needs checking"),
                    ("override_self_approved", "Override approved by the cashier"),
                    ("split_while_off", "Split sale from a store with it off"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="SaleLineShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField()),
                ("salesperson_code", models.CharField(blank=True, default="", max_length=40)),
                ("salesperson_name", models.CharField(blank=True, default="", max_length=160)),
                ("percent", models.PositiveSmallIntegerField()),
                ("value_paise", core.money.MoneyField(default=0)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="sell.saleline",
                    ),
                ),
                (
                    "salesperson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.staff",
                    ),
                ),
            ],
            options={
                "db_table": "sell_sale_line_share",
                "ordering": ["line_id", "position"],
                "indexes": [models.Index(fields=["salesperson"], name="saleshare_salesperson_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("line", "position"), name="uq_saleshare_line_position"
                    ),
                    models.UniqueConstraint(
                        fields=("line", "salesperson"), name="uq_saleshare_line_salesperson"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("position__gte", 1), ("position__lte", 2)),
                        name="ck_saleshare_position",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("percent__gte", 1), ("percent__lte", 99)),
                        name="ck_saleshare_percent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("value_paise__gte", 0)),
                        name="ck_saleshare_value_positive",
                    ),
                ],
            },
        ),
    ]
