# Generated by Django 5.1.15 on 2026-09-27 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_seed_offer_approval_policy'),
        ('sell', '0030_split_sale_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='gst_after_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saletender',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='continuityflag',
            name='kind',
            field=models.CharField(choices=[('number_hole', 'Bills missing before this one'), ('cn_unverified', 'Credit note taken without verification'), ('return_orig_missing', 'Returned against a bill we do not hold'), ('offer_mismatch', 'Offer applied differs from the rulebook'), ('gst_mismatch', 'Tax charged differs from the dated slab'), ('aged_uncosted', 'Sold before inward, still unpriced'), ('gstin_invalid', "The buyer's GSTIN is not well formed"), ('billed_while_paused', 'Billed while the counter was paused'), ('return_late', 'Taken back after the return window closed'), ('return_uncosted', 'Given back before the books could price it'), ('employee_returns', 'One seller took back an unusual number'), ('tax_version_mismatch', 'Taxed under another tax version'), ('tax_rule_missing', "No tax rule for an item's HSN"), ('invoice_number_missing', 'No number in the new invoice series'), ('invoice_number_problem', 'Invoice number needs checking'), ('override_self_approved', 'Override approved by the cashier'), ('split_while_off', 'Split sale from a store with it off'), ('after_discount_mismatch', 'Discount tax rules differ from switch'), ('till_server_mismatch', 'Till and server differ on the bill')], max_length=24),
        ),
        migrations.AlterField(
            model_name='saletender',
            name='mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('credit_note', 'Credit note'), ('bank_offer', 'Bank offer')], max_length=12),
        ),
        migrations.AddConstraint(
            model_name='saletender',
            constraint=models.CheckConstraint(condition=models.Q(('offer__isnull', True), ('mode', 'bank_offer'), _connector='OR'), name='ck_saletender_offer_only_on_bank_offer'),
        ),
    ]
