# Generated by Django 5.1.15 on 2026-09-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0031_gst_after_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='tax_rule_hsn_prefix',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='saleline',
            name='tax_rule_kind',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='saleline',
            name='tax_setting_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
