# Generated by Django 5.1.15 on 2026-09-27 16:00

import core.money
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_store_roles'),
        ('masters', '0025_document_series'),
        ('offers', '0004_seed_offer_approval_policy'),
        ('sell', '0032_sale_line_tax_rule'),
        ('vendors', '0010_bookingline_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gstin', models.CharField(max_length=15)),
                ('number', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('series', models.CharField(choices=[('CN', 'Credit note series'), ('CRN', "Today's credit-note numbering")], max_length=3)),
                ('issued_on', models.DateField()),
                ('value_paise', core.money.MoneyField(help_text='What the pieces coming back were worth: Σ leg values.')),
                ('gst_paise', core.money.MoneyField(default=0, help_text='The tax it reverses; nought when late.')),
                ('bank_offer_paise', core.money.MoneyField(default=0, help_text="B60: the bank's part, reversed to it.")),
                ('late', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sell_exchange_credit_note',
                'ordering': ['-issued_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='return_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleline',
            name='bank_offer_paise',
            field=core.money.MoneyField(default=0),
        ),
        migrations.AlterField(
            model_name='continuityflag',
            name='kind',
            field=models.CharField(choices=[('number_hole', 'Bills missing before this one'), ('cn_unverified', 'Credit note taken without verification'), ('return_orig_missing', 'Returned against a bill we do not hold'), ('offer_mismatch', 'Offer applied differs from the rulebook'), ('gst_mismatch', 'Tax charged differs from the dated slab'), ('aged_uncosted', 'Sold before inward, still unpriced'), ('gstin_invalid', "The buyer's GSTIN is not well formed"), ('billed_while_paused', 'Billed while the counter was paused'), ('return_late', 'Taken back after the return window closed'), ('return_uncosted', 'Given back before the books could price it'), ('employee_returns', 'One seller took back an unusual number'), ('tax_version_mismatch', 'Taxed under another tax version'), ('tax_rule_missing', "No tax rule for an item's HSN"), ('invoice_number_missing', 'No number in the new invoice series'), ('invoice_number_problem', 'Invoice number needs checking'), ('override_self_approved', 'Override approved by the cashier'), ('split_while_off', 'Split sale from a store with it off'), ('after_discount_mismatch', 'Discount tax rules differ from switch'), ('till_server_mismatch', 'Till and server differ on the bill'), ('late_credit_note', 'Taken back after the credit-note deadline'), ('return_tax_mismatch', 'Return tax rules differ from the switch'), ('cn_deadline_mismatch', 'Till and server differ on the deadline'), ('bank_share_returned', 'Bank offer part reversed on a return'), ('bank_share_mismatch', 'Till and server differ on the bank part'), ('credit_note_number', 'Credit note number needs checking')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.CheckConstraint(condition=models.Q(('bank_offer_paise', 0), models.Q(('direction', 'return'), ('bank_offer_paise__gt', 0), ('bank_offer_paise__lte', models.F('net_paise'))), _connector='OR'), name='ck_saleline_bank_offer_on_return_leg'),
        ),
        migrations.AddField(
            model_name='exchangecreditnote',
            name='original_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sell.sale'),
        ),
        migrations.AddField(
            model_name='exchangecreditnote',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_credit_note', to='sell.sale'),
        ),
        migrations.AddField(
            model_name='exchangecreditnote',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddConstraint(
            model_name='exchangecreditnote',
            constraint=models.CheckConstraint(condition=models.Q(('value_paise__gt', 0)), name='ck_exchangecn_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='exchangecreditnote',
            constraint=models.CheckConstraint(condition=models.Q(('gst_paise__gte', 0), ('gst_paise__lte', models.F('value_paise'))), name='ck_exchangecn_gst_within_value'),
        ),
        migrations.AddConstraint(
            model_name='exchangecreditnote',
            constraint=models.CheckConstraint(condition=models.Q(('bank_offer_paise__gte', 0), ('bank_offer_paise__lte', models.F('value_paise'))), name='ck_exchangecn_bank_within_value'),
        ),
        migrations.AddConstraint(
            model_name='exchangecreditnote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('late', True), _negated=True), ('gst_paise', 0), _connector='OR'), name='ck_exchangecn_late_reduces_no_tax'),
        ),
    ]
