# Generated by Django 5.1.15 on 2026-09-27 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masters", "0026_consent_wording"),
        ("sell", "0033_exchange_return_tax"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentAnswer",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("mobile", models.CharField(max_length=15)),
                (
                    "question",
                    models.CharField(
                        choices=[("bill", "Send my bill"), ("offers", "Send me offers")],
                        max_length=8,
                    ),
                ),
                (
                    "given",
                    models.BooleanField(
                        help_text="Yes (consent given) or no (refused or withdrawn)."
                    ),
                ),
                (
                    "how",
                    models.CharField(
                        choices=[
                            ("display", "On the customer display"),
                            ("counter", "At the counter"),
                        ],
                        max_length=8,
                    ),
                ),
                ("under_18", models.BooleanField(blank=True, null=True)),
                ("wording_version", models.PositiveIntegerField()),
                ("answered_at", models.DateTimeField()),
                ("till_number", models.CharField(blank=True, default="", max_length=64)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.store",
                    ),
                ),
            ],
            options={
                "db_table": "sell_consent_answer",
                "ordering": ["-answered_at", "-received_at"],
                "indexes": [
                    models.Index(
                        fields=["mobile", "question", "answered_at"], name="sell_consent_newest_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("given", False), ("how", "display"), _connector="OR"),
                        name="ck_consent_yes_only_on_display",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("given", True), ("question", "offers"), _negated=True),
                            models.Q(("under_18", False), ("under_18__isnull", False)),
                            _connector="OR",
                        ),
                        name="ck_consent_offers_not_under_18",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("question", "bill"), _negated=True),
                            ("under_18__isnull", True),
                            _connector="OR",
                        ),
                        name="ck_consent_bill_asks_no_age",
                    ),
                ],
            },
        ),
    ]
