# Generated by Django 5.1.15 on 2026-09-28 08:01

import core.money
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customer_reservation'),
        ('masters', '0028_season_ended_on'),
        ('offers', '0004_seed_offer_approval_policy'),
        ('sell', '0034_customer_consent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('idempotency_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('docstatus', models.IntegerField(choices=[(0, 'draft'), (1, 'submitted'), (2, 'cancelled')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('issued_on', models.DateField()),
                ('amount_paise', core.money.MoneyField()),
                ('mode', models.CharField(max_length=8)),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'sell_receipt_voucher',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveSmallIntegerField()),
                ('barcode', models.CharField(max_length=64)),
                ('season', models.CharField(blank=True, default='', max_length=24)),
                ('sku_id', models.UUIDField()),
                ('qty', models.PositiveIntegerField()),
                ('item', models.JSONField(default=dict)),
                ('portions', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'sell_reservation_piece',
                'ordering': ['reservation_id', 'line_no'],
            },
        ),
        migrations.AlterField(
            model_name='saletender',
            name='mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('credit_note', 'Credit note'), ('bank_offer', 'Bank offer'), ('advance', 'Reservation advance')], max_length=12),
        ),
        migrations.CreateModel(
            name='CustomerReservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=32, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_mobile', models.CharField(db_index=True, max_length=15)),
                ('status', models.CharField(choices=[('active', 'Reserved'), ('collected', 'Collected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=10)),
                ('reserved_on', models.DateField()),
                ('collect_by', models.DateField()),
                ('days', models.PositiveSmallIntegerField()),
                ('sale_period', models.BooleanField(default=False)),
                ('advance_policy', models.CharField(choices=[('refund', 'Refunded'), ('keep', 'Kept')], max_length=8)),
                ('terms', models.TextField()),
                ('hold_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, choices=[('collected', 'Collected on a bill'), ('customer_cancelled', 'Cancelled by the customer'), ('store_cancelled', 'Cancelled by the store'), ('expired', 'Not collected by the date')], default='', max_length=20)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hold_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.officialversion')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sell.sale')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'sell_customer_reservation',
                'ordering': ['collect_by', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvanceMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('received', 'Advance received'), ('used', 'Used on the pickup bill'), ('refunded', 'Refunded'), ('forfeited', 'Forfeited')], max_length=10)),
                ('mode', models.CharField(blank=True, default='', max_length=8)),
                ('amount_paise', core.money.MoneyField()),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('at', models.DateTimeField()),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sell.sale')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_movements', to='sell.customerreservation')),
            ],
            options={
                'db_table': 'sell_reservation_advance',
                'ordering': ['reservation_id', 'at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='saletender',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sell.customerreservation'),
        ),
        migrations.AddConstraint(
            model_name='saletender',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mode', 'advance'), ('reservation__isnull', False)), models.Q(models.Q(('mode', 'advance'), _negated=True), ('reservation__isnull', True)), _connector='OR'), name='ck_saletender_reservation_iff_advance'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='voucher', to='sell.customerreservation'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.voucherseries'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='reservationpiece',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='sell.customerreservation'),
        ),
        migrations.AddIndex(
            model_name='customerreservation',
            index=models.Index(fields=['store', 'status'], name='sell_resv_store_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerreservation',
            constraint=models.CheckConstraint(condition=models.Q(('collect_by__gte', models.F('reserved_on'))), name='ck_reservation_collect_after_reserved'),
        ),
        migrations.AddConstraint(
            model_name='customerreservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('close_reason', ''), ('closed_at__isnull', True), ('status', 'active')), models.Q(models.Q(('status', 'active'), _negated=True), ('closed_at__isnull', False), models.Q(('close_reason', ''), _negated=True)), _connector='OR'), name='ck_reservation_closed_iff_not_active'),
        ),
        migrations.AddConstraint(
            model_name='customerreservation',
            constraint=models.CheckConstraint(condition=models.Q(('sale__isnull', True), ('status', 'collected'), _connector='OR'), name='ck_reservation_sale_only_when_collected'),
        ),
        migrations.AddConstraint(
            model_name='advancemovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='ck_advance_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='advancemovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ['received', 'refunded']), ('mode__in', ['cash', 'card', 'upi'])), models.Q(('kind__in', ['used', 'forfeited']), ('mode', '')), _connector='OR'), name='ck_advance_mode_by_kind'),
        ),
        migrations.AddConstraint(
            model_name='advancemovement',
            constraint=models.CheckConstraint(condition=models.Q(('sale__isnull', True), ('kind', 'used'), _connector='OR'), name='ck_advance_sale_only_when_used'),
        ),
        migrations.AddConstraint(
            model_name='receiptvoucher',
            constraint=models.CheckConstraint(condition=models.Q(('docstatus', 0), ('doc_number__isnull', False), _connector='OR'), name='sell_receiptvoucher_posted_has_number'),
        ),
        migrations.AddConstraint(
            model_name='receiptvoucher',
            constraint=models.CheckConstraint(condition=models.Q(('docstatus__in', [0, 1, 2])), name='sell_receiptvoucher_docstatus_domain'),
        ),
        migrations.AddConstraint(
            model_name='receiptvoucher',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='ck_receiptvoucher_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='receiptvoucher',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ['cash', 'card', 'upi'])), name='ck_receiptvoucher_mode'),
        ),
        migrations.AddConstraint(
            model_name='reservationpiece',
            constraint=models.UniqueConstraint(fields=('reservation', 'line_no'), name='uq_reservation_piece_line'),
        ),
        migrations.AddConstraint(
            model_name='reservationpiece',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='ck_reservation_piece_qty'),
        ),
    ]
