# Generated by Django 5.1.15 on 2026-09-27 22:43

import core.money
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0028_season_ended_on'),
        ('sell', '0034_customer_consent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('business_day', models.DateField()),
                ('counted_at', models.DateTimeField()),
                ('window_from', models.DateTimeField()),
                ('opening_paise', core.money.MoneyField()),
                ('opening_declared', models.BooleanField(default=False)),
                ('cash_sales_paise', core.money.MoneyField()),
                ('cash_refunds_paise', core.money.MoneyField(default=0)),
                ('movements_paise', core.money.MoneyField(default=0)),
                ('petty_cash_paise', core.money.MoneyField(default=0)),
                ('expected_paise', core.money.MoneyField()),
                ('notes', models.JSONField()),
                ('coins_paise', core.money.MoneyField(default=0)),
                ('counted_paise', core.money.MoneyField()),
                ('variance_paise', core.money.MoneyField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('till_number', models.CharField(blank=True, default='', max_length=64)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('counted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('previous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next', to='sell.cashcount')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'sell_cash_count',
                'ordering': ['-counted_at'],
            },
        ),
        migrations.CreateModel(
            name='CashCountBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='sell.cashcount')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cash_count_link', to='sell.sale')),
            ],
            options={
                'db_table': 'sell_cash_count_bill',
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('deposit', 'Bank deposit'), ('handover', 'Handover')], max_length=10)),
                ('amount_paise', core.money.MoneyField()),
                ('received_by', models.CharField(max_length=120)),
                ('reference', models.CharField(max_length=64)),
                ('recorded_at', models.DateTimeField()),
                ('till_number', models.CharField(blank=True, default='', max_length=64)),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'sell_cash_movement',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='cashcount',
            constraint=models.UniqueConstraint(fields=('store', 'business_day'), name='uq_cash_count_day'),
        ),
        migrations.AddConstraint(
            model_name='cashcount',
            constraint=models.CheckConstraint(condition=models.Q(('variance_paise', django.db.models.expressions.CombinedExpression(models.F('counted_paise'), '-', models.F('expected_paise')))), name='ck_cash_count_variance'),
        ),
        migrations.AddConstraint(
            model_name='cashcount',
            constraint=models.CheckConstraint(condition=models.Q(('counted_paise__gte', 0), ('coins_paise__gte', 0), ('opening_paise__gte', 0)), name='ck_cash_count_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='cashcount',
            constraint=models.CheckConstraint(condition=models.Q(('variance_paise', 0), ('approved_by__isnull', False), _connector='OR'), name='ck_cash_count_variance_approved'),
        ),
        migrations.AddConstraint(
            model_name='cashcount',
            constraint=models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('counted_by')), _negated=True), _connector='OR'), name='ck_cash_count_not_self_approved'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['store', 'recorded_at'], name='sell_cash_move_store_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='ck_cash_movement_positive'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('received_by', ''), _negated=True), models.Q(('reference', ''), _negated=True)), name='ck_cash_movement_both_sides'),
        ),
    ]
