# Generated by Django 5.1.15 on 2026-09-27 23:03

import core.money
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0028_season_ended_on'),
        ('offers', '0004_seed_offer_approval_policy'),
        ('sell', '0034_customer_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLineFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.PositiveSmallIntegerField()),
                ('offer_name', models.CharField(blank=True, default='', max_length=160)),
                ('funder', models.CharField(blank=True, choices=[('brand', 'The brand, by its terms'), ('kdps', 'KDPS')], default='', max_length=8)),
                ('discount_paise', core.money.MoneyField(default=0)),
                ('brand_paise', core.money.MoneyField(blank=True, null=True)),
                ('kdps_paise', core.money.MoneyField(blank=True, null=True)),
                ('unknown_reason', models.CharField(blank=True, choices=[('model_unknown', 'The brand has no approved terms for this season'), ('share_unknown', "The brand's terms leave its discount share unknown"), ('brand_unknown', "The line's brand is not one brand in the brand list"), ('season_unknown', "The line's season is not in the season list"), ('offer_unknown', 'The offer the bill names is not on the books'), ('parts_disagree', "The bill's offers add up to more than the line's discount"), ('offer_unverified', "The till's offer savings are more than the offers give on the server's reading")], default='', max_length=16)),
                ('terms_version_id', models.UUIDField(blank=True, null=True)),
                ('funding_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('brand_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding', to='sell.saleline')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='offers.offer')),
                ('season_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.season')),
            ],
            options={
                'db_table': 'sell_sale_line_funding',
                'ordering': ['line_id', 'part'],
                'constraints': [models.UniqueConstraint(fields=('line', 'part'), name='uq_salefunding_line_part'), models.CheckConstraint(condition=models.Q(('part__gte', 1)), name='ck_salefunding_part_from_one'), models.CheckConstraint(condition=models.Q(('discount_paise__gt', 0)), name='ck_salefunding_discount_positive'), models.CheckConstraint(condition=models.Q(models.Q(('brand_paise__gte', 0), ('brand_paise__isnull', False), ('discount_paise', django.db.models.expressions.CombinedExpression(models.F('brand_paise'), '+', models.F('kdps_paise'))), ('kdps_paise__gte', 0), ('kdps_paise__isnull', False), ('unknown_reason', '')), models.Q(models.Q(('unknown_reason', ''), _negated=True), ('brand_paise__isnull', True), ('kdps_paise__isnull', True)), _connector='OR'), name='ck_salefunding_known_or_unknown')],
            },
        ),
    ]
