# Generated by Django 5.1.15 on 2026-09-27 22:09

import core.money
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0028_season_ended_on'),
        ('offers', '0004_seed_offer_approval_policy'),
        ('sell', '0034_customer_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField()),
                ('gstin', models.CharField(blank=True, default='', max_length=15)),
                ('qty', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('gift_offer', 'Gift with purchase'), ('free', 'Given free, no gift offer')], max_length=12)),
                ('offer_name', models.CharField(blank=True, default='', max_length=200)),
                ('cost_paise', core.money.MoneyField(blank=True, null=True)),
                ('itc_paise', core.money.MoneyField(blank=True, null=True)),
                ('missing', models.CharField(blank=True, choices=[('', 'Known'), ('no_layer', 'No receipt layer recorded'), ('no_rate', 'No input tax rate on its receipt'), ('other_gstin', 'Received under another GSTIN')], default='', max_length=12)),
                ('layers', models.JSONField(blank=True, default=list)),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gift', to='sell.saleline')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='offers.offer')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_pieces', to='sell.sale')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'sell_gift_piece',
                'ordering': ['-day', '-id'],
                'indexes': [models.Index(fields=['store', 'day'], name='sell_gift_p_store_i_0aa52b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='ck_giftpiece_qty'), models.CheckConstraint(condition=models.Q(('missing', ''), ('itc_paise__isnull', True), _connector='OR'), name='ck_giftpiece_missing_has_no_credit')],
            },
        ),
    ]
