# Generated by Django 5.1.15 on 2026-09-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0035_gift_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftpiece',
            name='tax_setting_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
