# Generated by Django 5.1.15 on 2026-09-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0035_customer_erasure'),
        ('sell', '0035_discount_funding'),
        ('sell', '0036_gift_piece_tax_version'),
    ]

    operations = [
    ]
