# Generated by Django 5.1.15 on 2026-09-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0035_cash_count'),
        ('sell', '0037_merge_20260928_1245'),
    ]

    operations = [
    ]
