# Generated by Django 5.1.15 on 2026-09-28 08:08

import core.goods_base
import core.money
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from core.dbroles import tenant_rls_sql

#: Both tables behind the tenant wall; what a claim claims frozen when raised; a
#: settled claim final; nothing deleted and a claimed part never changed (ticket 26).
GUARDS = f"""
{tenant_rls_sql("sell_brand_claim")}
{tenant_rls_sql("sell_brand_claim_part")}
CREATE OR REPLACE FUNCTION kdps_brand_claim_final() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'brand claims are never deleted (%)', TG_TABLE_NAME;
    END IF;
    IF TG_TABLE_NAME = 'sell_brand_claim_part' THEN
        RAISE EXCEPTION 'which part a brand claim took in is never changed';
    END IF;
    IF OLD.status IN ('settled', 'settled_short') THEN
        RAISE EXCEPTION 'a settled brand claim is never edited';
    END IF;
    IF (NEW.tenant_id, NEW.brand_id, NEW.store_id, NEW.month, NEW.sequence, NEW.reference,
        NEW.amount_paise, NEW.parts, NEW.pieces, NEW.unknown_paise, NEW.promotion_flag)
       IS DISTINCT FROM
       (OLD.tenant_id, OLD.brand_id, OLD.store_id, OLD.month, OLD.sequence, OLD.reference,
        OLD.amount_paise, OLD.parts, OLD.pieces, OLD.unknown_paise, OLD.promotion_flag) THEN
        RAISE EXCEPTION 'what a brand claim claims is frozen when it is raised';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER sell_brand_claim_final BEFORE UPDATE OR DELETE ON sell_brand_claim
    FOR EACH ROW EXECUTE FUNCTION kdps_brand_claim_final();
CREATE TRIGGER sell_brand_claim_part_final BEFORE UPDATE OR DELETE
    ON sell_brand_claim_part FOR EACH ROW EXECUTE FUNCTION kdps_brand_claim_final();
"""

UNGUARD = """
DROP TRIGGER IF EXISTS sell_brand_claim_final ON sell_brand_claim;
DROP TRIGGER IF EXISTS sell_brand_claim_part_final ON sell_brand_claim_part;
DROP FUNCTION IF EXISTS kdps_brand_claim_final();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0029_customer_corrected_at'),
        ('sell', '0038_merge_0035_cash_count_0037_merge_20260928_1245'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('discount', 'Brand-funded discount')], default='discount', max_length=12)),
                ('month', models.DateField()),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('reference', models.CharField(max_length=60)),
                ('amount_paise', core.money.MoneyField()),
                ('parts', models.PositiveIntegerField(default=0)),
                ('pieces', models.IntegerField(default=0)),
                ('unknown_paise', core.money.MoneyField(default=0)),
                ('status', models.CharField(choices=[('raised', 'Raised'), ('accepted', 'Accepted by the brand'), ('settled', 'Settled'), ('settled_short', 'Settled short')], default='raised', max_length=14)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('promotion_flag', models.BooleanField(default=False)),
                ('promotion_version_id', models.UUIDField(blank=True, null=True)),
                ('accepted_on', models.DateField(blank=True, null=True)),
                ('accepted_note', models.CharField(blank=True, default='', max_length=240)),
                ('credit_note_number', models.CharField(blank=True, default='', max_length=60)),
                ('credit_note_date', models.DateField(blank=True, null=True)),
                ('settled_paise', core.money.MoneyField(blank=True, null=True)),
                ('difference_paise', core.money.MoneyField(blank=True, null=True)),
                ('difference_reason', models.CharField(blank=True, default='', max_length=240)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('tenant', models.ForeignKey(db_default=core.goods_base.CurrentTenant(), editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'db_table': 'sell_brand_claim',
                'ordering': ['-month', 'store_id', 'brand_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='BrandClaimPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_id', models.BigIntegerField(unique=True)),
                ('sale_id', models.BigIntegerField()),
                ('line_id', models.BigIntegerField()),
                ('brand_paise', core.money.MoneyField()),
                ('pieces', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claimed_parts', to='sell.brandclaim')),
                ('tenant', models.ForeignKey(db_default=core.goods_base.CurrentTenant(), editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'db_table': 'sell_brand_claim_part',
            },
        ),
        migrations.AddIndex(
            model_name='brandclaim',
            index=models.Index(fields=['month', 'store'], name='sell_brand__month_71803a_idx'),
        ),
        migrations.AddIndex(
            model_name='brandclaim',
            index=models.Index(fields=['status'], name='sell_brand__status_51fce3_idx'),
        ),
        migrations.AddConstraint(
            model_name='brandclaim',
            constraint=models.UniqueConstraint(fields=('tenant', 'brand', 'store', 'month', 'sequence'), name='uq_brandclaim_month_sequence'),
        ),
        migrations.AddConstraint(
            model_name='brandclaim',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='ck_brandclaim_amount'),
        ),
        migrations.AddConstraint(
            model_name='brandclaim',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['settled', 'settled_short']), _negated=True), models.Q(models.Q(('credit_note_number', ''), _negated=True), ('credit_note_date__isnull', False), ('settled_paise__isnull', False)), _connector='OR'), name='ck_brandclaim_settled_note'),
        ),
        migrations.AddConstraint(
            model_name='brandclaim',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'settled_short'), _negated=True), models.Q(('difference_paise__gt', 0), models.Q(('difference_reason', ''), _negated=True)), _connector='OR'), name='ck_brandclaim_short_reason'),
        ),
        migrations.RunSQL(GUARDS, UNGUARD),
    ]
