# Generated by Django 5.1.15 on 2026-09-28 08:06

import core.money
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0029_customer_corrected_at'),
        ('sell', '0038_merge_0035_cash_count_0037_merge_20260928_1245'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcount',
            name='petty_top_ups_paise',
            field=core.money.MoneyField(default=0),
        ),
        migrations.CreateModel(
            name='PettyCashFloat',
            fields=[
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='+', serialize=False, to='masters.store')),
                ('float_paise', core.money.MoneyField()),
                ('revision', models.PositiveIntegerField(default=1)),
                ('set_at', models.DateTimeField()),
                ('custodian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('set_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sell_petty_cash_float',
                'constraints': [models.CheckConstraint(condition=models.Q(('float_paise__gt', 0)), name='ck_petty_float_positive')],
            },
        ),
        migrations.CreateModel(
            name='PettyCashSpend',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(editable=False, unique=True)),
                ('head', models.CharField(max_length=60)),
                ('amount_paise', core.money.MoneyField()),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('spent', 'Spent'), ('waiting', 'Waiting for the Owner'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('counts_from', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=2000)),
                ('bill_key', models.CharField(blank=True, default='', max_length=500)),
                ('bill_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('bill_media_type', models.CharField(blank=True, default='', max_length=100)),
                ('bill_size', models.PositiveIntegerField(default=0)),
                ('bill_filename', models.CharField(blank=True, default='', max_length=255)),
                ('bill_attached_at', models.DateTimeField(blank=True, null=True)),
                ('bill_attached_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('custodian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'sell_petty_cash_spend',
                'ordering': ['-recorded_at', '-id'],
                'indexes': [models.Index(fields=['store', 'counts_from'], name='sell_petty_spend_counts_idx'), models.Index(fields=['store', 'recorded_at'], name='sell_petty_spend_store_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='ck_petty_spend_positive'), models.CheckConstraint(condition=models.Q(models.Q(('counts_from__isnull', False), ('status__in', ['spent', 'approved'])), models.Q(('counts_from__isnull', True), ('status__in', ['waiting', 'rejected'])), _connector='OR'), name='ck_petty_spend_counts_from'), models.CheckConstraint(condition=models.Q(models.Q(('decided_by__isnull', False), ('status__in', ['approved', 'rejected'])), models.Q(('decided_by__isnull', True), ('status__in', ['spent', 'waiting'])), _connector='OR'), name='ck_petty_spend_decided'), models.CheckConstraint(condition=models.Q(('decided_by__isnull', True), models.Q(('decided_by', models.F('recorded_by')), _negated=True), _connector='OR'), name='ck_petty_spend_not_self_decided'), models.CheckConstraint(condition=models.Q(models.Q(('bill_key', ''), ('bill_sha256', '')), models.Q(models.Q(('bill_key', ''), _negated=True), models.Q(('bill_sha256', ''), _negated=True), ('bill_attached_at__isnull', False)), _connector='OR'), name='ck_petty_spend_bill_whole')],
            },
        ),
        migrations.CreateModel(
            name='PettyCashTopUp',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('till', 'From the till'), ('head_office', 'From head office')], max_length=12)),
                ('amount_paise', core.money.MoneyField()),
                ('given_by_name', models.CharField(blank=True, default='', max_length=120)),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('recorded_at', models.DateTimeField()),
                ('custodian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'sell_petty_cash_top_up',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['store', 'recorded_at'], name='sell_petty_topup_store_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='ck_petty_topup_positive'), models.CheckConstraint(condition=models.Q(('source', 'till'), models.Q(models.Q(('given_by_name', ''), _negated=True), models.Q(('reference', ''), _negated=True)), _connector='OR'), name='ck_petty_topup_ho_both_sides')],
            },
        ),
    ]
