# Generated by Django 5.1.15 on 2026-09-28 08:06

import core.money
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0029_customer_corrected_at'),
        ('sell', '0038_merge_0035_cash_count_0037_merge_20260928_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLineMarginShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(blank=True, choices=[('sor', 'SOR'), ('concession', 'Concession')], default='', max_length=12)),
                ('value_paise', core.money.MoneyField(default=0)),
                ('margin_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kdps_paise', core.money.MoneyField(blank=True, null=True)),
                ('brand_paise', core.money.MoneyField(blank=True, null=True)),
                ('unknown_reason', models.CharField(blank=True, choices=[('model_unknown', 'The brand has no approved terms for this season'), ('margin_unknown', "The brand's terms leave its margin unknown"), ('brand_unknown', "The line's brand is not one brand in the brand list"), ('season_unknown', "The line's season is not in the season list")], default='', max_length=16)),
                ('terms_version_id', models.UUIDField(blank=True, null=True)),
                ('brand_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand')),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='margin_share', to='sell.saleline')),
                ('season_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.season')),
            ],
            options={
                'db_table': 'sell_sale_line_margin_share',
                'ordering': ['line_id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('value_paise__gte', 0)), name='ck_salemargin_value_not_negative'), models.CheckConstraint(condition=models.Q(models.Q(('brand_paise__gte', 0), ('brand_paise__isnull', False), ('kdps_paise__gte', 0), ('kdps_paise__isnull', False), ('margin_percent__isnull', False), ('model__in', ['sor', 'concession']), ('unknown_reason', ''), ('value_paise', django.db.models.expressions.CombinedExpression(models.F('kdps_paise'), '+', models.F('brand_paise')))), models.Q(models.Q(('unknown_reason', ''), _negated=True), ('brand_paise__isnull', True), ('kdps_paise__isnull', True)), _connector='OR'), name='ck_salemargin_known_or_unknown')],
            },
        ),
    ]
