# Generated by Django 5.1.15 on 2026-09-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0039_margin_share'),
        ('sell', '0039_petty_cash'),
    ]

    operations = [
    ]
