# Generated by Django 5.1.15 on 2026-09-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0039_brand_claims'),
        ('sell', '0040_merge_0039_margin_share_0039_petty_cash'),
    ]

    operations = [
    ]
