# Generated by Django 5.1.15 on 2026-09-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0036_reservation_ref_per_store_append_only'),
        ('sell', '0041_merge_20260928_1537'),
    ]

    operations = [
    ]
