# Generated by Django 5.1.15 on 2026-09-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0042_merge_20260928_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuityflag',
            name='kind',
            field=models.CharField(choices=[('number_hole', 'Bills missing before this one'), ('cn_unverified', 'Credit note taken without verification'), ('return_orig_missing', 'Returned against a bill we do not hold'), ('offer_mismatch', 'Offer applied differs from the rulebook'), ('gst_mismatch', 'Tax charged differs from the dated slab'), ('aged_uncosted', 'Sold before inward, still unpriced'), ('gstin_invalid', "The buyer's GSTIN is not well formed"), ('billed_while_paused', 'Billed while the counter was paused'), ('return_late', 'Taken back after the return window closed'), ('return_uncosted', 'Given back before the books could price it'), ('employee_returns', 'One seller took back an unusual number'), ('tax_version_mismatch', 'Taxed under another tax version'), ('tax_rule_missing', "No tax rule for an item's HSN"), ('invoice_number_missing', 'No number in the new invoice series'), ('invoice_number_problem', 'Invoice number needs checking'), ('override_self_approved', 'Override approved by the cashier'), ('split_while_off', 'Split sale from a store with it off'), ('after_discount_mismatch', 'Discount tax rules differ from switch'), ('till_server_mismatch', 'Till and server differ on the bill'), ('late_credit_note', 'Taken back after the credit-note deadline'), ('return_tax_mismatch', 'Return tax rules differ from the switch'), ('cn_deadline_mismatch', 'Till and server differ on the deadline'), ('bank_share_returned', 'Bank offer part reversed on a return'), ('bank_share_mismatch', 'Till and server differ on the bank part'), ('credit_note_number', 'Credit note number needs checking'), ('no_bill_return_cap', 'Over the no-bill return cap')], max_length=24),
        ),
    ]
