# Generated by Django 5.1.15 on 2026-09-28 12:19

import core.money
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_store_roles'),
        ('masters', '0030_customer_merge_and_numbers'),
        ('offers', '0004_seed_offer_approval_policy'),
        ('sell', '0042_merge_20260928_1558'),
        ('vendors', '0010_bookingline_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlterationJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=32)),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('charge_paise', core.money.MoneyField(default=0)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_mobile', models.CharField(db_index=True, max_length=15)),
                ('work', models.CharField(max_length=500)),
                ('measurements', models.CharField(blank=True, default='', max_length=500)),
                ('tailor', models.CharField(choices=[('in_house', 'In-house'), ('outside', 'Outside')], max_length=8)),
                ('tailor_name', models.CharField(blank=True, default='', max_length=120)),
                ('promised_on', models.DateField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('with_tailor', 'With the tailor'), ('ready', 'Ready'), ('handed_over', 'Handed over'), ('cancelled', 'Cancelled')], default='received', max_length=12)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('customer_told_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=240)),
            ],
            options={
                'db_table': 'sell_alteration_job',
                'ordering': ['promised_on', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BilledRetainedCustody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField()),
                ('purpose', models.CharField(choices=[('alteration', 'Alteration')], max_length=12)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_mobile', models.CharField(max_length=15)),
                ('location', models.CharField(choices=[('store', 'At the store'), ('outside_tailor', 'With an outside tailor')], default='store', max_length=16)),
                ('expected_by', models.DateField()),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('handed_over', 'Handed to the customer'), ('cancelled', 'Given back, work cancelled')], default='', max_length=12)),
            ],
            options={
                'db_table': 'sell_billed_retained_custody',
                'ordering': ['expected_by', 'opened_at'],
            },
        ),
        migrations.AddField(
            model_name='saleline',
            name='kind',
            field=models.CharField(choices=[('goods', 'Goods'), ('alteration', 'Alteration charge')], default='goods', max_length=12),
        ),
        migrations.AlterField(
            model_name='continuityflag',
            name='kind',
            field=models.CharField(choices=[('number_hole', 'Bills missing before this one'), ('cn_unverified', 'Credit note taken without verification'), ('return_orig_missing', 'Returned against a bill we do not hold'), ('offer_mismatch', 'Offer applied differs from the rulebook'), ('gst_mismatch', 'Tax charged differs from the dated slab'), ('aged_uncosted', 'Sold before inward, still unpriced'), ('gstin_invalid', "The buyer's GSTIN is not well formed"), ('billed_while_paused', 'Billed while the counter was paused'), ('return_late', 'Taken back after the return window closed'), ('return_uncosted', 'Given back before the books could price it'), ('employee_returns', 'One seller took back an unusual number'), ('tax_version_mismatch', 'Taxed under another tax version'), ('tax_rule_missing', "No tax rule for an item's HSN"), ('invoice_number_missing', 'No number in the new invoice series'), ('invoice_number_problem', 'Invoice number needs checking'), ('override_self_approved', 'Override approved by the cashier'), ('split_while_off', 'Split sale from a store with it off'), ('after_discount_mismatch', 'Discount tax rules differ from switch'), ('till_server_mismatch', 'Till and server differ on the bill'), ('late_credit_note', 'Taken back after the credit-note deadline'), ('return_tax_mismatch', 'Return tax rules differ from the switch'), ('cn_deadline_mismatch', 'Till and server differ on the deadline'), ('bank_share_returned', 'Bank offer part reversed on a return'), ('bank_share_mismatch', 'Till and server differ on the bank part'), ('credit_note_number', 'Credit note number needs checking'), ('returned_on_job_card', 'Garment on an open job card came back')], max_length=24),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'goods'), models.Q(('direction', 'sale'), ('disc_paise', 0), ('hsn', '9988'), ('kind', 'alteration'), ('qty', 1)), _connector='OR'), name='ck_saleline_alteration_shape'),
        ),
        migrations.AddField(
            model_name='alterationjob',
            name='charge_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alteration_job_charged', to='sell.saleline'),
        ),
        migrations.AddField(
            model_name='alterationjob',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alterationjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alterationjob',
            name='customer_told_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alterationjob',
            name='garment_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alteration_jobs', to='sell.saleline'),
        ),
        migrations.AddField(
            model_name='alterationjob',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='billedretainedcustody',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billedretainedcustody',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billedretainedcustody',
            name='sale_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sell.saleline'),
        ),
        migrations.AddField(
            model_name='billedretainedcustody',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='alterationjob',
            name='custody',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='alteration_job', to='sell.billedretainedcustody'),
        ),
        migrations.AddIndex(
            model_name='billedretainedcustody',
            index=models.Index(fields=['store', 'closed_at'], name='sell_custody_store_open_idx'),
        ),
        migrations.AddConstraint(
            model_name='billedretainedcustody',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='ck_custody_qty'),
        ),
        migrations.AddConstraint(
            model_name='billedretainedcustody',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('outcome', '')), models.Q(('closed_at__isnull', False), models.Q(('outcome', ''), _negated=True)), _connector='OR'), name='ck_custody_closed_iff_outcome'),
        ),
        migrations.AddIndex(
            model_name='alterationjob',
            index=models.Index(fields=['store', 'status'], name='sell_alter_store_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='alterationjob',
            constraint=models.UniqueConstraint(fields=('store', 'ref'), name='uq_alteration_store_ref'),
        ),
        migrations.AddConstraint(
            model_name='alterationjob',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='ck_alteration_qty'),
        ),
        migrations.AddConstraint(
            model_name='alterationjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('charge_line__isnull', True), ('charge_paise', 0)), models.Q(('charge_line__isnull', False), ('charge_paise__gt', 0)), _connector='OR'), name='ck_alteration_charge_iff_line'),
        ),
        migrations.AddConstraint(
            model_name='alterationjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('status__in', ['received', 'with_tailor', 'ready'])), models.Q(('closed_at__isnull', False), ('status__in', ['handed_over', 'cancelled'])), _connector='OR'), name='ck_alteration_closed_iff_ended'),
        ),
        migrations.AddConstraint(
            model_name='alterationjob',
            constraint=models.CheckConstraint(condition=models.Q(('customer_told_at__isnull', True), ('ready_at__isnull', False), _connector='OR'), name='ck_alteration_told_after_ready'),
        ),
    ]
