# Generated by Django 5.1.15 on 2026-09-28 12:15

import core.money
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0043_no_bill_return_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleline',
            name='manual_disc_paise',
            field=core.money.MoneyField(blank=True, null=True),
        ),
    ]
