# Generated by Django 5.1.15 on 2026-09-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0043_alterations'),
        ('sell', '0043_special_orders'),
    ]

    operations = [
    ]
