# Generated by Django 5.1.15 on 2026-09-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0044_merge_0043_alterations_0043_special_orders'),
        ('sell', '0044_saleline_manual_disc_paise'),
    ]

    operations = [
    ]
