# Generated by Django 5.1.15 on 2026-09-28 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0030_customer_merge_and_numbers'),
        ('sell', '0046_alter_continuityflag_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSize',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('brand_key', models.CharField(max_length=120)),
                ('category_key', models.CharField(max_length=120)),
                ('size', models.CharField(max_length=24)),
                ('source', models.CharField(choices=[('bill', 'Learned from a bill'), ('staff', 'Corrected by staff')], max_length=8)),
                ('as_of', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_sizes', to='masters.customer')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sell.sale')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'sell_saved_size',
                'ordering': ['-as_of', '-recorded_at'],
                'indexes': [models.Index(fields=['customer', 'brand_key', 'category_key', 'as_of'], name='sell_saved_size_newest_idx')],
            },
        ),
    ]
