# Generated by Django 5.1.15 on 2026-09-28 14:41

import core.money
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

from core.documents import document_fsm_reverse_sql, document_fsm_sql
from core.ledger import append_only_reverse_sql, append_only_sql


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customer_reservation'),
        ('masters', '0030_customer_merge_and_numbers'),
        ('offers', '0004_seed_offer_approval_policy'),
        ('sell', '0047_saved_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftVoucherMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('issued', 'Sold'), ('used', 'Used on a bill'), ('expired', 'Expired unused')], max_length=8)),
                ('amount_paise', core.money.MoneyField()),
                ('at', models.DateTimeField()),
            ],
            options={
                'db_table': 'sell_gift_voucher_movement',
                'ordering': ['voucher_id', 'at', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='saletender',
            name='mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('credit_note', 'Credit note'), ('bank_offer', 'Bank offer'), ('advance', 'Advance paid earlier'), ('gift_voucher', 'Gift voucher')], max_length=12),
        ),
        migrations.CreateModel(
            name='GiftVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('idempotency_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('docstatus', models.IntegerField(choices=[(0, 'draft'), (1, 'submitted'), (2, 'cancelled')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('code', models.CharField(max_length=12)),
                ('issued_on', models.DateField()),
                ('valid_until', models.DateField()),
                ('value_paise', core.money.MoneyField()),
                ('mode', models.CharField(max_length=8)),
                ('reference', models.CharField(blank=True, default='', max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.voucherseries')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'sell_gift_voucher',
                'ordering': ['-issued_on', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='saletender',
            name='gift_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenders', to='sell.giftvoucher'),
        ),
        migrations.AddConstraint(
            model_name='saletender',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('gift_voucher__isnull', False), ('mode', 'gift_voucher')), models.Q(models.Q(('mode', 'gift_voucher'), _negated=True), ('gift_voucher__isnull', True)), _connector='OR'), name='ck_saletender_voucher_iff_gift_voucher'),
        ),
        migrations.AddField(
            model_name='giftvouchermovement',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giftvouchermovement',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sell.sale'),
        ),
        migrations.AddField(
            model_name='giftvouchermovement',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='giftvouchermovement',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='sell.giftvoucher'),
        ),
        migrations.AddIndex(
            model_name='giftvoucher',
            index=models.Index(fields=['store', 'valid_until'], name='sell_gv_store_until_idx'),
        ),
        migrations.AddConstraint(
            model_name='giftvoucher',
            constraint=models.CheckConstraint(condition=models.Q(('docstatus', 0), ('doc_number__isnull', False), _connector='OR'), name='sell_giftvoucher_posted_has_number'),
        ),
        migrations.AddConstraint(
            model_name='giftvoucher',
            constraint=models.CheckConstraint(condition=models.Q(('docstatus__in', [0, 1, 2])), name='sell_giftvoucher_docstatus_domain'),
        ),
        migrations.AddConstraint(
            model_name='giftvoucher',
            constraint=models.CheckConstraint(condition=models.Q(('value_paise__gt', 0)), name='ck_giftvoucher_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='giftvoucher',
            constraint=models.CheckConstraint(condition=models.Q(('mode__in', ['cash', 'card', 'upi'])), name='ck_giftvoucher_mode'),
        ),
        migrations.AddConstraint(
            model_name='giftvoucher',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__gte', models.F('issued_on'))), name='ck_giftvoucher_valid_after_issue'),
        ),
        migrations.AddConstraint(
            model_name='giftvouchermovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='ck_gvmovement_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='giftvouchermovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'used'), ('sale__isnull', False)), models.Q(('sale__isnull', True), models.Q(('kind', 'used'), _negated=True)), _connector='OR'), name='ck_gvmovement_sale_iff_used'),
        ),
        migrations.AddConstraint(
            model_name='giftvouchermovement',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['issued', 'expired'])), fields=('voucher', 'kind'), name='uq_gvmovement_issued_expired_once'),
        ),
        migrations.AddConstraint(
            model_name='giftvouchermovement',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'used')), fields=('voucher', 'sale'), name='uq_gvmovement_one_use_per_bill'),
        ),
        # A voucher once sold is never edited (the docstatus FSM, like every document).
        migrations.RunSQL(
            sql=document_fsm_sql("sell_gift_voucher"),
            reverse_sql=document_fsm_reverse_sql("sell_gift_voucher"),
        ),
        # Every change to what a voucher holds is its own row, never an edit (ST-POS-4).
        migrations.RunSQL(
            sql=append_only_sql("sell_gift_voucher_movement"),
            reverse_sql=append_only_reverse_sql("sell_gift_voucher_movement"),
        ),
    ]
