# Generated by Django 5.2.17 on 2026-09-29 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0032_so03_brand_identity'),
        ('sell', '0048_gift_vouchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnline',
            name='brand_ref',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand'),
        ),
        migrations.AddField(
            model_name='saleline',
            name='brand_ref',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand'),
        ),
        migrations.AddField(
            model_name='savedsize',
            name='brand_ref',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand'),
        ),
    ]
