# Generated by Django 5.1.15 on 2026-09-28 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0030_customer_merge_and_numbers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('every', models.CharField(choices=[('day', 'Every day'), ('week', 'Every week'), ('month', 'Every month')], max_length=8)),
                ('weekday', models.SmallIntegerField(blank=True, null=True)),
                ('day_of_month', models.SmallIntegerField(blank=True, null=True)),
                ('due_by', models.TimeField(blank=True, null=True)),
                ('items', models.JSONField(default=list)),
                ('judged_after', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('revision', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_checklist_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistMiss',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_on', models.DateField()),
                ('items', models.JSONField(default=list)),
                ('found_at', models.DateTimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='storefront.checklisttemplate')),
            ],
            options={
                'db_table': 'store_checklist_miss',
                'ordering': ['-due_on'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(unique=True)),
                ('item_id', models.CharField(max_length=36)),
                ('item_text', models.CharField(max_length=200)),
                ('due_on', models.DateField()),
                ('ticked_at', models.DateTimeField()),
                ('late', models.BooleanField(default=False)),
                ('photo_key', models.CharField(blank=True, default='', max_length=255)),
                ('photo_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('photo_media_type', models.CharField(blank=True, default='', max_length=40)),
                ('photo_size', models.IntegerField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='storefront.checklisttemplate')),
                ('ticked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'store_checklist_tick',
            },
        ),
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('name',), name='uq_checklist_template_live_name'),
        ),
        migrations.AddIndex(
            model_name='checklistmiss',
            index=models.Index(fields=['store', 'due_on'], name='store_cl_miss_store_day_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklistmiss',
            constraint=models.UniqueConstraint(fields=('store', 'template', 'due_on'), name='uq_checklist_miss_list_day'),
        ),
        migrations.AddIndex(
            model_name='checklisttick',
            index=models.Index(fields=['store', 'due_on'], name='store_cl_tick_store_day_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklisttick',
            constraint=models.UniqueConstraint(fields=('store', 'template', 'item_id', 'due_on'), name='uq_checklist_tick_item_day'),
        ),
    ]
