# Generated by Django 5.1.15 on 2026-06-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32, unique=True)),
                (
                    "vendor_name_raw",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "received_at",
                    models.CharField(
                        choices=[("store", "Store"), ("warehouse", "Warehouse")],
                        default="store",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("sent_to_ho", "Sent to HO (Patna)"),
                            ("inwarded", "Inwarded"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                ("is_direct", models.BooleanField(default=False)),
                (
                    "invoice_number",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=400)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GrnLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("style_code", models.CharField(max_length=80)),
                ("size", models.CharField(blank=True, default="", max_length=24)),
                ("color", models.CharField(blank=True, default="", max_length=40)),
                ("barcode", models.CharField(blank=True, default="", max_length=40)),
                ("received_qty", models.IntegerField(default=0)),
                ("damaged_qty", models.IntegerField(default=0)),
                ("is_variance", models.BooleanField(default=False)),
                ("remark", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
