# Generated by Django 5.1.15 on 2026-06-28 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
        ("inbound", "0001_initial"),
        ("masters", "0001_initial"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="grn",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grns",
                to="vendors.booking",
            ),
        ),
        migrations.AddField(
            model_name="grn",
            name="invoice_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="files.storedfile",
            ),
        ),
        migrations.AddField(
            model_name="grn",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grn",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grns",
                to="masters.store",
            ),
        ),
        migrations.AddField(
            model_name="grn",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grns",
                to="vendors.vendor",
            ),
        ),
        migrations.AddField(
            model_name="grnline",
            name="booking_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vendors.bookingline",
            ),
        ),
        migrations.AddField(
            model_name="grnline",
            name="grn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="inbound.grn",
            ),
        ),
    ]
