# Generated by Django 5.1.15 on 2026-07-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0003_remove_grn_number_grn_doc_number_grn_docstatus_and_more'),
    ]

    # Expand/contract: drop `status` from Django's model state but LEAVE the DB column in
    # place, only relaxing its NOT NULL. Render runs `migrate` in the build step while the
    # *previous* release is still serving, and its serializer still reads `status` —
    # dropping the column there 500s every GRN read until cutover. Keeping a nullable
    # column lets the old code (which sets it) and the new code (which no longer does) both
    # insert during the window. A later cleanup migration drops the column outright once no
    # running code references it.
    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='grn',
                    name='status',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE inbound_grn ALTER COLUMN status DROP NOT NULL;',
                    reverse_sql='ALTER TABLE inbound_grn ALTER COLUMN status SET NOT NULL;',
                ),
            ],
        ),
    ]
