# Generated by Django 5.1.15 on 2026-09-13 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_tenant_authenticationfailure_tenant_and_more'),
        ('core', '0009_voucherseries_tenant_and_more'),
        ('files', '0004_evidencelink_tenant_evidenceobject_actor_and_more'),
        ('inbound', '0006_arrivaldecision_arrivalhead_countergrndraft_and_more'),
        ('masters', '0012_style_productsku_identitypick_skualias_and_more'),
        ('outbound', '0027_countsnapshot_lot_countsnapshot_site_and_more'),
        ('stockledger', '0009_acceptancesession_allocationguard_custodylot_and_more'),
        ('vendors', '0007_goodsbooking_bookingreceiptlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vendors.goodsbooking'),
        ),
        migrations.AddField(
            model_name='arrival',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand'),
        ),
        migrations.AddField(
            model_name='arrival',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='arrival',
            name='invoice_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.evidenceobject'),
        ),
        migrations.AddField(
            model_name='arrival',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='arrival',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='arrival',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='arrivaldecision',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='arrivaldecision',
            name='arrival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='inbound.arrival'),
        ),
        migrations.AddField(
            model_name='arrivaldecision',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='arrivaldecision',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.evidenceobject'),
        ),
        migrations.AddField(
            model_name='arrivaldecision',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='arrivalhead',
            name='arrival',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='head', to='inbound.arrival'),
        ),
        migrations.AddField(
            model_name='arrivalhead',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='countergrndraft',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='counter_grn', to='core.documentidentity'),
        ),
        migrations.AddField(
            model_name='countergrndraft',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='countsession',
            name='arrival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='inbound.arrival'),
        ),
        migrations.AddField(
            model_name='countsession',
            name='counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='countsession',
            name='entry_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='countsession',
            name='grn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.documentidentity'),
        ),
        migrations.AddField(
            model_name='countsession',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='authority_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.configversion'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.documentidentity'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='journal_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stockledger.journalbatch'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='stockledger.custodylot'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='pt_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.draftrevision'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='inbound.disposition'),
        ),
        migrations.AddField(
            model_name='disposition',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='goodsgrn',
            name='arrival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='inbound.arrival'),
        ),
        migrations.AddField(
            model_name='goodsgrn',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vendors.goodsbooking'),
        ),
        migrations.AddField(
            model_name='goodsgrn',
            name='count_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='goods_grn', to='inbound.countsession'),
        ),
        migrations.AddField(
            model_name='goodsgrn',
            name='counter_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counters', to='inbound.goodsgrn'),
        ),
        migrations.AddField(
            model_name='goodsgrn',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='goods_grn', to='core.documentidentity'),
        ),
        migrations.AddField(
            model_name='goodsgrn',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='countergrndraft',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counter_drafts', to='inbound.goodsgrn'),
        ),
        migrations.AddField(
            model_name='invoiceclaimversion',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='invoiceclaimversion',
            name='arrival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='inbound.arrival'),
        ),
        migrations.AddField(
            model_name='invoiceclaimversion',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='invoiceclaimversion',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.evidenceobject'),
        ),
        migrations.AddField(
            model_name='invoiceclaimversion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='scanobservation',
            name='acceptance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='stockledger.acceptancesession'),
        ),
        migrations.AddField(
            model_name='scanobservation',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='scanobservation',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='scanobservation',
            name='correction_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='inbound.scanobservation'),
        ),
        migrations.AddField(
            model_name='scanobservation',
            name='count_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='inbound.countsession'),
        ),
        migrations.AddField(
            model_name='scanobservation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.location'),
        ),
        migrations.AddField(
            model_name='scanobservation',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='scanobservation',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.productsku'),
        ),
        migrations.AddField(
            model_name='scanobservation',
            name='stocktake_pass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='outbound.goodscountpass'),
        ),
        migrations.AddField(
            model_name='scanobservation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddIndex(
            model_name='arrival',
            index=models.Index(fields=['site', 'actual_arrival_at'], name='inbound_arr_site_id_d63449_idx'),
        ),
        migrations.AddConstraint(
            model_name='arrival',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='inbound_arrival_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='arrival',
            constraint=models.CheckConstraint(condition=models.Q(('actual_arrival_at__lte', models.F('recorded_at'))), name='ck_arrival_not_in_future'),
        ),
        migrations.AddIndex(
            model_name='arrivaldecision',
            index=models.Index(fields=['arrival', 'recorded_at'], name='inbound_arr_arrival_981014_idx'),
        ),
        migrations.AddConstraint(
            model_name='arrivaldecision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='inbound_arrivaldecision_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='arrivaldecision',
            constraint=models.UniqueConstraint(fields=('arrival', 'kind'), name='uq_arrivaldecision_kind'),
        ),
        migrations.AddIndex(
            model_name='countsession',
            index=models.Index(fields=['arrival', 'state'], name='inbound_cou_arrival_39be79_idx'),
        ),
        migrations.AddIndex(
            model_name='disposition',
            index=models.Index(fields=['source_line_key', 'recorded_at'], name='inbound_dis_source__070eb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='disposition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='inbound_disposition_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='disposition',
            constraint=models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='ck_disposition_qty'),
        ),
        migrations.AddConstraint(
            model_name='disposition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lot__isnull', True), ('portion__isnull', True)), models.Q(('lot__isnull', False), ('portion__isnull', False)), _connector='OR'), name='ck_disposition_lot_portion'),
        ),
        migrations.AddConstraint(
            model_name='invoiceclaimversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='inbound_invoiceclaimversion_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='invoiceclaimversion',
            constraint=models.UniqueConstraint(fields=('arrival', 'revision'), name='uq_invoiceclaim_revision'),
        ),
        migrations.AddIndex(
            model_name='scanobservation',
            index=models.Index(fields=['count_session', 'recorded_at'], name='inbound_sca_count_s_d6a658_idx'),
        ),
        migrations.AddConstraint(
            model_name='scanobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='inbound_scanobservation_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='scanobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('acceptance__isnull', True), ('count_session__isnull', False), ('stocktake_pass__isnull', True)), models.Q(('acceptance__isnull', True), ('count_session__isnull', True), ('stocktake_pass__isnull', False)), models.Q(('acceptance__isnull', False), ('count_session__isnull', True), ('stocktake_pass__isnull', True)), _connector='OR'), name='ck_scanobservation_one_session'),
        ),
        migrations.AddConstraint(
            model_name='scanobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('correction_of__isnull', True), ('qty__gte', 1), ('qty__lte', 999999)), models.Q(('correction_of__isnull', False), ('qty__gte', -999999), ('qty__lte', 999999)), _connector='OR'), name='ck_scanobservation_qty'),
        ),
        migrations.AddConstraint(
            model_name='scanobservation',
            constraint=models.UniqueConstraint(condition=models.Q(('count_session__isnull', False)), fields=('count_session', 'scan_key'), name='uq_scan_count_session'),
        ),
        migrations.AddConstraint(
            model_name='scanobservation',
            constraint=models.UniqueConstraint(condition=models.Q(('stocktake_pass__isnull', False)), fields=('stocktake_pass', 'scan_key'), name='uq_scan_count_pass'),
        ),
        migrations.AddConstraint(
            model_name='scanobservation',
            constraint=models.UniqueConstraint(condition=models.Q(('acceptance__isnull', False)), fields=('acceptance', 'scan_key'), name='uq_scan_acceptance'),
        ),
    ]
