# Generated by Django 5.1.15 on 2026-09-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0007_arrival_booking_arrival_brand_arrival_command_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanobservation',
            name='alias_context',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
