# Generated by Django 5.1.15 on 2026-09-20 06:38

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_must_change_password'),
        ('core', '0010_documentidentity_site_unless_booking'),
        ('inbound', '0008_observation_alias_context'),
        ('masters', '0020_sbu_revision_and_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountHandover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('reason_code', models.CharField(max_length=60)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('count_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers', to='inbound.countsession')),
                ('from_human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
                ('to_human', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['count_session', 'recorded_at'], name='inbound_cou_count_s_7fdb70_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='inbound_counthandover_one_actor'), models.CheckConstraint(condition=models.Q(('from_human', models.F('to_human')), _negated=True), name='ck_counthandover_to_another_person')],
            },
        ),
    ]
