# Generated by Django 5.1.15 on 2026-09-20 07:27

import django.db.models.deletion
import django.db.models.functions.datetime
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_must_change_password'),
        ('core', '0010_documentidentity_site_unless_booking'),
        ('files', '0004_evidencelink_tenant_evidenceobject_actor_and_more'),
        ('inbound', '0009_counthandover'),
        ('masters', '0020_sbu_revision_and_history'),
        ('vendors', '0009_enforce_vendor_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateArrivalAcknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('warning_hash', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=500)),
                ('matched_arrivals', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='arrival',
            index=models.Index(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('invoice_number')), models.F('vendor'), name='ix_arrival_invoice_match'),
        ),
        migrations.AddField(
            model_name='duplicatearrivalacknowledgement',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='duplicatearrivalacknowledgement',
            name='arrival',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_acknowledgement', to='inbound.arrival'),
        ),
        migrations.AddField(
            model_name='duplicatearrivalacknowledgement',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='duplicatearrivalacknowledgement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddIndex(
            model_name='duplicatearrivalacknowledgement',
            index=models.Index(fields=['warning_hash'], name='inbound_dup_warning_f5f252_idx'),
        ),
        migrations.AddConstraint(
            model_name='duplicatearrivalacknowledgement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='inbound_duplicatearrivalacknowledgement_one_actor'),
        ),
    ]
