# Generated by Django 5.1.15 on 2026-09-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0011_delete_legacy_grn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposition',
            name='kind',
            field=models.CharField(choices=[('accept_shortage', 'Accept Shortage'), ('hold_excess', 'Hold Excess'), ('accept_excess', 'Accept Excess'), ('hold_damage', 'Hold Damage'), ('value_damage', 'Value Damage'), ('return', 'Return'), ('dispose', 'Dispose'), ('resolve_identity', 'Resolve Identity'), ('accept_wrong', 'Accept Wrong')], max_length=20),
        ),
    ]
