# Generated by Django 5.1.15 on 2026-09-26 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_merge_store_roles"),
        ("core", "0011_alter_documentidentity_purpose"),
        ("inbound", "0012_disposition_accept_wrong"),
        ("masters", "0022_crosswalk_attribute_kinds"),
        ("outbound", "0041_transfer_excess_corrective"),
        ("stockledger", "0020_disposal_posting_kind"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="scanobservation",
            name="ck_scanobservation_one_session",
        ),
        migrations.AddField(
            model_name="scanobservation",
            name="transfer_dispatch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observations",
                to="outbound.transferdispatch",
            ),
        ),
        migrations.AddConstraint(
            model_name="scanobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("acceptance__isnull", True),
                        ("count_session__isnull", False),
                        ("stocktake_pass__isnull", True),
                        ("transfer_dispatch__isnull", True),
                    ),
                    models.Q(
                        ("acceptance__isnull", True),
                        ("count_session__isnull", True),
                        ("stocktake_pass__isnull", False),
                        ("transfer_dispatch__isnull", True),
                    ),
                    models.Q(
                        ("acceptance__isnull", False),
                        ("count_session__isnull", True),
                        ("stocktake_pass__isnull", True),
                        ("transfer_dispatch__isnull", True),
                    ),
                    models.Q(
                        ("acceptance__isnull", True),
                        ("count_session__isnull", True),
                        ("stocktake_pass__isnull", True),
                        ("transfer_dispatch__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_scanobservation_one_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="scanobservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("transfer_dispatch__isnull", False)),
                fields=("transfer_dispatch", "scan_key"),
                name="uq_scan_transfer_dispatch",
            ),
        ),
    ]
