# Generated by Django 5.1.15 on 2026-09-27 23:06

import core.goods_base
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from core.dbroles import tenant_rls_sql


#: Both tables behind the tenant wall, an issued note final, nothing deleted
#: (store operations PRD §6 principle 3: an issued document is never edited).
GUARDS = f"""
{tenant_rls_sql("inbound_debit_note")}
{tenant_rls_sql("inbound_debit_note_source")}
CREATE OR REPLACE FUNCTION kdps_debit_note_final() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'debit notes are never deleted (%)', TG_TABLE_NAME;
    END IF;
    IF TG_TABLE_NAME = 'inbound_debit_note_source' THEN
        RAISE EXCEPTION 'which shortage a debit note line came from is never changed';
    END IF;
    IF OLD.status = 'issued' THEN
        RAISE EXCEPTION 'an issued debit note is never edited';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER inbound_debit_note_final BEFORE UPDATE OR DELETE ON inbound_debit_note
    FOR EACH ROW EXECUTE FUNCTION kdps_debit_note_final();
CREATE TRIGGER inbound_debit_note_source_final BEFORE UPDATE OR DELETE
    ON inbound_debit_note_source FOR EACH ROW EXECUTE FUNCTION kdps_debit_note_final();
"""

UNGUARD = """
DROP TRIGGER IF EXISTS inbound_debit_note_final ON inbound_debit_note;
DROP TRIGGER IF EXISTS inbound_debit_note_source_final ON inbound_debit_note_source;
DROP FUNCTION IF EXISTS kdps_debit_note_final();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("inbound", "0013_transfer_excess_observation"),
        ("masters", "0028_season_ended_on"),
        ("vendors", "0010_bookingline_cost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DebitNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_number", models.CharField(blank=True, default="", max_length=80)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                ("lines", models.JSONField(default=list)),
                ("taxable_paise", models.BigIntegerField(default=0)),
                ("tax_paise", models.BigIntegerField(default=0)),
                ("total_paise", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("review_note", models.CharField(blank=True, default="", max_length=240)),
                ("approval_hash", models.CharField(blank=True, default="", max_length=64)),
                ("number", models.CharField(blank=True, max_length=16, null=True)),
                ("issued_on", models.DateField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, default="", max_length=240)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.brand",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inbound.invoiceclaimversion",
                    ),
                ),
                (
                    "grn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inbound.goodsgrn",
                    ),
                ),
                (
                    "gstin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.gstin",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.store",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_default=core.goods_base.CurrentTenant(),
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.tenant",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "inbound_debit_note",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DebitNoteSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "disposition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inbound.disposition",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sources",
                        to="inbound.debitnote",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_default=core.goods_base.CurrentTenant(),
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "inbound_debit_note_source",
            },
        ),
        migrations.AddIndex(
            model_name="debitnote",
            index=models.Index(fields=["grn", "status"], name="inbound_deb_grn_id_c5a34b_idx"),
        ),
        migrations.AddIndex(
            model_name="debitnote",
            index=models.Index(fields=["site", "status"], name="inbound_deb_site_id_6bcc79_idx"),
        ),
        migrations.AddConstraint(
            model_name="debitnote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number__isnull", False)),
                fields=("tenant", "number"),
                name="uq_debitnote_tenant_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="debitnote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("issued_on__isnull", False),
                        ("number__isnull", False),
                        ("status", "issued"),
                    ),
                    models.Q(
                        models.Q(("status", "issued"), _negated=True),
                        ("issued_on__isnull", True),
                        ("number__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_debitnote_number_when_issued",
            ),
        ),
        migrations.AddConstraint(
            model_name="debitnote",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "cancelled"), _negated=True),
                    models.Q(("cancel_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="ck_debitnote_cancel_reason",
            ),
        ),
        migrations.RunSQL(GUARDS, UNGUARD),
    ]
