# Generated by Django 5.1.15 on 2026-09-28 11:14

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_store_roles'),
        ('core', '0012_customer_reservation'),
        ('inbound', '0014_debit_notes'),
        ('masters', '0030_customer_merge_and_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandDispatchDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('dispatch_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_dates', to='inbound.arrival')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['arrival', 'recorded_at'], name='inbound_bra_arrival_6d452e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='inbound_branddispatchdate_one_actor')],
            },
        ),
        migrations.CreateModel(
            name='SorBrandInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('invoice_number', models.CharField(max_length=80)),
                ('invoice_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sor_invoices', to='inbound.arrival')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['arrival', 'recorded_at'], name='inbound_sor_arrival_ec05c4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='inbound_sorbrandinvoice_one_actor')],
            },
        ),
    ]
