class FileContentWithMimeType:
    def __init__(self, *, file_path: str, mime_type: str) -> None: ...

class UserMessage:
    def __init__(
        self, *, text: str, file_contents: list[FileContentWithMimeType]
    ) -> None: ...

class LlmChat:
    def __init__(self, *, api_key: str, session_id: str, system_message: str) -> None: ...
    def with_model(self, provider: str, model: str) -> LlmChat: ...
    async def send_message(self, message: UserMessage) -> str: ...
