# Generated by Django 5.1.15 on 2026-06-28 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "ownership",
                    models.CharField(
                        choices=[
                            ("owned", "KDPS-owned"),
                            ("brand_owned", "Brand-owned"),
                        ],
                        default="owned",
                        max_length=12,
                    ),
                ),
                (
                    "return_terms",
                    models.CharField(
                        choices=[
                            ("none", "No returns"),
                            ("capped", "Capped allowance"),
                            ("uncapped", "Uncapped"),
                            ("rolling", "Uncapped + rolling top-up"),
                        ],
                        default="none",
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GstSlab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Apparel", max_length=80)),
                ("hsn_prefix", models.CharField(blank=True, default="", max_length=8)),
                ("threshold_paise", models.BigIntegerField(default=250000)),
                (
                    "rate_below",
                    models.DecimalField(decimal_places=2, default=5, max_digits=5),
                ),
                (
                    "rate_above",
                    models.DecimalField(decimal_places=2, default=18, max_digits=5),
                ),
                ("effective_from", models.DateField()),
            ],
            options={
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="LegalEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=24, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("pan", models.CharField(blank=True, default="", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "legal entities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=24, unique=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("eoss", "EOSS"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=8,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Gstin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gstin", models.CharField(max_length=15, unique=True)),
                ("state_code", models.CharField(max_length=2)),
                ("state_name", models.CharField(max_length=40)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "legal_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gstins",
                        to="masters.legalentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "GSTIN",
                "ordering": ["state_name"],
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "store_type",
                    models.CharField(
                        choices=[("store", "Store"), ("warehouse", "Warehouse")],
                        default="store",
                        max_length=12,
                    ),
                ),
                ("city", models.CharField(blank=True, default="", max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "gstin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stores",
                        to="masters.gstin",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
