# Generated by Django 5.1.15 on 2026-07-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_phasef_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(blank=True, default='', max_length=160, unique=True)),
                ('margin_pct', models.DecimalField(decimal_places=2, default=33, max_digits=5)),
                ('band_min_pct', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('band_max_pct', models.DecimalField(decimal_places=2, default=35, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['item'],
            },
        ),
    ]
