# Generated by Django 5.1.15 on 2026-07-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_seed_default_category_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='return_cap_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text="The Correction goods-return allowance, as a percentage of the brand's delivered value (the 10 of 25-18-10, stretchable to 12/15). Read only for Correction brands — the other three models have no cap.", max_digits=5),
        ),
        migrations.AddField(
            model_name='brand',
            name='return_window_days',
            field=models.IntegerField(default=0, help_text='How long after a piece arrives the brand will still take it back (60–120 days, negotiated per brand). 0 means nobody has agreed one yet — the return screen says so rather than guessing a deadline.'),
        ),
    ]
