# Generated by Django 5.1.15 on 2026-07-30 04:34

import core.money
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_brand_return_terms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(help_text='The month, as its first day (2026-08-01 = August 2026).')),
                ('target_paise', core.money.MoneyField(help_text='Net sales asked of this store for the month, in integer paise. Nought is a real answer - a store shut for the month is not an unset target.')),
                ('set_by', models.ForeignKey(blank=True, help_text='Who last set this number. The only route from a Dashboard figure back to the person who chose it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_targets_set', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='masters.store')),
            ],
            options={
                'ordering': ['store__code', 'month'],
                'constraints': [models.UniqueConstraint(fields=('store', 'month'), name='uq_storetarget_store_month'), models.CheckConstraint(condition=models.Q(('month__day', 1)), name='ck_storetarget_month_is_first_of_month'), models.CheckConstraint(condition=models.Q(('target_paise__gte', 0)), name='ck_storetarget_target_not_negative')],
            },
        ),
    ]
