# Generated by Django 5.1.15 on 2026-08-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_dataset_watermarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile', models.CharField(help_text='Digits only, normalised at the accept boundary.', max_length=15, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('gstin', models.CharField(blank=True, default='', help_text='Normalised uppercase.', max_length=15)),
            ],
            options={
                'ordering': ['mobile'],
                'indexes': [models.Index(fields=['updated_at'], name='masters_customer_synced_idx')],
            },
        ),
    ]
