# Generated by Django 5.1.15 on 2026-08-03 16:36

import core.money
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0008_customer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("barcode", models.CharField(db_index=True, max_length=64)),
                ("from_paise", core.money.MoneyField(blank=True, null=True)),
                ("to_paise", core.money.MoneyField()),
                ("effective_from", models.DateField()),
                (
                    "source",
                    models.CharField(
                        choices=[("pt", "PT posting"), ("reprice", "Re-ticket")],
                        max_length=12,
                    ),
                ),
                ("doc_number", models.CharField(blank=True, default="", max_length=32)),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_changes",
                        to="masters.sku",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from", "-id"],
                "indexes": [
                    models.Index(
                        fields=["barcode", "effective_from"],
                        name="masters_price_day_idx",
                    )
                ],
            },
        ),
    ]
