# Generated by Django 5.1.15 on 2026-08-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0009_pricechange"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="is_partner",
            field=models.BooleanField(
                default=False,
                help_text="A franchisee/partner store rather than a KDPS-owned one. Stock transferred here is billed to the partner at Purchase Price — see `outbound.BillingPolicy` for whether that also posts to the ledger.",
            ),
        ),
    ]
