# Generated by Django 5.1.15 on 2026-09-13 14:50

import django.contrib.postgres.constraints
import django.db.models.deletion
import django.db.models.functions.datetime
import masters.goods_models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_authenticationfailure_humanidentity_rolegrant_and_more'),
        ('approvals', '0009_approvaldecision_approvalrequest_actiondraft'),
        ('core', '0008_auditevent_chainhead_commandattempt_commandkey_and_more'),
        ('files', '0003_evidenceobject_uploadintent_evidencelink'),
        ('masters', '0010_store_is_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('kind', models.CharField(max_length=60)),
                ('scope', models.JSONField()),
                ('scope_key', models.CharField(max_length=500)),
                ('revision', models.IntegerField(default=1)),
                ('payload', models.JSONField()),
                ('effective_from', models.DateTimeField()),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=60)),
                ('version', models.IntegerField()),
                ('scope', models.JSONField()),
                ('scope_key', models.CharField(max_length=500)),
                ('payload', models.JSONField()),
                ('effective_from', models.DateTimeField()),
                ('source_revision', models.IntegerField()),
                ('source_hash', models.CharField(max_length=64)),
                ('backdate_impact', models.JSONField(default=list)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='masters.configdraft')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteCapabilityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('operation', models.CharField(choices=[('opening_setup', 'Opening Setup'), ('goods', 'Goods'), ('sell', 'Sell'), ('non_trading', 'Non Trading'), ('closing', 'Closing'), ('closed', 'Closed')], max_length=20)),
                ('outcome', models.CharField(choices=[('approved', 'Approved'), ('revoked', 'Revoked')], max_length=10)),
                ('site_revision', models.IntegerField()),
                ('checks', models.JSONField()),
                ('reason_code', models.CharField(max_length=60)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.evidenceobject')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('deployment_key', models.UUIDField(unique=True)),
                ('timezone', models.CharField(max_length=60)),
                ('currency', models.CharField(max_length=3)),
                ('locale', models.CharField(max_length=20)),
                ('synthetic', models.BooleanField(default=False)),
                ('revision', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('business_profile_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.configversion')),
            ],
        ),
        migrations.CreateModel(
            name='SiteGuard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('opening_setup_ready', models.BooleanField(default=False)),
                ('goods_ready', models.BooleanField(default=False)),
                ('sell_ready', models.BooleanField(default=False)),
                ('non_trading_confirmed', models.BooleanField(default=False)),
                ('lifecycle', models.CharField(choices=[('planned', 'Planned'), ('opening', 'Opening'), ('active', 'Active'), ('closing', 'Closing'), ('closed', 'Closed')], default='planned', max_length=10)),
                ('stock_contract', models.CharField(choices=[('legacy', 'Legacy'), ('goods_v1', 'Goods V1')], default='legacy', max_length=10)),
                ('freeze_id', models.UUIDField(blank=True, null=True)),
                ('closure_date', models.DateField(blank=True, null=True)),
                ('revision', models.IntegerField(default=1)),
                ('capability_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.sitecapabilityevent')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='goods_guard', to='masters.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sitecapabilityevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.CreateModel(
            name='Sbu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('code', models.CharField(max_length=40)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MasterVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('tenant', 'Tenant'), ('entity', 'Entity'), ('registration', 'Registration'), ('site', 'Site'), ('vendor', 'Vendor'), ('brand', 'Brand'), ('subbrand', 'Subbrand'), ('season', 'Season'), ('location', 'Location'), ('staff', 'Staff'), ('style', 'Style'), ('sku', 'Sku'), ('alias', 'Alias'), ('crosswalk', 'Crosswalk'), ('user', 'User'), ('role', 'Role')], max_length=20)),
                ('target_key', models.CharField(max_length=100)),
                ('revision', models.IntegerField()),
                ('payload', models.JSONField()),
                ('retired', models.BooleanField(default=False)),
                ('reason_code', models.CharField(blank=True, max_length=60, null=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='approvals.approvalrequest')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('floor', 'Floor'), ('backstore', 'Backstore'), ('receiving', 'Receiving'), ('quarantine', 'Quarantine'), ('excess_hold', 'Excess Hold'), ('rtv_hold', 'Rtv Hold'), ('transit_out', 'Transit Out'), ('custody', 'Custody'), ('zone', 'Zone'), ('bin', 'Bin'), ('fixture', 'Fixture')], max_length=20)),
                ('system', models.BooleanField(default=False)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.IntegerField(default=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='masters.location')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('active_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.masterversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='EffectiveVersionPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('target_kind', models.CharField(choices=[('master', 'Master'), ('configuration', 'Configuration'), ('assignment', 'Assignment'), ('grant', 'Grant'), ('alias', 'Alias')], max_length=20)),
                ('target_id', models.UUIDField()),
                ('scope_key', models.CharField(max_length=500)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='configversion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='configdraft',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.CreateModel(
            name='AliasRangeCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('next_value', models.BigIntegerField()),
                ('range_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.configversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='sitecapabilityevent',
            index=models.Index(fields=['site', 'operation', 'recorded_at'], name='masters_sit_site_id_e98e8e_idx'),
        ),
        migrations.AddConstraint(
            model_name='sitecapabilityevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='masters_sitecapabilityevent_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='sbu',
            constraint=models.UniqueConstraint(condition=models.Q(('brand__isnull', False)), fields=('site', 'brand'), name='uq_sbu_site_brand'),
        ),
        migrations.AddConstraint(
            model_name='sbu',
            constraint=models.UniqueConstraint(condition=models.Q(('brand__isnull', True)), fields=('site',), name='uq_sbu_site_fallback'),
        ),
        migrations.AddConstraint(
            model_name='sbu',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_sbu_code'),
        ),
        migrations.AddIndex(
            model_name='masterversion',
            index=models.Index(fields=['kind', 'target_key', 'effective_from'], name='masters_mas_kind_f7210e_idx'),
        ),
        migrations.AddConstraint(
            model_name='masterversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='masters_masterversion_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='masterversion',
            constraint=models.UniqueConstraint(fields=('tenant', 'kind', 'target_key', 'revision'), name='uq_masterversion_revision'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='uq_location_site_name'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('system', True)), fields=('site', 'kind'), name='uq_location_system_kind'),
        ),
        migrations.AddConstraint(
            model_name='effectiveversionperiod',
            constraint=models.UniqueConstraint(fields=('tenant', 'target_kind', 'target_id'), name='uq_effectiveperiod_target'),
        ),
        migrations.AddConstraint(
            model_name='effectiveversionperiod',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='ck_effectiveperiod_order'),
        ),
        migrations.AddConstraint(
            model_name='effectiveversionperiod',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('tenant', '='), ('target_kind', '='), ('scope_key', '='), (masters.goods_models.TsTzRange('effective_from', 'effective_to'), '&&')], name='ex_effectiveperiod_overlap'),
        ),
        migrations.AddIndex(
            model_name='configversion',
            index=models.Index(fields=['kind', 'effective_from'], name='masters_con_kind_2c75e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='configversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='masters_configversion_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='configversion',
            constraint=models.UniqueConstraint(fields=('tenant', 'kind', 'scope_key', 'version'), name='uq_configversion_version'),
        ),
        migrations.AddIndex(
            model_name='configdraft',
            index=models.Index(fields=['kind', 'state'], name='masters_con_kind_7df3d2_idx'),
        ),
    ]
