# Generated by Django 5.1.15 on 2026-09-13 15:25

import django.contrib.postgres.constraints
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.datetime
import masters.goods_models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_tenant_authenticationfailure_tenant_and_more'),
        ('core', '0009_voucherseries_tenant_and_more'),
        ('inbound', '0006_arrivaldecision_arrivalhead_countergrndraft_and_more'),
        ('masters', '0011_configdraft_configversion_sitecapabilityevent_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('style_code', models.CharField(max_length=120)),
                ('profile_family', models.CharField(max_length=60)),
                ('attrs', models.JSONField(default=list)),
                ('governance_state', models.CharField(choices=[('pending', 'Pending'), ('effective', 'Effective'), ('retired', 'Retired')], max_length=10)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.IntegerField(default=1)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand')),
                ('originating_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.draftrevision')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSku',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('identity_key', models.CharField(max_length=64)),
                ('attrs', models.JSONField(default=list)),
                ('governance_state', models.CharField(choices=[('pending', 'Pending'), ('effective', 'Effective'), ('retired', 'Retired')], max_length=10)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.IntegerField(default=1)),
                ('identity_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.configversion')),
                ('originating_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.draftrevision')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='masters.style')),
            ],
        ),
        migrations.CreateModel(
            name='IdentityPick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=128)),
                ('candidates', models.JSONField()),
                ('candidate_hash', models.CharField(max_length=64)),
                ('context', models.JSONField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('scan_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inbound.scanobservation')),
                ('subject_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.draftrevision')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
                ('chosen_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.productsku')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['chosen_sku', 'recorded_at'], name='masters_ide_chosen__76b04c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='masters_identitypick_one_actor'), models.CheckConstraint(condition=models.Q(models.Q(('scan_event__isnull', True), ('subject_revision__isnull', False)), models.Q(('scan_event__isnull', False), ('subject_revision__isnull', True)), _connector='OR'), name='ck_identitypick_one_subject')],
            },
        ),
        migrations.CreateModel(
            name='SkuAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('issuer_key', models.CharField(max_length=100)),
                ('alias_type', models.CharField(choices=[('barcode', 'Barcode'), ('vendor_code', 'Vendor Code'), ('generated', 'Generated')], max_length=12)),
                ('value', models.CharField(max_length=128)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('governance_state', models.CharField(choices=[('pending', 'Pending'), ('effective', 'Effective'), ('retired', 'Retired')], max_length=10)),
                ('revision', models.IntegerField(default=1)),
                ('config_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.configversion')),
                ('originating_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.draftrevision')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='masters.productsku')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'issuer_key', 'alias_type', 'value', 'effective_from'], name='masters_sku_tenant__e78ff0_idx')],
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('governance_state', 'retired'), _negated=True), expressions=[('tenant', '='), ('sku', '='), ('issuer_key', '='), ('alias_type', '='), ('value', '='), (django.db.models.functions.comparison.Coalesce('site', models.Value(0)), '='), (masters.goods_models.TsTzRange('effective_from', 'effective_to'), '&&')], name='ex_skualias_same_sku_overlap')],
            },
        ),
        migrations.CreateModel(
            name='SourceCrosswalk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('kind', models.CharField(choices=[('vendor', 'Vendor'), ('brand', 'Brand'), ('subbrand', 'Subbrand')], max_length=10)),
                ('issuer_key', models.CharField(max_length=100)),
                ('source_key', models.CharField(max_length=240)),
                ('target_key', models.CharField(max_length=100)),
                ('governance_state', models.CharField(choices=[('pending', 'Pending'), ('effective', 'Effective'), ('retired', 'Retired')], default='effective', max_length=10)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.IntegerField(default=1)),
                ('config_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.configversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'issuer_key', 'source_key'], name='masters_sou_kind_fcb845_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'kind', 'issuer_key', 'source_key', 'config_version'), name='uq_sourcecrosswalk')],
            },
        ),
        migrations.AddConstraint(
            model_name='style',
            constraint=models.UniqueConstraint(fields=('tenant', 'brand', 'profile_family', 'style_code'), name='uq_style_code'),
        ),
        migrations.AddIndex(
            model_name='productsku',
            index=models.Index(fields=['style'], name='masters_pro_style_i_00d58b_idx'),
        ),
        migrations.AddConstraint(
            model_name='productsku',
            constraint=models.UniqueConstraint(fields=('tenant', 'identity_key'), name='uq_productsku_identity'),
        ),
    ]
