# Generated by Django 5.1.15 on 2026-09-14 06:33

import django.contrib.postgres.constraints
import django.db.models.deletion
import masters.goods_models
from django.db import migrations, models

# Every approved configuration version gets its effective-period row, so the one
# resolver reads the same period shape for old and new versions. An existing
# version keeps its own start, stays open-ended and gets a key of its own: it
# cannot collide with another row here, and overlapping old versions still fail
# closed when the resolver finds more than one match.
BACKFILL_PERIODS = """
INSERT INTO masters_effectiveversionperiod
    (id, tenant_id, created_at, target_kind, target_id, scope_key, effective_from)
SELECT gen_random_uuid(), v.tenant_id, now(), 'configuration', v.id,
       'version:' || v.id::text, v.effective_from
FROM masters_configversion v
WHERE NOT EXISTS (
    SELECT 1 FROM masters_effectiveversionperiod p
    WHERE p.target_kind = 'configuration' AND p.target_id = v.id
)
"""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_enforce_role_tenant'),
        ('masters', '0015_enforce_inherited_master_tenant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='effectiveversionperiod',
            name='ex_effectiveperiod_overlap',
        ),
        migrations.AddField(
            model_name='configdraft',
            name='effective_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='effectiveversionperiod',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='effectiveversionperiod',
            name='withdrawn_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='effectiveversionperiod',
            name='withdrawn_reason',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddConstraint(
            model_name='effectiveversionperiod',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('withdrawn_at__isnull', True)), expressions=[('tenant', '='), ('target_kind', '='), ('scope_key', '='), (masters.goods_models.TsTzRange('effective_from', 'effective_to'), '&&')], name='ex_effectiveperiod_overlap'),
        ),
        migrations.RunSQL(BACKFILL_PERIODS, migrations.RunSQL.noop),
    ]
