# Generated by Django 5.1.15 on 2026-09-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masters", "0017_end_backfilled_config_periods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="kind",
            field=models.CharField(
                choices=[
                    ("floor", "Floor"),
                    ("backstore", "Backstore"),
                    ("receiving", "Receiving"),
                    ("quarantine", "Quarantine"),
                    ("excess_hold", "Excess Hold"),
                    ("rtv_hold", "Rtv Hold"),
                    ("transit_out", "Transit Out"),
                    ("custody", "Custody"),
                    ("zone", "Zone"),
                    ("rack", "Rack"),
                    ("bin", "Bin"),
                    ("fixture", "Fixture"),
                ],
                max_length=20,
            ),
        ),
    ]
