# Generated by Django 5.1.15 on 2026-09-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masters", "0019_backfill_custody_system_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="sbu",
            name="revision",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="masterversion",
            name="kind",
            field=models.CharField(
                choices=[
                    ("tenant", "Tenant"),
                    ("entity", "Entity"),
                    ("registration", "Registration"),
                    ("site", "Site"),
                    ("vendor", "Vendor"),
                    ("brand", "Brand"),
                    ("subbrand", "Subbrand"),
                    ("season", "Season"),
                    ("location", "Location"),
                    ("sbu", "Sbu"),
                    ("staff", "Staff"),
                    ("style", "Style"),
                    ("sku", "Sku"),
                    ("alias", "Alias"),
                    ("crosswalk", "Crosswalk"),
                    ("user", "User"),
                    ("role", "Role"),
                ],
                max_length=20,
            ),
        ),
    ]
