# Generated by Django 5.1.15 on 2026-09-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0020_sbu_revision_and_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='historical_unknown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(condition=models.Q(('historical_unknown', True)), fields=('historical_unknown',), name='uq_season_one_historical_unknown'),
        ),
    ]
