# Generated by Django 5.1.15 on 2026-09-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0021_season_historical_unknown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecrosswalk',
            name='kind',
            field=models.CharField(max_length=60),
        ),
    ]
