# Generated by Django 5.1.15 on 2026-09-26 21:14

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0022_crosswalk_attribute_kinds'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFeatureSwitch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('feature_key', models.CharField(max_length=60)),
                ('enabled', models.BooleanField()),
                ('mode', models.CharField(choices=[('manual', 'Manual'), ('connected', 'Connected')], default='manual', max_length=12)),
                ('revision', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'site', 'feature_key'), name='uq_storefeatureswitch_site_key')],
            },
        ),
    ]
