# Generated by Django 5.1.15 on 2026-09-26 22:26

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_merge_store_roles"),
        ("masters", "0023_store_feature_switch"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxSettingVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("version", models.PositiveIntegerField()),
                ("applies_from", models.DateField()),
                ("rules", models.JSONField(default=list)),
                ("unmatched_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("options", models.JSONField(blank=True, default=dict)),
                ("note", models.CharField(max_length=240)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.humanidentity",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "version"), name="uq_taxsettingversion_number"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 2)),
                        name="ck_taxsettingversion_after_slab_table",
                    ),
                ],
            },
        ),
    ]
