# Generated by Django 5.1.15 on 2026-09-26 23:24

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0024_taxsettingversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPrefix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('code', models.CharField(max_length=3)),
                ('revision', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField()),
                ('gstin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.gstin')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSeriesCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('series', models.CharField(choices=[('INV', 'Tax invoice'), ('CN', 'Credit note'), ('RV', 'Receipt voucher'), ('GV', 'Gift voucher'), ('DC', 'Delivery challan'), ('DN', 'Debit note')], max_length=3)),
                ('fy', models.CharField(max_length=5)),
                ('next_n', models.BigIntegerField(default=1)),
                ('prefix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counters', to='masters.documentprefix')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='IssuedDocumentNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('number', models.CharField(max_length=16)),
                ('series', models.CharField(choices=[('INV', 'Tax invoice'), ('CN', 'Credit note'), ('RV', 'Receipt voucher'), ('GV', 'Gift voucher'), ('DC', 'Delivery challan'), ('DN', 'Debit note')], max_length=3)),
                ('fy', models.CharField(max_length=5)),
                ('n', models.BigIntegerField()),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('cancelled', 'Cancelled')], max_length=10)),
                ('document_type', models.CharField(blank=True, default='', max_length=40)),
                ('document_ref', models.CharField(blank=True, default='', max_length=64)),
                ('issued_on', models.DateField()),
                ('period', models.DateField()),
                ('reason', models.CharField(blank=True, default='', max_length=240)),
                ('updated_at', models.DateTimeField()),
                ('prefix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numbers', to='masters.documentprefix')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'ordering': ['prefix', 'series', 'fy', 'n'],
            },
        ),
        migrations.CreateModel(
            name='NumberingSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('new_format_from', models.DateField()),
                ('till_block_size', models.PositiveIntegerField()),
                ('revision', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='documentprefix',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_documentprefix_code'),
        ),
        migrations.AddConstraint(
            model_name='documentprefix',
            constraint=models.UniqueConstraint(condition=models.Q(('site__isnull', False)), fields=('tenant', 'site'), name='uq_documentprefix_site'),
        ),
        migrations.AddConstraint(
            model_name='documentprefix',
            constraint=models.UniqueConstraint(condition=models.Q(('gstin__isnull', False)), fields=('tenant', 'gstin'), name='uq_documentprefix_gstin'),
        ),
        migrations.AddConstraint(
            model_name='documentprefix',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('gstin__isnull', True), ('site__isnull', False)), models.Q(('gstin__isnull', False), ('site__isnull', True)), _connector='OR'), name='ck_documentprefix_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='documentprefix',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z]{3}$')), name='ck_documentprefix_three_letters'),
        ),
        migrations.AddConstraint(
            model_name='documentseriescounter',
            constraint=models.UniqueConstraint(fields=('tenant', 'prefix', 'series', 'fy'), name='uq_documentseriescounter_scope'),
        ),
        migrations.AddConstraint(
            model_name='documentseriescounter',
            constraint=models.CheckConstraint(condition=models.Q(('next_n__gte', 1)), name='ck_documentseriescounter_positive'),
        ),
        migrations.AddIndex(
            model_name='issueddocumentnumber',
            index=models.Index(fields=['tenant', 'status', 'period'], name='issueddocno_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='issueddocumentnumber',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='uq_issueddocumentnumber'),
        ),
        migrations.AddConstraint(
            model_name='issueddocumentnumber',
            constraint=models.UniqueConstraint(fields=('tenant', 'prefix', 'series', 'fy', 'n'), name='uq_issueddocumentnumber_scope'),
        ),
        migrations.AddConstraint(
            model_name='numberingsetting',
            constraint=models.UniqueConstraint(fields=('tenant',), name='uq_numberingsetting_tenant'),
        ),
        migrations.AddConstraint(
            model_name='numberingsetting',
            constraint=models.CheckConstraint(condition=models.Q(('new_format_from__day', 1), ('new_format_from__month', 4)), name='ck_numberingsetting_first_april'),
        ),
        migrations.AddConstraint(
            model_name='numberingsetting',
            constraint=models.CheckConstraint(condition=models.Q(('till_block_size__gte', 1)), name='ck_numberingsetting_block_size'),
        ),
    ]
