# Generated by Django 5.1.15 on 2026-09-27 19:29

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_merge_store_roles"),
        ("masters", "0026_consent_wording"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandPromotionVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("version", models.PositiveIntegerField()),
                ("applies_from", models.DateField()),
                ("agreement", models.BooleanField()),
                ("note", models.CharField(max_length=240)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.humanidentity",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.brand",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "brand", "version"),
                        name="uq_brandpromotionversion_number",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="ck_brandpromotionversion_from_one",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BrandTermsDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "subject_kind",
                    models.CharField(
                        choices=[("terms", "Terms"), ("promotion", "Promotion-services agreement")],
                        max_length=12,
                    ),
                ),
                ("subject_id", models.UUIDField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=12,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=240)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.humanidentity",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "subject_kind", "subject_id"),
                        name="uq_brandtermsdecision_one_per_row",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BrandTermsVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("version", models.PositiveIntegerField()),
                ("applies_from", models.DateField()),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("sor", "SOR"),
                            ("outright", "Outright"),
                            ("consignment", "Consignment"),
                            ("concession", "Concession"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "margin_percent",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "return_allowance_percent",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "discount_funding_percent",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("payment_days", models.PositiveIntegerField(blank=True, null=True)),
                ("note", models.CharField(max_length=240)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.humanidentity",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.brand",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.season",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "brand", "season", "version"),
                        name="uq_brandtermsversion_number",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="ck_brandtermsversion_from_one",
                    ),
                ],
            },
        ),
    ]
