# Generated by Django 5.1.15 on 2026-09-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masters", "0027_brand_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="ended_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
