# Generated by Django 5.1.15 on 2026-09-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0028_season_ended_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='corrected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
