# Generated by Django 5.1.15 on 2026-09-28 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0029_customer_corrected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merged', to='masters.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CustomerNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('reason', models.CharField(choices=[('merged', 'Merged in'), ('moved', 'Moved to a new number')], max_length=8)),
                ('since', models.DateTimeField(blank=True, null=True)),
                ('until', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_numbers', to='masters.customer')),
            ],
            options={
                'db_table': 'masters_customer_number',
                'ordering': ['recorded_at', 'id'],
                'indexes': [models.Index(fields=['mobile'], name='masters_cust_number_mob_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('reason', 'merged'), ('until__isnull', True)), models.Q(('reason', 'moved'), ('until__isnull', False)), _connector='OR'), name='ck_customer_number_until')],
            },
        ),
    ]
