# Generated by Django 5.1.15 on 2026-09-28 14:37

import core.money
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_merge_store_roles"),
        ("masters", "0030_customer_merge_and_numbers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "month",
                    models.DateField(
                        help_text="The month, as its first day (2026-08-01 = August 2026)."
                    ),
                ),
                (
                    "target_paise",
                    core.money.MoneyField(
                        help_text="Net sales asked of this person here for the month."
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "set_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who last set this number.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_targets_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.staff",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_targets",
                        to="masters.store",
                    ),
                ),
            ],
            options={
                "ordering": ["store__code", "month"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store", "staff", "month"), name="uq_stafftarget_store_staff_month"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("month__day", 1)),
                        name="ck_stafftarget_month_is_first_of_month",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("target_paise__gte", 0)),
                        name="ck_stafftarget_target_not_negative",
                    ),
                ],
            },
        ),
    ]
