# Generated by Django 5.2.17 on 2026-09-29 17:43

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_roleassignment_revoked_at'),
        ('core', '0012_customer_reservation'),
        ('masters', '0031_staff_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandIdentityBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('resource_model', models.CharField(max_length=100)),
                ('resource_id', models.BigIntegerField()),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('basis', models.JSONField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='masters_brandidentitybinding_one_actor'), models.UniqueConstraint(fields=('tenant', 'resource_model', 'resource_id'), name='uq_brand_identity_resource')],
            },
        ),
    ]
