# Generated by Django 5.2.17 on 2026-10-01 07:34

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_installationregistration'),
        ('approvals', '0018_transfer_approval_subject'),
        ('core', '0012_customer_reservation'),
        ('files', '0004_evidencelink_tenant_evidenceobject_actor_and_more'),
        ('masters', '0033_first_store_controls'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSheetImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('source_hash', models.CharField(max_length=64)),
                ('source_name', models.CharField(max_length=240)),
                ('parsed', models.JSONField(default=dict)),
                ('selections', models.JSONField(default=dict)),
                ('base', models.JSONField(default=dict)),
                ('base_hash', models.CharField(blank=True, max_length=64)),
                ('plan', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('reviewed_hash', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(choices=[('review', 'Review'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('withdrawn', 'Withdrawn')], default='review', max_length=20)),
                ('result', models.JSONField(default=dict)),
                ('approval_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='approvals.approvalrequest')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('source_evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.evidenceobject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
            ],
        ),
        migrations.CreateModel(
            name='MasterSheetImportReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('revision', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('source_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='masters.mastersheetimport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='mastersheetimport',
            index=models.Index(fields=['tenant', 'state', 'created_at'], name='masters_mas_tenant__411324_idx'),
        ),
        migrations.AddConstraint(
            model_name='mastersheetimportreview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='masters_mastersheetimportreview_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='mastersheetimportreview',
            constraint=models.UniqueConstraint(fields=('source_import', 'revision'), name='uq_master_sheet_review_revision'),
        ),
    ]
