# Generated by Django 5.1.15 on 2026-07-30 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0007_dataset_watermarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('funder', models.CharField(choices=[('brand', 'Funded by the brand'), ('kdps', 'Funded by KDPS')], default='brand', max_length=8)),
                ('layer', models.CharField(choices=[('brand', 'Brand offer'), ('storewide', 'Storewide add-on'), ('bank', 'Bank / tender add-on')], default='brand', max_length=12)),
                ('trigger_type', models.CharField(choices=[('none', 'No condition'), ('spend', 'Spend threshold'), ('qty', 'Quantity threshold'), ('group', 'Buy X get Y')], default='none', max_length=8)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('reward_type', models.CharField(choices=[('pct_off', 'Percent off'), ('amt_off', 'Amount off'), ('item_free', 'Item free'), ('fixed_price', 'Fixed price'), ('gift', 'Gift')], max_length=12)),
                ('reward_config', models.JSONField(blank=True, default=dict)),
                ('item_scope', models.JSONField(blank=True, default=dict)),
                ('store_scope', models.JSONField(blank=True, default=dict, help_text="{'kind': 'all'|'specific', 'stores': ['DEO', ...]} - always a list, resolved when the offer was written, so a new store is never auto-enrolled.")),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, help_text='Empty means it rolls until somebody stops it (D5 Q5).', null=True)),
                ('combinable', models.BooleanField(default=False, help_text='Stacking is opt-in, per offer. Every new offer defaults to non-combining.')),
                ('priority', models.IntegerField(default=100, help_text='Lower wins a tie on rupees. Then the id does.')),
                ('is_fallback', models.BooleanField(default=False, help_text="The named default that fills a gap in a brand's timeline (D5 Q5).")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('live', 'Live'), ('ended', 'Ended')], default='draft', max_length=8)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_approved', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(blank=True, help_text="Empty means the rule is not one brand's - a storewide or KDPS offer.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='masters.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_authored', to=settings.AUTH_USER_MODEL)),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='offers.offer')),
            ],
            options={
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['layer', 'starts_on', 'ends_on'], name='offers_window_idx'), models.Index(fields=['brand'], name='offers_brand_idx'), models.Index(fields=['updated_at'], name='offers_synced_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='offer_ends_after_it_starts'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'live'), _negated=True), ('approved_by__isnull', False), _connector='OR'), name='offer_live_only_after_approval')],
            },
        ),
    ]
