# Generated by Django 5.1.15 on 2026-08-03 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0008_customer"),
        ("offers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="mode",
            field=models.CharField(
                choices=[("regular", "Regular"), ("eoss", "End-of-season sale")],
                default="regular",
                help_text="A tag for margin-attribution reporting only (D5): an EOSS offer runs through the exact same engine as any other. Nothing is reclaimed from a brand because a rule is tagged EOSS - it only marks the report.",
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="EossLadderStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step_no", models.PositiveIntegerField()),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("gap", "Points behind the sell-through target"),
                            ("age", "Weeks in stock"),
                        ],
                        default="gap",
                        max_length=8,
                    ),
                ),
                (
                    "trigger_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Points behind target (gap) or weeks in stock (age), whichever trigger_type says.",
                        max_digits=6,
                    ),
                ),
                ("discount_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty = the network default ladder.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eoss_ladder_steps",
                        to="masters.brand",
                    ),
                ),
            ],
            options={
                "ordering": ["brand_id", "step_no"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("brand", "step_no"), name="uq_eoss_ladder_brand_step"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EossRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("design", models.CharField(blank=True, default="", max_length=120)),
                ("color", models.CharField(blank=True, default="", max_length=60)),
                ("item", models.CharField(blank=True, default="", max_length=120)),
                ("weeks_in_stock", models.IntegerField(default=0)),
                ("on_hand_qty", models.IntegerField(default=0)),
                ("sold_qty", models.IntegerField(default=0)),
                (
                    "sell_through_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "target_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "gap_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("broken_size_run", models.BooleanField(default=False)),
                (
                    "margin_floor_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The deepest discount possible before the price falls below unit cost.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "recommended_discount_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                (
                    "decided_discount_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eoss_recommendations",
                        to="masters.brand",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eoss_recommendation",
                        to="offers.offer",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eoss_recommendations",
                        to="masters.season",
                    ),
                ),
            ],
            options={
                "ordering": ["-gap_pct", "design"],
                "indexes": [
                    models.Index(
                        fields=["season", "status"], name="eoss_reco_season_status_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("season", "brand", "design", "color"),
                        name="uq_eoss_reco_style",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SellThroughTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "week_number",
                    models.PositiveIntegerField(
                        help_text="Weeks since the style first arrived."
                    ),
                ),
                ("target_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty = the network default curve.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sell_through_targets",
                        to="masters.brand",
                    ),
                ),
            ],
            options={
                "ordering": ["brand_id", "week_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("brand", "week_number"),
                        name="uq_sellthrough_brand_week",
                    )
                ],
            },
        ),
    ]
