# Generated by Django 5.1.15 on 2026-06-28 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0001_initial"),
        ("masters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=32, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("booked", "Booked"),
                            ("partially_received", "Partially received"),
                            ("received", "Received"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("vendor_ref", models.CharField(blank=True, default="", max_length=80)),
                ("ownership", models.CharField(default="", max_length=12)),
                ("return_terms", models.CharField(default="", max_length=12)),
                (
                    "estimated_value_paise",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=400)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="masters.brand",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_store",
                    models.ForeignKey(
                        blank=True,
                        help_text="Where the goods are expected to land (store delivery). Null = warehouse/HO.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="masters.store",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="masters.season",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="files.storedfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("style_code", models.CharField(max_length=80)),
                ("size", models.CharField(blank=True, default="", max_length=24)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("booked_qty", models.IntegerField(default=0)),
                ("mrp_paise", models.BigIntegerField(blank=True, null=True)),
                ("received_qty", models.IntegerField(default=0)),
                ("inwarded_qty", models.IntegerField(default=0)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="vendors.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("city", models.CharField(blank=True, default="", max_length=80)),
                ("gstin", models.CharField(blank=True, default="", max_length=15)),
                ("state_code", models.CharField(blank=True, default="", max_length=2)),
                ("state_name", models.CharField(blank=True, default="", max_length=40)),
                ("pan", models.CharField(blank=True, default="", max_length=10)),
                (
                    "payment_terms",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "brands",
                    models.ManyToManyField(
                        blank=True, related_name="vendors", to="masters.brand"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="vendors.vendor",
            ),
        ),
    ]
