# Generated by Django 5.1.15 on 2026-07-05 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0004_seed_default_category_margin"),
        ("vendors", "0002_moneyfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingline",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="Destination store for this line (multi-store booking). Null = use the booking's default destination_store (else warehouse/HO).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking_lines",
                to="masters.store",
            ),
        ),
    ]
