# Generated by Django 5.1.15 on 2026-09-13 15:25

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_tenant_authenticationfailure_tenant_and_more'),
        ('core', '0009_voucherseries_tenant_and_more'),
        ('masters', '0012_style_productsku_identitypick_skualias_and_more'),
        ('vendors', '0006_seed_booking_approval_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, max_length=60, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='core.documentidentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='vendors.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingReceiptLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('booking_line_key', models.UUIDField()),
                ('grn_line_key', models.UUIDField()),
                ('linked_qty', models.IntegerField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('counter_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counters', to='vendors.bookingreceiptlink')),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.documentidentity')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_links', to='vendors.goodsbooking')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['booking', 'booking_line_key'], name='vendors_boo_booking_9828e2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='vendors_bookingreceiptlink_one_actor'), models.CheckConstraint(condition=models.Q(('linked_qty__gt', 0)), name='ck_receiptlink_qty')],
            },
        ),
        migrations.CreateModel(
            name='BookingCorrectionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('reason_code', models.CharField(max_length=60)),
                ('effective_at', models.DateTimeField()),
                ('payload', models.JSONField()),
                ('evidence_ids', models.JSONField(default=list)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
                ('prior_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.officialversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='vendors.goodsbooking')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['booking', 'effective_at'], name='vendors_boo_booking_ad4bb4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='vendors_bookingcorrectionevent_one_actor')],
            },
        ),
    ]
