# Generated by Django 5.1.15 on 2026-09-28 11:10

import core.goods_base
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from core.dbroles import tenant_rls_sql

#: Both tables behind the tenant wall. A budget is never deleted (its figure is
#: changed, with an audit record); an ask is never changed or deleted.
GUARDS = f"""
{tenant_rls_sql("vendors_open_to_buy_budget")}
{tenant_rls_sql("vendors_open_to_buy_ask")}
CREATE OR REPLACE FUNCTION kdps_open_to_buy_guard() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'open-to-buy records are never deleted (%)', TG_TABLE_NAME;
    END IF;
    IF TG_TABLE_NAME = 'vendors_open_to_buy_ask' THEN
        RAISE EXCEPTION 'an open-to-buy ask is never changed';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER vendors_open_to_buy_budget_guard BEFORE DELETE ON vendors_open_to_buy_budget
    FOR EACH ROW EXECUTE FUNCTION kdps_open_to_buy_guard();
CREATE TRIGGER vendors_open_to_buy_ask_guard BEFORE UPDATE OR DELETE ON vendors_open_to_buy_ask
    FOR EACH ROW EXECUTE FUNCTION kdps_open_to_buy_guard();
"""

UNGUARD = """
DROP TRIGGER IF EXISTS vendors_open_to_buy_budget_guard ON vendors_open_to_buy_budget;
DROP TRIGGER IF EXISTS vendors_open_to_buy_ask_guard ON vendors_open_to_buy_ask;
DROP FUNCTION IF EXISTS kdps_open_to_buy_guard();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0030_customer_merge_and_numbers'),
        ('vendors', '0010_bookingline_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenToBuyAsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft_hash', models.CharField(max_length=64)),
                ('figures', models.JSONField(default=list)),
                ('over_paise', models.BigIntegerField(default=0)),
                ('asked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='open_to_buy_asks', to='vendors.goodsbooking')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.season')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('tenant', models.ForeignKey(db_default=core.goods_base.CurrentTenant(), editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'db_table': 'vendors_open_to_buy_ask',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['booking', 'created_at'], name='vendors_ope_booking_8a09b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='OpenToBuyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_paise', models.BigIntegerField()),
                ('revision', models.PositiveIntegerField(default=1)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.season')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('tenant', models.ForeignKey(db_default=core.goods_base.CurrentTenant(), editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'db_table': 'vendors_open_to_buy_budget',
                'ordering': ['brand_id', 'season_id', 'site_id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('site__isnull', False)), fields=('tenant', 'brand', 'season', 'site'), name='uq_otb_budget_site'), models.UniqueConstraint(condition=models.Q(('site__isnull', True)), fields=('tenant', 'brand', 'season'), name='uq_otb_budget_company'), models.CheckConstraint(condition=models.Q(('budget_paise__gte', 0)), name='ck_otb_budget_not_negative')],
            },
        ),
        migrations.RunSQL(GUARDS, UNGUARD),
    ]
