# Generated by Django 5.1.15 on 2026-09-28 11:17

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_merge_store_roles"),
        ("masters", "0030_customer_merge_and_numbers"),
        ("vendors", "0010_bookingline_cost"),
    ]

    operations = [
        migrations.CreateModel(
            name="SizeCurveFill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("reference_season", models.CharField(max_length=24)),
                ("category", models.CharField(max_length=120)),
                ("style_code", models.CharField(max_length=120)),
                ("total", models.PositiveIntegerField()),
                ("history", models.JSONField()),
                ("split", models.JSONField()),
                ("made_at", models.DateTimeField()),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.brand",
                    ),
                ),
                (
                    "made_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounts.humanidentity",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.season",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.store",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["made_at"],
                "indexes": [
                    models.Index(
                        fields=["store", "brand", "season"], name="vendors_siz_store_i_3294b1_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("total__gt", 0)), name="ck_sizecurvefill_total"
                    )
                ],
            },
        ),
    ]
