# Generated by Django 5.1.15 on 2026-09-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_open_to_buy'),
        ('vendors', '0011_size_curve_fill'),
    ]

    operations = [
    ]
