"""Admin for the alerts spine (#77).

``AlertPolicy`` is editable — the thresholds are business numbers an owner
retunes as stores and brands change, not constants that need a release
(Rule 12). ``Alert`` is read-only, generated by the daily job; the one write
path is ``alerts.checks``.
"""

from __future__ import annotations

from typing import Any

from django.contrib import admin

from alerts.models import Alert, AlertPolicy


@admin.register(AlertPolicy)
# `ModelAdmin` is generic to django-stubs but not subscriptable at runtime here
# (same gap as `core.money.MoneyField`'s base) - subscripting it crashes Django's
# admin autodiscover, so the generic arg is left off rather than "fixed".
class AlertPolicyAdmin(admin.ModelAdmin):  # type: ignore[type-arg]
    list_display = ("kind", "thresholds_days")
    readonly_fields = ("created_at", "updated_at")

    def has_add_permission(self, request: Any) -> bool:
        return False

    def has_delete_permission(self, request: Any, obj: Any = None) -> bool:
        return False


@admin.register(Alert)
# See the type-ignore note on `AlertPolicyAdmin` above.
class AlertAdmin(admin.ModelAdmin):  # type: ignore[type-arg]
    list_display = ("kind_label", "title", "status", "store", "due_date", "created_at")
    list_filter = ("kind", "status")
    search_fields = ("title",)
    date_hierarchy = "created_at"

    def has_add_permission(self, request: Any) -> bool:
        return False

    def has_change_permission(self, request: Any, obj: Any = None) -> bool:
        return False

    def has_delete_permission(self, request: Any, obj: Any = None) -> bool:
        return False
