# Generated by Django 5.1.15 on 2026-09-27 11:32

import core.money
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0025_document_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRefresh',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('as_of', models.DateTimeField(blank=True, null=True)),
                ('took_ms', models.IntegerField(default=0)),
                ('documents', models.IntegerField(default=0, help_text='Documents the last run re-read.')),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'db_table': 'report_refresh',
            },
        ),
        migrations.CreateModel(
            name='SalesLineFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='The business day, India time.')),
                ('source', models.CharField(choices=[('sale', 'A bill (sold lines and exchange legs)'), ('old_return', 'An old standalone return')], max_length=12)),
                ('doc_id', models.BigIntegerField(help_text='The bill (or old return) this row came from.')),
                ('line_id', models.BigIntegerField()),
                ('share_position', models.PositiveSmallIntegerField(default=0)),
                ('share_percent', models.PositiveSmallIntegerField(default=100)),
                ('bill_id', models.BigIntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('salesperson_key', models.CharField(blank=True, default='', max_length=64)),
                ('salesperson_name', models.CharField(blank=True, default='', max_length=160)),
                ('salesperson_code', models.CharField(blank=True, default='', max_length=40)),
                ('pieces_x100', models.BigIntegerField()),
                ('gross_paise', core.money.MoneyField(default=0)),
                ('disc_paise', core.money.MoneyField(default=0)),
                ('value_paise', core.money.MoneyField(default=0)),
                ('gst_paise', core.money.MoneyField(default=0)),
                ('cost_paise', core.money.MoneyField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'report_sales_line_fact',
                'ordering': ['store_id', 'day', 'id'],
                'indexes': [models.Index(fields=['store', 'day'], name='rpt_saleline_store_day_idx'), models.Index(fields=['source', 'doc_id'], name='rpt_saleline_doc_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesTenderFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('source', models.CharField(choices=[('sale', 'A bill (sold lines and exchange legs)'), ('old_return', 'An old standalone return')], max_length=12)),
                ('doc_id', models.BigIntegerField()),
                ('bill_id', models.BigIntegerField(blank=True, null=True)),
                ('mode', models.CharField(max_length=12)),
                ('amount_paise', core.money.MoneyField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'report_sales_tender_fact',
                'ordering': ['store_id', 'day', 'id'],
                'indexes': [models.Index(fields=['store', 'day'], name='rpt_tender_store_day_idx'), models.Index(fields=['source', 'doc_id'], name='rpt_tender_doc_idx')],
            },
        ),
    ]
