# Generated by Django 5.1.15 on 2026-09-27 19:24

import core.money
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0025_document_series'),
        ('offers', '0004_seed_offer_approval_policy'),
        ('reporting', '0001_sales_report_copy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferSimLineFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='The business day, India time.')),
                ('bill_id', models.BigIntegerField()),
                ('line_id', models.BigIntegerField()),
                ('line_no', models.IntegerField()),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('brand_key', models.CharField(blank=True, default='', max_length=120)),
                ('item', models.CharField(blank=True, default='', max_length=120)),
                ('design', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.CharField(blank=True, default='', max_length=24)),
                ('color', models.CharField(blank=True, default='', max_length=60)),
                ('barcode', models.CharField(blank=True, default='', max_length=64)),
                ('season', models.CharField(blank=True, default='', max_length=120)),
                ('qty', models.IntegerField()),
                ('mrp_paise', core.money.MoneyField(default=0)),
                ('disc_paise', core.money.MoneyField(default=0)),
                ('net_paise', core.money.MoneyField(default=0)),
                ('gst_paise', core.money.MoneyField(default=0)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cost_paise', core.money.MoneyField(blank=True, null=True)),
                ('no_discount', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'report_offer_sim_line_fact',
                'ordering': ['store_id', 'day', 'bill_id', 'line_no'],
                'indexes': [models.Index(fields=['store', 'day'], name='rpt_offersim_store_day_idx'), models.Index(fields=['brand_key', 'day'], name='rpt_offersim_brand_day_idx'), models.Index(fields=['bill_id'], name='rpt_offersim_bill_idx')],
            },
        ),
        migrations.CreateModel(
            name='OfferSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_updated_at', models.DateTimeField()),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('as_of', models.DateTimeField(blank=True, null=True)),
                ('formula_version', models.CharField(max_length=40)),
                ('took_ms', models.IntegerField(default=0)),
                ('result', models.JSONField(default=dict)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='offers.offer')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_offer_simulation',
                'ordering': ['-run_at', '-id'],
                'indexes': [models.Index(fields=['offer', '-run_at'], name='rpt_offersim_offer_idx')],
            },
        ),
    ]
