# Generated by Django 5.1.15 on 2026-09-27 19:32

import core.money
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0025_document_series'),
        ('reporting', '0002_offer_simulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GstOpenBlockFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(blank=True, default='', max_length=15)),
                ('month', models.DateField()),
                ('first_number', models.CharField(max_length=16)),
                ('last_number', models.CharField(max_length=16)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'report_gst_open_block_fact',
                'ordering': ['month', 'store_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GstDocumentFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(blank=True, default='', max_length=15)),
                ('day', models.DateField()),
                ('source', models.CharField(max_length=12)),
                ('doc_id', models.BigIntegerField()),
                ('kind', models.CharField(choices=[('invoice', 'Tax invoice'), ('credit_note', 'Credit note')], max_length=12)),
                ('number', models.CharField(blank=True, default='', max_length=128)),
                ('original_number', models.CharField(blank=True, default='', max_length=128)),
                ('supply', models.CharField(choices=[('b2b', 'B2B (buyer GSTIN on the bill)'), ('b2c', 'B2C')], max_length=3)),
                ('split', models.CharField(choices=[('intra', 'CGST + SGST (same state)'), ('inter', 'IGST (another state)')], max_length=5)),
                ('buyer_gstin', models.CharField(blank=True, default='', max_length=15)),
                ('pieces', models.IntegerField(default=0)),
                ('taxable_paise', core.money.MoneyField(default=0)),
                ('igst_paise', core.money.MoneyField(default=0)),
                ('cgst_paise', core.money.MoneyField(default=0)),
                ('sgst_paise', core.money.MoneyField(default=0)),
                ('tax_paise', core.money.MoneyField(default=0)),
                ('value_paise', core.money.MoneyField(default=0)),
                ('late', models.BooleanField(default=False)),
                ('irn_status', models.CharField(blank=True, default='', max_length=10)),
                ('irn', models.CharField(blank=True, default='', max_length=64)),
                ('irn_due_on', models.DateField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'report_gst_document_fact',
                'ordering': ['store_id', 'day', 'id'],
                'indexes': [models.Index(fields=['store', 'day'], name='rpt_gstdoc_store_day_idx'), models.Index(fields=['source', 'doc_id'], name='rpt_gstdoc_doc_idx')],
            },
        ),
        migrations.CreateModel(
            name='GstLineFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(blank=True, default='', max_length=15)),
                ('day', models.DateField(help_text="The document's business day, India time.")),
                ('source', models.CharField(choices=[('sale', 'A bill (sold lines and exchange legs)'), ('old_return', 'An old standalone return')], max_length=12)),
                ('doc_id', models.BigIntegerField(help_text='The bill (or old return) this row came from.')),
                ('line_id', models.BigIntegerField()),
                ('kind', models.CharField(choices=[('invoice', 'Sold on an invoice'), ('credit', 'Given back (credit note)')], max_length=8)),
                ('supply', models.CharField(choices=[('b2b', 'B2B (buyer GSTIN on the bill)'), ('b2c', 'B2C')], max_length=3)),
                ('split', models.CharField(choices=[('intra', 'CGST + SGST (same state)'), ('inter', 'IGST (another state)')], max_length=5)),
                ('hsn', models.CharField(blank=True, default='', max_length=24)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pieces', models.IntegerField()),
                ('taxable_paise', core.money.MoneyField(default=0)),
                ('igst_paise', core.money.MoneyField(default=0)),
                ('cgst_paise', core.money.MoneyField(default=0)),
                ('sgst_paise', core.money.MoneyField(default=0)),
                ('tax_paise', core.money.MoneyField(default=0)),
                ('value_paise', core.money.MoneyField(default=0)),
                ('late', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'report_gst_line_fact',
                'ordering': ['store_id', 'day', 'id'],
                'indexes': [models.Index(fields=['store', 'day'], name='rpt_gstline_store_day_idx'), models.Index(fields=['source', 'doc_id'], name='rpt_gstline_doc_idx')],
            },
        ),
        migrations.CreateModel(
            name='GstNumberFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(blank=True, default='', max_length=15)),
                ('nature', models.CharField(max_length=20)),
                ('series', models.CharField(max_length=128)),
                ('n', models.BigIntegerField()),
                ('number', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('cancelled', 'Cancelled')], max_length=10)),
                ('period', models.DateField()),
                ('unused_offline', models.BooleanField(default=False)),
                ('origin', models.CharField(max_length=12)),
                ('origin_ref', models.CharField(max_length=64)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'report_gst_number_fact',
                'ordering': ['gstin', 'nature', 'series', 'n'],
                'indexes': [models.Index(fields=['period', 'store'], name='rpt_gstno_period_store_idx'), models.Index(fields=['origin', 'origin_ref'], name='rpt_gstno_origin_idx')],
            },
        ),
    ]
