# Generated by Django 5.1.15 on 2026-09-27 22:11

import core.money
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0028_season_ended_on'),
        ('reporting', '0003_gst_report_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShrinkageLineFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='The day the loss was approved, India time.')),
                ('source', models.CharField(choices=[('shrinkage', 'A shrinkage adjustment'), ('writeoff', 'A write-off typed as shrinkage')], max_length=12)),
                ('document_id', models.UUIDField()),
                ('number', models.CharField(blank=True, default='', max_length=128)),
                ('line_key', models.UUIDField()),
                ('reason_code', models.CharField(blank=True, default='', max_length=60)),
                ('sku_id', models.UUIDField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('pieces', models.IntegerField()),
                ('cost_paise', core.money.MoneyField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'report_shrinkage_line_fact',
                'ordering': ['store_id', 'day', 'id'],
                'indexes': [models.Index(fields=['store', 'day'], name='rpt_shrink_store_day_idx')],
            },
        ),
    ]
