# Generated by Django 5.1.15 on 2026-09-27 23:03

import core.money
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0028_season_ended_on'),
        ('reporting', '0003_gst_report_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountFundingFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text="The bill's business day, India time.")),
                ('bill_id', models.BigIntegerField()),
                ('line_id', models.BigIntegerField()),
                ('part', models.PositiveSmallIntegerField()),
                ('sign', models.SmallIntegerField()),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('brand_ref_id', models.BigIntegerField(blank=True, null=True)),
                ('offer_id', models.BigIntegerField(blank=True, null=True)),
                ('offer_name', models.CharField(blank=True, default='', max_length=160)),
                ('funder', models.CharField(blank=True, default='', max_length=8)),
                ('discount_paise', core.money.MoneyField(default=0)),
                ('brand_paise', core.money.MoneyField(blank=True, null=True)),
                ('kdps_paise', core.money.MoneyField(blank=True, null=True)),
                ('unknown_reason', models.CharField(blank=True, default='', max_length=16)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'report_discount_funding_fact',
                'ordering': ['store_id', 'day', 'id'],
                'indexes': [models.Index(fields=['store', 'day'], name='rpt_funding_store_day_idx'), models.Index(fields=['bill_id'], name='rpt_funding_bill_idx')],
            },
        ),
    ]
