# Generated by Django 5.1.15 on 2026-09-27 22:09

import core.money
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0028_season_ended_on'),
        ('reporting', '0003_gst_report_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftItcFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(blank=True, default='', max_length=15)),
                ('day', models.DateField(help_text='The day the piece left stock, India time.')),
                ('tag_id', models.BigIntegerField(unique=True)),
                ('doc_id', models.BigIntegerField(help_text='The bill the piece left on.')),
                ('line_id', models.BigIntegerField()),
                ('doc_number', models.CharField(blank=True, default='', max_length=128)),
                ('barcode', models.CharField(blank=True, default='', max_length=64)),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('item', models.CharField(blank=True, default='', max_length=120)),
                ('hsn', models.CharField(blank=True, default='', max_length=24)),
                ('pieces', models.IntegerField()),
                ('source', models.CharField(max_length=12)),
                ('offer_name', models.CharField(blank=True, default='', max_length=200)),
                ('input_tax_pct', models.CharField(blank=True, default='', max_length=40)),
                ('cost_paise', core.money.MoneyField(blank=True, null=True)),
                ('itc_paise', core.money.MoneyField(blank=True, null=True)),
                ('missing', models.CharField(blank=True, default='', max_length=12)),
                ('returned', models.IntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'report_gift_itc_fact',
                'ordering': ['store_id', 'day', 'id'],
                'indexes': [models.Index(fields=['store', 'day'], name='rpt_giftitc_store_day_idx')],
            },
        ),
    ]
