# Generated by Django 5.1.15 on 2026-09-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_discount_funding_copy'),
        ('reporting', '0004_gift_stock'),
    ]

    operations = [
    ]
