# Generated by Django 5.1.15 on 2026-09-28 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_shrinkage_report_copy'),
        ('reporting', '0005_merge_0004_discount_funding_copy_0004_gift_stock'),
    ]

    operations = [
    ]
