# Generated by Django 5.1.15 on 2026-09-28 08:11

import core.money
import django.db.models.deletion
from django.db import migrations, models

# Rows copied before ticket 43 carry no season: fill it from the bill lines they
# came from, so the report need not wait for a full rebuild of the sales copy.
BACKFILL_SEASON = """
UPDATE report_sales_line_fact f SET season = l.season
  FROM sell_sale_line l
 WHERE f.source = 'sale' AND f.line_id = l.id AND l.season <> '';
UPDATE report_sales_line_fact f SET season = l.season
  FROM sell_return_line l
 WHERE f.source = 'old_return' AND f.line_id = l.id AND l.season <> '';
"""


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0029_customer_corrected_at'),
        ('reporting', '0006_merge_20260928_1314'),
        ('sell', '0011_plain_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslinefact',
            name='season',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.CreateModel(
            name='InventoryReceiptFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='The day the pieces were put away, India time.')),
                ('event_id', models.UUIDField()),
                ('origin_id', models.UUIDField(blank=True, null=True)),
                ('source', models.CharField(choices=[('receipt', 'A receipt from a vendor'), ('opening', 'Opening stock'), ('transfer', 'A transfer in')], max_length=10)),
                ('sku_id', models.UUIDField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('season_id', models.BigIntegerField(blank=True, null=True)),
                ('season', models.CharField(blank=True, default='', max_length=120)),
                ('pieces', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'report_inventory_receipt_fact',
                'ordering': ['store_id', 'day', 'id'],
                'indexes': [models.Index(fields=['store', 'day'], name='rpt_invrcpt_store_day_idx'), models.Index(fields=['event_id'], name='rpt_invrcpt_event_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='The business day, India time.')),
                ('taken_at', models.DateTimeField()),
                ('goods_records', models.BooleanField(default=True)),
                ('idle_days', models.IntegerField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'report_inventory_snapshot',
                'ordering': ['store_id', 'day'],
                'constraints': [models.UniqueConstraint(fields=('store', 'day'), name='uq_rpt_invsnap_store_day')],
            },
        ),
        migrations.CreateModel(
            name='InventoryStockFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('season_id', models.BigIntegerField(blank=True, null=True)),
                ('season', models.CharField(blank=True, default='', max_length=120)),
                ('pieces', models.IntegerField()),
                ('cost_paise', core.money.MoneyField(default=0)),
                ('dead_pieces', models.IntegerField(default=0)),
                ('dead_cost_paise', core.money.MoneyField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'report_inventory_stock_fact',
                'ordering': ['store_id', 'day', 'id'],
                'indexes': [models.Index(fields=['store', 'day'], name='rpt_invstock_store_day_idx')],
            },
        ),
        migrations.RunSQL(BACKFILL_SEASON, migrations.RunSQL.noop),
    ]
