# Generated by Django 5.1.15 on 2026-09-28 08:10

import core.money
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0029_customer_corrected_at'),
        ('reporting', '0006_merge_20260928_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarginShareFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text="The bill's business day, India time.")),
                ('bill_id', models.BigIntegerField()),
                ('doc_number', models.CharField(blank=True, default='', max_length=128)),
                ('line_id', models.BigIntegerField()),
                ('sign', models.SmallIntegerField()),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('brand_ref_id', models.BigIntegerField(blank=True, null=True)),
                ('season', models.CharField(blank=True, default='', max_length=120)),
                ('barcode', models.CharField(blank=True, default='', max_length=64)),
                ('qty', models.IntegerField()),
                ('model', models.CharField(blank=True, default='', max_length=12)),
                ('margin_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('value_paise', core.money.MoneyField(default=0)),
                ('kdps_paise', core.money.MoneyField(blank=True, null=True)),
                ('brand_paise', core.money.MoneyField(blank=True, null=True)),
                ('unknown_reason', models.CharField(blank=True, default='', max_length=16)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'report_margin_share_fact',
                'ordering': ['store_id', 'day', 'id'],
                'indexes': [models.Index(fields=['store', 'day'], name='rpt_margin_store_day_idx'), models.Index(fields=['bill_id'], name='rpt_margin_bill_idx'), models.Index(fields=['brand_ref_id', 'day'], name='rpt_margin_brand_day_idx')],
            },
        ),
    ]
