# Generated by Django 5.1.15 on 2026-09-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_inventory_report_copy'),
        ('reporting', '0007_margin_share_copy'),
    ]

    operations = [
    ]
