# Generated by Django 5.1.15 on 2026-09-28 11:20

import core.money
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0030_customer_merge_and_numbers'),
        ('reporting', '0008_merge_20260928_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='The day the exception is about, India time.')),
                ('kind', models.CharField(choices=[('cancelled_bill', 'Cancelled bill'), ('manual_discount', 'Manual discount'), ('pin_use', 'Manager PIN use'), ('cash_variance', 'Cash variance'), ('number_hole', 'Bill-number hole'), ('no_bill_return', 'Return without a bill'), ('no_bill_cap', 'Over the no-bill return cap'), ('late_sync', 'Late sync')], max_length=20)),
                ('staff_key', models.CharField(blank=True, default='', max_length=64)),
                ('staff_name', models.CharField(blank=True, default='', max_length=160)),
                ('events', models.IntegerField(default=1)),
                ('value_paise', core.money.MoneyField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, default='', max_length=128)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'report_exception_fact',
                'ordering': ['store_id', 'day', 'id'],
                'indexes': [models.Index(fields=['store', 'day'], name='rpt_exception_store_day_idx')],
            },
        ),
    ]
