# Generated by Django 5.1.15 on 2026-09-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0030_customer_merge_and_numbers'),
        ('reporting', '0009_exceptions_report_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionfact',
            name='bill_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exceptionfact',
            name='kind',
            field=models.CharField(choices=[('cancelled_bill', 'Cancelled bill'), ('price_typed', 'Price typed at the counter'), ('manual_discount', 'Manual discount'), ('pin_use', 'Manager PIN use'), ('cash_variance', 'Cash variance'), ('number_hole', 'Bill-number hole'), ('no_bill_return', 'Return without a bill'), ('no_bill_cap', 'Over the no-bill return cap'), ('late_sync', 'Late sync')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='exceptionfact',
            index=models.Index(fields=['bill_id'], name='rpt_exception_bill_idx'),
        ),
    ]
