# Generated by Django 5.1.15 on 2026-09-28 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_offer_return'),
        ('reporting', '0010_exception_fact_bill'),
    ]

    operations = [
    ]
