# Generated by Django 5.1.15 on 2026-09-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_merge_0009_offer_return_0010_exception_fact_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorystockfact',
            name='ended_pieces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorystockfact',
            name='piece_days',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
