# Generated by Django 5.1.15 on 2026-09-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0012_inventory_stock_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionfact',
            name='kind',
            field=models.CharField(choices=[('cancelled_bill', 'Cancelled bill'), ('price_typed', 'Price typed at the counter'), ('manual_discount', 'Manual discount'), ('pin_use', 'Manager PIN use'), ('cash_variance', 'Cash variance'), ('number_hole', 'Bill-number hole'), ('no_bill_return', 'Return without a bill'), ('no_bill_cap', 'Over the no-bill return cap'), ('late_sync', 'Late sync'), ('checklist_missed', 'Checklist items missed')], max_length=20),
        ),
    ]
