# Generated by Django 5.1.15 on 2026-09-28 15:51

import core.money
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def first_layouts(apps, schema_editor):
    """The KDPS Sale and SOH sheets: each company's first two layouts (ST-BRD-2).

    A company made later uses the same sheets built in until it saves its own
    (``reporting.brand_layouts.standard``)."""
    from reporting.brand_layouts import STANDARD

    tenant = apps.get_model("masters", "Tenant")
    layout = apps.get_model("reporting", "BrandReportLayout")
    for tenant_id in tenant.objects.values_list("id", flat=True):
        for kind, standard in STANDARD.items():
            layout.objects.get_or_create(
                tenant_id=tenant_id,
                brand=None,
                kind=kind,
                defaults={"name": standard["name"], "layout": standard["layout"]},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0030_customer_merge_and_numbers'),
        ('reporting', '0013_exception_fact_checklist_missed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysnapshot',
            name='items_kept',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BrandReportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='The month, as its first day.')),
                ('made_at', models.DateTimeField()),
                ('took_ms', models.IntegerField(default=0)),
                ('files', models.IntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'report_brand_report_run',
                'ordering': ['-month', 'store_id'],
            },
        ),
        migrations.CreateModel(
            name='BrandReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sale', 'Sale'), ('soh', 'SOH')], max_length=4)),
                ('month', models.DateField()),
                ('file_name', models.CharField(max_length=200)),
                ('content_type', models.CharField(max_length=120)),
                ('content', models.BinaryField()),
                ('size', models.IntegerField(default=0)),
                ('rows', models.IntegerField(default=0)),
                ('layout_id', models.BigIntegerField(blank=True, null=True)),
                ('layout_revision', models.PositiveIntegerField()),
                ('as_of', models.DateTimeField(blank=True, null=True)),
                ('about', models.JSONField(default=dict)),
                ('made_at', models.DateTimeField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.store')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='made', to='reporting.brandreportrun')),
            ],
            options={
                'db_table': 'report_brand_report_file',
                'ordering': ['-month', 'store_id', 'brand_id', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='BrandSaleLineFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='The business day, India time.')),
                ('source', models.CharField(choices=[('sale', 'Bill'), ('old_return', 'Old return document')], max_length=12)),
                ('doc_id', models.BigIntegerField()),
                ('doc_number', models.CharField(blank=True, default='', max_length=128)),
                ('line_id', models.BigIntegerField()),
                ('line_no', models.IntegerField(default=0)),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('brand_key', models.CharField(blank=True, default='', max_length=120)),
                ('item', models.CharField(blank=True, default='', max_length=120)),
                ('design', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.CharField(blank=True, default='', max_length=24)),
                ('color', models.CharField(blank=True, default='', max_length=60)),
                ('barcode', models.CharField(blank=True, default='', max_length=64)),
                ('season', models.CharField(blank=True, default='', max_length=120)),
                ('qty', models.IntegerField(help_text='Pieces; negative when given back.')),
                ('mrp_paise', core.money.MoneyField(blank=True, help_text='MRP of one piece.', null=True)),
                ('gross_paise', core.money.MoneyField(default=0, help_text='MRP times pieces, signed.')),
                ('disc_paise', core.money.MoneyField(default=0)),
                ('value_paise', core.money.MoneyField(default=0, help_text='What the customer paid, GST inside.')),
                ('gst_paise', core.money.MoneyField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'report_brand_sale_line_fact',
                'ordering': ['store_id', 'day', 'doc_id', 'line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItemFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('brand_key', models.CharField(blank=True, default='', max_length=120)),
                ('item', models.CharField(blank=True, default='', max_length=120)),
                ('design', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.CharField(blank=True, default='', max_length=24)),
                ('color', models.CharField(blank=True, default='', max_length=60)),
                ('barcode', models.CharField(blank=True, default='', max_length=64)),
                ('season', models.CharField(blank=True, default='', max_length=120)),
                ('mrp_paise', core.money.MoneyField(blank=True, null=True)),
                ('pieces', models.IntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='masters.store')),
            ],
            options={
                'db_table': 'report_inventory_item_fact',
                'ordering': ['store_id', 'day', 'brand_key', 'design', 'size', 'barcode'],
            },
        ),
        migrations.CreateModel(
            name='BrandReportLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sale', 'Sale'), ('soh', 'SOH')], max_length=4)),
                ('name', models.CharField(max_length=120)),
                ('layout', models.JSONField()),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_brand_layout',
                'ordering': ['tenant_id', 'kind', 'brand_id'],
                'constraints': [models.UniqueConstraint(fields=('brand', 'kind'), name='uq_rpt_brandlayout_brand_kind'), models.UniqueConstraint(condition=models.Q(('brand__isnull', True)), fields=('tenant', 'kind'), name='uq_rpt_brandlayout_standard_kind')],
            },
        ),
        migrations.AddConstraint(
            model_name='brandreportrun',
            constraint=models.UniqueConstraint(fields=('store', 'month'), name='uq_rpt_brandrun_store_month'),
        ),
        migrations.AddConstraint(
            model_name='brandreportfile',
            constraint=models.UniqueConstraint(fields=('store', 'brand', 'kind', 'month'), name='uq_rpt_brandfile_one_a_month'),
        ),
        migrations.AddIndex(
            model_name='brandsalelinefact',
            index=models.Index(fields=['store', 'brand_key', 'day'], name='rpt_brandsale_store_brand_idx'),
        ),
        migrations.AddIndex(
            model_name='brandsalelinefact',
            index=models.Index(fields=['source', 'doc_id'], name='rpt_brandsale_doc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitemfact',
            index=models.Index(fields=['store', 'day', 'brand_key'], name='rpt_invitem_store_day_idx'),
        ),
        migrations.RunPython(first_layouts, migrations.RunPython.noop),
    ]
