# Generated by Django 5.2.17 on 2026-09-29 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0032_so03_brand_identity'),
        ('reporting', '0014_brand_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsalelinefact',
            name='brand_ref',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand'),
        ),
        migrations.AddField(
            model_name='giftitcfact',
            name='brand_ref',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand'),
        ),
        migrations.AddField(
            model_name='inventoryitemfact',
            name='brand_ref',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand'),
        ),
        migrations.AddField(
            model_name='inventoryreceiptfact',
            name='brand_ref',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand'),
        ),
        migrations.AddField(
            model_name='inventorystockfact',
            name='brand_ref',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand'),
        ),
        migrations.AddField(
            model_name='offersimlinefact',
            name='brand_ref',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand'),
        ),
        migrations.AddField(
            model_name='saleslinefact',
            name='brand_ref',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand'),
        ),
        migrations.AddField(
            model_name='shrinkagelinefact',
            name='brand_ref',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.brand'),
        ),
    ]
