# Generated by Django 5.1.15 on 2026-06-28 19:52

import core.money
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from core.ledger import append_only_reverse_sql, append_only_sql

STOCK_LEDGER_TABLE = "stockledger_entry"


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masters", "0001_initial"),
        ("ptmapper", "0003_ptfile_booking_ptfile_inward_doc_number"),
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", core.money.MoneyField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sku_code", models.CharField(db_index=True, max_length=64)),
                ("design", models.CharField(blank=True, default="", max_length=120)),
                ("color", models.CharField(blank=True, default="", max_length=60)),
                ("size", models.CharField(blank=True, default="", max_length=24)),
                ("brand", models.CharField(blank=True, default="", max_length=120)),
                ("season", models.CharField(blank=True, default="", max_length=120)),
                ("item", models.CharField(blank=True, default="", max_length=120)),
                ("hsn", models.CharField(blank=True, default="", max_length=24)),
                ("qty", models.IntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pt_inward", "PT inward"),
                            ("pt_reversal", "PT reversal"),
                        ],
                        max_length=16,
                    ),
                ),
                ("doc_number", models.CharField(db_index=True, max_length=128)),
                ("line_no", models.IntegerField(default=0)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_entries",
                        to="vendors.booking",
                    ),
                ),
                (
                    "gstin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_entries",
                        to="masters.gstin",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pt_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_entries",
                        to="ptmapper.ptfile",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_entries",
                        to="masters.store",
                    ),
                ),
            ],
            options={
                "db_table": "stockledger_entry",
                "ordering": ["-created_at", "line_no"],
            },
        ),
        # Append-only enforcement (ADR-0004): BEFORE UPDATE OR DELETE trigger
        # blocks every role (superuser included); the REVOKE is defence-in-depth.
        migrations.RunSQL(
            sql=append_only_sql(STOCK_LEDGER_TABLE),
            reverse_sql=append_only_reverse_sql(STOCK_LEDGER_TABLE),
        ),
    ]
