# Generated by Django 5.1.15 on 2026-07-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockledger", "0003_stock_on_hand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockledgerentry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("pt_inward", "PT inward"),
                    ("pt_reversal", "PT reversal"),
                    ("transfer_out", "Transfer out"),
                    ("transfer_in", "Transfer in"),
                    ("rtv_out", "RTV out"),
                    ("seasonal_ret", "Seasonal return"),
                    ("adjustment", "Adjustment"),
                    ("write_off", "Write-off"),
                    ("vflip_out", "V-flip out"),
                    ("vflip_in", "V-flip in"),
                ],
                max_length=16,
            ),
        ),
    ]
