# Generated by Django 5.1.15 on 2026-07-23 12:17

import core.money
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_seed_default_category_margin'),
        ('stockledger', '0004_alter_stockledgerentry_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledgerentry',
            name='kind',
            field=models.CharField(choices=[('pt_inward', 'PT inward'), ('pt_reversal', 'PT reversal'), ('transfer_out', 'Transfer out'), ('transfer_in', 'Transfer in'), ('transit_in', 'Transit in'), ('transit_out', 'Transit out'), ('rtv_out', 'RTV out'), ('seasonal_ret', 'Seasonal return'), ('adjustment', 'Adjustment'), ('write_off', 'Write-off'), ('vflip_out', 'V-flip out'), ('vflip_in', 'V-flip in')], max_length=16),
        ),
        migrations.CreateModel(
            name='InTransitStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_doc_number', models.CharField(db_index=True, max_length=128)),
                ('sku_code', models.CharField(db_index=True, max_length=64)),
                ('design', models.CharField(blank=True, default='', max_length=120)),
                ('color', models.CharField(blank=True, default='', max_length=60)),
                ('size', models.CharField(blank=True, default='', max_length=24)),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('season', models.CharField(blank=True, default='', max_length=120)),
                ('item', models.CharField(blank=True, default='', max_length=120)),
                ('hsn', models.CharField(blank=True, default='', max_length=24)),
                ('qty', models.IntegerField(default=0)),
                ('value_paise', core.money.MoneyField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_transit_in', to='masters.store')),
                ('gstin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='in_transit', to='masters.gstin')),
                ('source_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_transit_out', to='masters.store')),
            ],
            options={
                'db_table': 'stockledger_in_transit',
                'ordering': ['transfer_doc_number', 'sku_code'],
                'constraints': [models.UniqueConstraint(fields=('transfer_doc_number', 'sku_code'), name='uq_in_transit_doc_sku')],
            },
        ),
    ]
