# Generated by Django 5.1.15 on 2026-07-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockledger', '0006_alter_stockledgerentry_kind_quarantinestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledgerentry',
            name='kind',
            field=models.CharField(choices=[('pt_inward', 'PT inward'), ('pt_reversal', 'PT reversal'), ('transfer_out', 'Transfer out'), ('transfer_in', 'Transfer in'), ('transit_in', 'Transit in'), ('transit_out', 'Transit out'), ('damage_out', 'Damaged out of sellable'), ('quarantine_in', 'Quarantine in'), ('quarantine_out', 'Quarantine out'), ('sale_out', 'Sale out'), ('sale_return_in', 'Sale return in'), ('rtv_out', 'RTV out'), ('seasonal_ret', 'Seasonal return'), ('adjustment', 'Adjustment'), ('write_off', 'Write-off'), ('vflip_out', 'V-flip out'), ('vflip_in', 'V-flip in')], max_length=16),
        ),
    ]
