# Generated by Django 5.1.15 on 2026-07-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_dataset_watermarks'),
        ('stockledger', '0007_alter_stockledgerentry_kind'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockonhand',
            index=models.Index(fields=['store', 'updated_at'], name='onhand_synced_idx'),
        ),
    ]
