# Generated by Django 5.1.15 on 2026-09-16 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_enforce_role_tenant"),
        ("core", "0009_voucherseries_tenant_and_more"),
        ("inbound", "0008_observation_alias_context"),
        ("masters", "0019_backfill_custody_system_location"),
        ("stockledger", "0013_operational_batch_bounded_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="origin",
            name="value_damage_disposition",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="value_origin",
                to="inbound.disposition",
            ),
        ),
        migrations.AlterField(
            model_name="origin",
            name="official_line",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="origin",
                to="core.officialline",
            ),
        ),
        migrations.AlterField(
            model_name="origin",
            name="source_kind",
            field=models.CharField(
                choices=[
                    ("receipt", "Receipt"),
                    ("opening", "Opening"),
                    ("value_damage", "Value Damage"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddConstraint(
            model_name="origin",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("official_line__isnull", False),
                        ("source_kind__in", ["receipt", "opening"]),
                        ("value_damage_disposition__isnull", True),
                    ),
                    models.Q(
                        ("official_line__isnull", True),
                        ("source_kind", "value_damage"),
                        ("value_damage_disposition__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="ck_origin_source_reference",
            ),
        ),
    ]
