# Generated by Django 5.1.15 on 2026-09-16 10:23

import uuid

import django.contrib.postgres.constraints
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import core.goods_fields


class Migration(migrations.Migration):
    dependencies = [
        ("masters", "0019_backfill_custody_system_location"),
        ("stockledger", "0015_value_damage_posting_truth"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveValueBasis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
                ),
                ("portion", core.goods_fields.PortionField()),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="stockledger.custodylot",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="stockledger.origin",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="masters.tenant",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["lot"], name="stockledger_lot_id_fde7c9_idx")],
                "constraints": [
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        expressions=[("tenant", "="), ("lot", "="), ("portion", "&&")],
                        name="ex_livevaluebasis_overlap",
                    )
                ],
            },
        ),
    ]
