# Generated by Django 5.1.15 on 2026-09-26 02:14

import django.contrib.postgres.constraints
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_merge_store_roles"),
        ("core", "0011_alter_documentidentity_purpose"),
        ("files", "0004_evidencelink_tenant_evidenceobject_actor_and_more"),
        ("masters", "0022_crosswalk_attribute_kinds"),
        ("outbound", "0041_transfer_excess_corrective"),
        ("stockledger", "0020_disposal_posting_kind"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="custodymatch",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("tenant", "="),
                    ("observed_lot", "="),
                    ("observed_portion", "&&"),
                ],
                name="ex_custodymatch_observed",
            ),
        ),
    ]
