# Generated by Django 5.1.15 on 2026-09-27 22:37

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_store_roles'),
        ('masters', '0028_season_ended_on'),
        ('stockledger', '0021_custody_match_once'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokenSizeAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('colour', models.CharField(blank=True, max_length=120)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('style_code', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('core_sizes', models.JSONField(default=list)),
                ('missing_sizes', models.JSONField(default=list)),
                ('held', models.JSONField(default=dict)),
                ('pieces', models.PositiveIntegerField()),
                ('rule_percent', models.PositiveSmallIntegerField()),
                ('missing_percent', models.PositiveSmallIntegerField()),
                ('opened_at', models.DateTimeField()),
                ('checked_at', models.DateTimeField()),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('transfer', 'Asked for a transfer of the missing sizes'), ('markdown', 'Asked for a markdown'), ('other', 'Something else (see the note)')], max_length=12)),
                ('action_note', models.CharField(blank=True, max_length=240)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_reason', models.CharField(blank=True, choices=[('fixed', 'Enough core sizes are back'), ('rule_changed', "Its category's rule changed and it is not broken under it"), ('sold_out', 'The style-colour has no stock here now'), ('no_rule', 'Its category has no rule now'), ('switched_off', 'The feature was switched off at the store'), ('not_checked', 'The store is no longer checked (closed, or not on the goods records)')], max_length=16)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.style')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'ordering': ['opened_at'],
                'indexes': [models.Index(fields=['site', 'opened_at'], name='stockledger_site_id_5415f0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('tenant', 'site', 'style', 'colour'), name='uq_brokensizealert_open'), models.CheckConstraint(condition=models.Q(('acted_at__isnull', True), models.Q(('action', ''), _negated=True), _connector='OR'), name='ck_brokensizealert_action_named'), models.CheckConstraint(condition=models.Q(('closed_at__isnull', True), models.Q(('closed_reason', ''), _negated=True), _connector='OR'), name='ck_brokensizealert_close_reason')],
            },
        ),
        migrations.CreateModel(
            name='SizeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('category', models.CharField(blank=True, max_length=120)),
                ('category_key', models.CharField(blank=True, max_length=120)),
                ('core_sizes', models.JSONField(default=list)),
                ('missing_percent', models.PositiveSmallIntegerField(default=40)),
                ('active', models.BooleanField(default=True)),
                ('revision', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant')),
            ],
            options={
                'ordering': ['category'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'category_key'), name='uq_sizerule_category'), models.CheckConstraint(condition=models.Q(('missing_percent__gte', 1), ('missing_percent__lte', 100)), name='ck_sizerule_percent')],
            },
        ),
    ]
