# Generated by Django 5.1.15 on 2026-08-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='kind',
            field=models.CharField(choices=[('booking_receipt', 'Booking receipt'), ('invoice', 'Invoice'), ('pt_file', 'PT file'), ('bank_statement', 'Bank statement'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
