# Generated by Django 5.1.15 on 2026-09-13 14:50

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_authenticationfailure_humanidentity_rolegrant_and_more'),
        ('core', '0008_auditevent_chainhead_commandattempt_commandkey_and_more'),
        ('files', '0002_bank_reconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('media_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('object_key', models.CharField(max_length=500)),
                ('object_version', models.CharField(max_length=250)),
                ('retention_until', models.DateTimeField()),
                ('legal_hold', models.BooleanField(default=False)),
                ('scope', models.JSONField()),
                ('contains_fields', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UploadIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('command_id', models.UUIDField()),
                ('scope', models.JSONField()),
                ('kind', models.CharField(max_length=20)),
                ('expected_hash', models.CharField(max_length=64)),
                ('expected_size', models.BigIntegerField()),
                ('object_key', models.CharField(max_length=500)),
                ('state', models.CharField(choices=[('staged', 'Staged'), ('confirmed', 'Confirmed'), ('refused', 'Refused')], default='staged', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('service_code', models.CharField(blank=True, max_length=60, null=True)),
                ('event_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('row_hash', models.CharField(max_length=64)),
                ('subject_key', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=60)),
                ('subject_revision', models.IntegerField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity')),
                ('command_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
