# Generated by Django 5.1.15 on 2026-09-13 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_authenticationfailure_humanidentity_rolegrant_and_more'),
        ('core', '0009_voucherseries_tenant_and_more'),
        ('files', '0003_evidenceobject_uploadintent_evidencelink'),
        ('masters', '0011_configdraft_configversion_sitecapabilityevent_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencelink',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='evidenceobject',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='evidenceobject',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='evidenceobject',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='evidencelink',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='files.evidenceobject'),
        ),
        migrations.AddField(
            model_name='uploadintent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='uploadintent',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='evidenceobject',
            name='upload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='files.uploadintent'),
        ),
        migrations.AddIndex(
            model_name='evidencelink',
            index=models.Index(fields=['subject_key'], name='files_evide_subject_946274_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidencelink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='files_evidencelink_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='evidencelink',
            constraint=models.UniqueConstraint(fields=('evidence', 'subject_key', 'relationship', 'subject_revision'), name='uq_evidencelink'),
        ),
        migrations.AddIndex(
            model_name='uploadintent',
            index=models.Index(fields=['state', 'created_at'], name='files_uploa_state_685a6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='uploadintent',
            constraint=models.UniqueConstraint(fields=('tenant', 'uploader', 'command_id'), name='uq_uploadintent_command'),
        ),
        migrations.AddConstraint(
            model_name='uploadintent',
            constraint=models.CheckConstraint(condition=models.Q(('expected_size__gte', 1), ('expected_size__lte', 20000000)), name='ck_uploadintent_size'),
        ),
        migrations.AddConstraint(
            model_name='evidenceobject',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='files_evidenceobject_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='evidenceobject',
            constraint=models.UniqueConstraint(fields=('tenant', 'object_key', 'object_version'), name='uq_evidenceobject_object'),
        ),
    ]
