# Generated by Django 5.1.15 on 2026-06-27 21:47

import core.money
from django.db import migrations, models

from core.ledger import append_only_reverse_sql, append_only_sql

LEDGER_PROBE_TABLE = "core_ledger_probe"


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerProbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', core.money.MoneyField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_ledger_probe',
            },
        ),
        # Append-only enforcement: the BEFORE UPDATE OR DELETE trigger blocks
        # every role (superuser included); the REVOKE is defence-in-depth.
        migrations.RunSQL(
            sql=append_only_sql(LEDGER_PROBE_TABLE),
            reverse_sql=append_only_reverse_sql(LEDGER_PROBE_TABLE),
        ),
    ]
