# Generated by Django 5.1.15 on 2026-06-28 07:05

import django.db.models.deletion
import uuid
from django.db import migrations, models

from core.documents import document_fsm_reverse_sql, document_fsm_sql

DOCUMENT_PROBE_TABLE = "core_document_probe"


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.CharField(max_length=7)),
                ('store_code', models.CharField(max_length=16)),
                ('doc_type', models.CharField(max_length=16)),
                ('prefix', models.CharField(blank=True, default='', max_length=32)),
                ('suffix', models.CharField(blank=True, default='', max_length=32)),
                ('next_seq', models.BigIntegerField(default=1)),
            ],
            options={
                'db_table': 'core_voucher_series',
                'constraints': [models.UniqueConstraint(fields=('fy', 'store_code', 'doc_type'), name='uq_voucher_series_scope')],
            },
        ),
        migrations.CreateModel(
            name='DocumentProbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('idempotency_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('docstatus', models.IntegerField(choices=[(0, 'draft'), (1, 'submitted'), (2, 'cancelled')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fy', models.CharField(max_length=7)),
                ('store_code', models.CharField(max_length=16)),
                ('doc_type', models.CharField(max_length=16)),
                ('memo', models.CharField(blank=True, default='', max_length=120)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.voucherseries')),
            ],
            options={
                'db_table': 'core_document_probe',
            },
        ),
        # docstatus FSM enforced at the DB: the trigger blocks every role
        # (superuser included) from re-posting, walking backwards, editing a
        # cancelled row, or deleting a posted/cancelled row.
        migrations.RunSQL(
            sql=document_fsm_sql(DOCUMENT_PROBE_TABLE),
            reverse_sql=document_fsm_reverse_sql(DOCUMENT_PROBE_TABLE),
        ),
    ]
