# Generated by Django 5.1.15 on 2026-06-28 11:07
#
# K2 fix (issue #18): widen doc_number so a long-but-valid series can't overflow
# (#5); add the posted-has-number CHECK so no row reaches a non-draft status
# without a number, on INSERT *and* UPDATE (#3); re-apply the FSM trigger
# function so cancellation can no longer rewrite other columns (#4).

from django.db import migrations, models

from core.documents import TRIGGER_FUNCTION, document_fsm_function_sql


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_voucherseries_documentprobe'),
    ]

    operations = [
        # [#5] doc_number 64 -> 128 so prefix(32)+suffix(32)+fy+store+type+seq fits.
        migrations.AlterField(
            model_name='documentprobe',
            name='doc_number',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        # [#3] a non-draft row must carry a number — fires on INSERT and UPDATE.
        migrations.AddConstraint(
            model_name='documentprobe',
            constraint=models.CheckConstraint(condition=models.Q(('docstatus', 0), ('doc_number__isnull', False), _connector='OR'), name='core_documentprobe_posted_has_number'),
        ),
        # [#4] CREATE OR REPLACE the shared FSM function in place (the trigger on
        # each table keeps pointing at it). Forward-only: the reverse leaves the
        # corrected function — restoring the prior, looser body would re-open the
        # raw-cancel tampering hole, so we don't.
        migrations.RunSQL(
            sql=document_fsm_function_sql(),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
