# Generated by Django 5.1.15 on 2026-06-28 11:52
#
# K2 hardening (2nd Codex pass, follow-up to #18): push the slice's
# "binds even the superuser" guarantee fully into the database.
#
#  #B  every INSERT must start in draft + docstatus stays in {0,1,2}.
#  #D  the gap-free counter may only hold or advance by one — a DB trigger,
#      not just Model.save(), so QuerySet.update()/raw SQL can't rewind it.
#  #E  a used series has frozen fy/store_code/doc_type.
#
# (#A — lock-and-refresh the draft before allocating — is pure Python in
#  post(); no schema change.)

from django.db import migrations, models

from core.documents import (
    document_fsm_reverse_sql,
    document_fsm_sql,
    voucher_series_guard_reverse_sql,
    voucher_series_guard_sql,
)

DOCUMENT_PROBE_TABLE = "core_document_probe"
VOUCHER_SERIES_TABLE = "core_voucher_series"


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_doc_number_width_and_posted_has_number'),
    ]

    operations = [
        # [#B] keep the stored docstatus domain to {draft, submitted, cancelled}.
        migrations.AddConstraint(
            model_name='documentprobe',
            constraint=models.CheckConstraint(condition=models.Q(('docstatus__in', [0, 1, 2])), name='core_documentprobe_docstatus_domain'),
        ),
        # [#B] the FSM trigger now fires on INSERT too (must start draft). Drop and
        # recreate so the BEFORE event list gains INSERT; the function it calls is
        # CREATE OR REPLACE'd with the new INSERT branch.
        migrations.RunSQL(
            sql=document_fsm_reverse_sql(DOCUMENT_PROBE_TABLE) + document_fsm_sql(DOCUMENT_PROBE_TABLE),
            reverse_sql=document_fsm_reverse_sql(DOCUMENT_PROBE_TABLE),
        ),
        # [#D][#E] install the counter-ownership + frozen-scope guard on the
        # voucher-series table (a DB trigger that binds even raw SQL).
        migrations.RunSQL(
            sql=voucher_series_guard_sql(VOUCHER_SERIES_TABLE),
            reverse_sql=voucher_series_guard_reverse_sql(VOUCHER_SERIES_TABLE),
        ),
    ]
