# Generated by Django 5.1.15 on 2026-06-29 19:49

import core.money
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from core.ledger import (
    append_only_reverse_sql,
    append_only_sql,
    truncate_guard_reverse_sql,
    truncate_guard_sql,
)

GL = "core_gl_entry"
# Existing append-only ledger / document tables that must also reject TRUNCATE
# (the BEFORE UPDATE/DELETE guard does not fire on TRUNCATE).
ALSO_GUARD = ["core_ledger_probe", "core_document_probe"]


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_docstatus_domain_and_series_guard"),
        ("masters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GLEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", core.money.MoneyField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("account", models.CharField(db_index=True, max_length=32)),
                ("doc_type", models.CharField(max_length=16)),
                ("doc_number", models.CharField(db_index=True, max_length=128)),
                (
                    "against_voucher",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("party_type", models.CharField(blank=True, default="", max_length=16)),
                ("party_code", models.CharField(blank=True, default="", max_length=64)),
                ("brand", models.CharField(blank=True, default="", max_length=120)),
                ("season", models.CharField(blank=True, default="", max_length=120)),
                ("line_no", models.IntegerField(default=0)),
                ("memo", models.CharField(blank=True, default="", max_length=240)),
                (
                    "gstin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gl_entries",
                        to="masters.gstin",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gl_entries",
                        to="masters.store",
                    ),
                ),
            ],
            options={
                "db_table": "core_gl_entry",
                "ordering": ["-created_at", "line_no"],
            },
        ),
        # The GL is append-only (ADR-0004): BEFORE UPDATE/DELETE trigger binds every
        # role; REVOKE is defence-in-depth.
        migrations.RunSQL(
            sql=append_only_sql(GL),
            reverse_sql=append_only_reverse_sql(GL),
        ),
        # Close the TRUNCATE bypass on the GL + the existing kernel append-only/
        # document probe tables (ADR-0006 hardening).
        migrations.RunSQL(
            sql=truncate_guard_sql(GL),
            reverse_sql=truncate_guard_reverse_sql(GL),
        ),
        *[
            migrations.RunSQL(
                sql=truncate_guard_sql(table),
                reverse_sql=truncate_guard_reverse_sql(table),
            )
            for table in ALSO_GUARD
        ],
    ]
