# Generated by Django 5.1.15 on 2026-09-13 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_authenticationfailure_humanidentity_rolegrant_and_more'),
        ('approvals', '0010_actiondraft_tenant_approvaldecision_actor_and_more'),
        ('core', '0008_auditevent_chainhead_commandattempt_commandkey_and_more'),
        ('files', '0003_evidenceobject_uploadintent_evidencelink'),
        ('masters', '0011_configdraft_configversion_sitecapabilityevent_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherseries',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddConstraint(
            model_name='voucherseries',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_version', 'entity_v1')), fields=('tenant', 'legal_entity', 'doc_type', 'fy'), name='uq_voucher_series_entity_v1'),
        ),
        migrations.AddConstraint(
            model_name='voucherseries',
            constraint=models.CheckConstraint(condition=models.Q(('scope_version', 'legacy'), models.Q(('legal_entity__isnull', False), ('tenant__isnull', False)), _connector='OR'), name='ck_voucher_series_entity_v1_scope'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='chainhead',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='commandattempt',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='commandattempt',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='commandkey',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='commandattempt',
            name='command_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='commandoutcome',
            name='key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outcome', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='commandoutcome',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='deliveryevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='deliveryevent',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='deliveryevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='documentevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='documentevent',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='documentevent',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.evidenceobject'),
        ),
        migrations.AddField(
            model_name='documentevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='documenthead',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='documentidentity',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='documentidentity',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.legalentity'),
        ),
        migrations.AddField(
            model_name='documentidentity',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='documentidentity',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddField(
            model_name='documentidentity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='documenthead',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='head', to='core.documentidentity'),
        ),
        migrations.AddField(
            model_name='documentevent',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.documentidentity'),
        ),
        migrations.AddField(
            model_name='draftline',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='draftline',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='draftline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_lines', to='core.documentidentity'),
        ),
        migrations.AddField(
            model_name='draftline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='draftrevision',
            name='action_draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='approvals.actiondraft'),
        ),
        migrations.AddField(
            model_name='draftrevision',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='draftrevision',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='draftrevision',
            name='config_draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='masters.configdraft'),
        ),
        migrations.AddField(
            model_name='draftrevision',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='core.documentidentity'),
        ),
        migrations.AddField(
            model_name='draftrevision',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.draftrevision'),
        ),
        migrations.AddField(
            model_name='draftrevision',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='documenthead',
            name='draft_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.draftrevision'),
        ),
        migrations.AddField(
            model_name='documentevent',
            name='revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.draftrevision'),
        ),
        migrations.AddField(
            model_name='jobartifact',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='jobartifact',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='jobartifact',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.evidenceobject'),
        ),
        migrations.AddField(
            model_name='jobartifact',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='jobstate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='legacyreference',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.evidenceobject'),
        ),
        migrations.AddField(
            model_name='legacyreference',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='officialline',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='officialline',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='officialline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='officialversion',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='officialversion',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='officialversion',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='officialversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core.documentidentity'),
        ),
        migrations.AddField(
            model_name='officialversion',
            name='draft_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.draftrevision'),
        ),
        migrations.AddField(
            model_name='officialversion',
            name='profile_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.configversion'),
        ),
        migrations.AddField(
            model_name='officialversion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='officialline',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='core.officialversion'),
        ),
        migrations.AddField(
            model_name='documenthead',
            name='live_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.officialversion'),
        ),
        migrations.AddField(
            model_name='documentevent',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.officialversion'),
        ),
        migrations.AddField(
            model_name='outboxintent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='outboxintent',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='outboxintent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='jobstate',
            name='intent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='job', to='core.outboxintent'),
        ),
        migrations.AddField(
            model_name='jobartifact',
            name='intent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='artifact', to='core.outboxintent'),
        ),
        migrations.AddField(
            model_name='deliveryevent',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.outboxintent'),
        ),
        migrations.AddField(
            model_name='privilegedreview',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='privilegedreview',
            name='audit_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='core.auditevent'),
        ),
        migrations.AddField(
            model_name='privilegedreview',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='privilegedreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='privilegedreview',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='recoveryrecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='recoveryrecord',
            name='manifest_evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.evidenceobject'),
        ),
        migrations.AddField(
            model_name='recoveryrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='seriesceiling',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.humanidentity'),
        ),
        migrations.AddField(
            model_name='seriesceiling',
            name='command_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.commandkey'),
        ),
        migrations.AddField(
            model_name='seriesceiling',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ceilings', to='core.voucherseries'),
        ),
        migrations.AddField(
            model_name='seriesceiling',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddField(
            model_name='subjectrevision',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.tenant'),
        ),
        migrations.AddIndex(
            model_name='chainhead',
            index=models.Index(fields=['anchored_at'], name='core_chainh_anchore_6cd283_idx'),
        ),
        migrations.AddConstraint(
            model_name='chainhead',
            constraint=models.UniqueConstraint(fields=('tenant', 'partition_key'), name='uq_chainhead_partition'),
        ),
        migrations.AddConstraint(
            model_name='commandkey',
            constraint=models.UniqueConstraint(fields=('tenant', 'principal_key', 'command_id'), name='uq_commandkey_identity'),
        ),
        migrations.AddIndex(
            model_name='commandattempt',
            index=models.Index(fields=['subject_key', 'recorded_at'], name='core_comman_subject_0a5b54_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['site', 'recorded_at'], name='core_audite_site_id_5881d4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor', 'recorded_at'], name='core_audite_actor_i_165f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['subject_key', 'recorded_at'], name='core_audite_subject_1c5c79_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='core_auditevent_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='commandoutcome',
            constraint=models.CheckConstraint(condition=models.Q(('status_code__gte', 200), ('status_code__lte', 599)), name='ck_commandoutcome_status'),
        ),
        migrations.AddIndex(
            model_name='documentidentity',
            index=models.Index(fields=['site', 'kind', 'created_at'], name='core_docume_site_id_3356bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentidentity',
            constraint=models.UniqueConstraint(condition=models.Q(('official_number__isnull', False)), fields=('tenant', 'official_number'), name='uq_documentidentity_number'),
        ),
        migrations.AddIndex(
            model_name='draftline',
            index=models.Index(fields=['document', 'line_key', 'created_in_revision'], name='core_draftl_documen_8a7b7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='draftline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='core_draftline_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='draftline',
            constraint=models.UniqueConstraint(fields=('document', 'line_key', 'created_in_revision'), name='uq_draftline_state'),
        ),
        migrations.AddConstraint(
            model_name='draftrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='core_draftrevision_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='draftrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action_draft__isnull', True), ('config_draft__isnull', True), ('document__isnull', False)), models.Q(('action_draft__isnull', True), ('config_draft__isnull', False), ('document__isnull', True)), models.Q(('action_draft__isnull', False), ('config_draft__isnull', True), ('document__isnull', True)), _connector='OR'), name='ck_draftrevision_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='draftrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('document__isnull', False)), fields=('document', 'revision'), name='uq_draftrevision_document'),
        ),
        migrations.AddConstraint(
            model_name='draftrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('config_draft__isnull', False)), fields=('config_draft', 'revision'), name='uq_draftrevision_config'),
        ),
        migrations.AddConstraint(
            model_name='draftrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('action_draft__isnull', False)), fields=('action_draft', 'revision'), name='uq_draftrevision_action'),
        ),
        migrations.AddConstraint(
            model_name='legacyreference',
            constraint=models.UniqueConstraint(fields=('tenant', 'family', 'legacy_key'), name='uq_legacyreference'),
        ),
        migrations.AddConstraint(
            model_name='officialversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='core_officialversion_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='officialversion',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='uq_officialversion_version'),
        ),
        migrations.AddIndex(
            model_name='officialline',
            index=models.Index(fields=['stable_line_key'], name='core_offici_stable__01e0a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='officialline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='core_officialline_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='officialline',
            constraint=models.UniqueConstraint(fields=('version', 'line_no'), name='uq_officialline_no'),
        ),
        migrations.AddConstraint(
            model_name='officialline',
            constraint=models.UniqueConstraint(fields=('version', 'stable_line_key'), name='uq_officialline_key'),
        ),
        migrations.AddConstraint(
            model_name='officialline',
            constraint=models.CheckConstraint(condition=models.Q(('line_no__gte', 1), ('line_no__lte', 50000)), name='ck_officialline_no'),
        ),
        migrations.AddConstraint(
            model_name='documenthead',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='ck_documenthead_revision'),
        ),
        migrations.AddIndex(
            model_name='documentevent',
            index=models.Index(fields=['document', 'recorded_at', 'id'], name='core_docume_documen_35c074_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='core_documentevent_one_actor'),
        ),
        migrations.AddIndex(
            model_name='outboxintent',
            index=models.Index(fields=['kind', 'not_before'], name='core_outbox_kind_b37b85_idx'),
        ),
        migrations.AddConstraint(
            model_name='outboxintent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='core_outboxintent_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='outboxintent',
            constraint=models.UniqueConstraint(fields=('tenant', 'request_key'), name='uq_outbox_request'),
        ),
        migrations.AddIndex(
            model_name='jobstate',
            index=models.Index(fields=['state', 'lease_until', 'created_at'], name='core_jobsta_state_c90bd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobstate',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__gte', 0)), name='ck_jobstate_attempts'),
        ),
        migrations.AddConstraint(
            model_name='jobstate',
            constraint=models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='ck_jobstate_progress'),
        ),
        migrations.AddConstraint(
            model_name='jobartifact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='core_jobartifact_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='deliveryevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='core_deliveryevent_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='deliveryevent',
            constraint=models.UniqueConstraint(fields=('intent', 'attempt', 'state'), name='uq_delivery_attempt_state'),
        ),
        migrations.AddIndex(
            model_name='privilegedreview',
            index=models.Index(fields=['reviewed_at'], name='core_privil_reviewe_fdf6fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='privilegedreview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='core_privilegedreview_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='privilegedreview',
            constraint=models.UniqueConstraint(fields=('audit_event', 'reviewer'), name='uq_privilegedreview'),
        ),
        migrations.AddIndex(
            model_name='recoveryrecord',
            index=models.Index(fields=['restored_at'], name='core_recove_restore_f291c2_idx'),
        ),
        migrations.AddIndex(
            model_name='seriesceiling',
            index=models.Index(fields=['series', 'ceiling'], name='core_series_series__20173e_idx'),
        ),
        migrations.AddConstraint(
            model_name='seriesceiling',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('service_code__isnull', True)), models.Q(('actor__isnull', True), ('service_code__isnull', False)), _connector='OR'), name='core_seriesceiling_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='seriesceiling',
            constraint=models.UniqueConstraint(fields=('series', 'ceiling'), name='uq_seriesceiling'),
        ),
        migrations.AddConstraint(
            model_name='subjectrevision',
            constraint=models.UniqueConstraint(fields=('tenant', 'family', 'subject_key'), name='uq_subjectrevision'),
        ),
        migrations.AddConstraint(
            model_name='subjectrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gt', 0)), name='ck_subjectrevision_positive'),
        ),
    ]
