# Generated by Django 5.1.15 on 2026-09-19 03:10

import django.db.models.deletion
from django.db import migrations, models

# A booking may be saved with only its legal entity (GSA-T05, decided
# 19 September 2026): its document site stays empty until the buyer first names
# a destination, then is set once. The identity guard's function is replaced in
# place (its trigger is bound by name, so it is not re-created); on a new
# database the trigger itself is installed after migrate by core.schema_guards
# with the same body. Both bodies are frozen here so the migration never drifts.
GUARD_WITH_BOOKING_SITE = """
    CREATE OR REPLACE FUNCTION kdps_identity_number_once() RETURNS trigger AS $$
    BEGIN
        IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'document identities are never deleted (%)', TG_TABLE_NAME;
        END IF;
        IF OLD.official_number IS NOT NULL
           AND NEW.official_number IS DISTINCT FROM OLD.official_number THEN
            RAISE EXCEPTION 'an official number is set once and never changed';
        END IF;
        IF NEW.site_id IS DISTINCT FROM OLD.site_id
           AND (OLD.site_id IS NOT NULL OR NEW.site_id IS NULL OR OLD.purpose <> 'booking') THEN
            RAISE EXCEPTION 'a booking''s site is set once, from none, and never changed';
        END IF;
        IF (to_jsonb(NEW) - 'official_number' - 'site_id')
           IS DISTINCT FROM (to_jsonb(OLD) - 'official_number' - 'site_id') THEN
            RAISE EXCEPTION 'document identity fields are immutable';
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
"""

GUARD_BEFORE = """
    CREATE OR REPLACE FUNCTION kdps_identity_number_once() RETURNS trigger AS $$
    BEGIN
        IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'document identities are never deleted (%)', TG_TABLE_NAME;
        END IF;
        IF OLD.official_number IS NOT NULL
           AND NEW.official_number IS DISTINCT FROM OLD.official_number THEN
            RAISE EXCEPTION 'an official number is set once and never changed';
        END IF;
        IF (to_jsonb(NEW) - 'official_number')
           IS DISTINCT FROM (to_jsonb(OLD) - 'official_number') THEN
            RAISE EXCEPTION 'document identity fields are immutable';
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_must_change_password'),
        ('core', '0009_voucherseries_tenant_and_more'),
        ('masters', '0020_sbu_revision_and_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentidentity',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.store'),
        ),
        migrations.AddConstraint(
            model_name='documentidentity',
            constraint=models.CheckConstraint(condition=models.Q(('site__isnull', False), ('purpose', 'booking'), _connector='OR'), name='ck_documentidentity_site_unless_booking'),
        ),
        migrations.RunSQL(sql=GUARD_WITH_BOOKING_SITE, reverse_sql=GUARD_BEFORE),
    ]
