# Generated by Django 5.1.15 on 2026-09-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_documentidentity_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentidentity',
            name='purpose',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('opening', 'Opening'), ('transfer', 'Transfer'), ('booking', 'Booking'), ('grn', 'Grn'), ('counter_grn', 'Counter Grn'), ('movement', 'Movement'), ('count', 'Count'), ('gap_resolution', 'Gap Resolution'), ('sale', 'Sale'), ('reservation', 'Reservation')], max_length=20),
        ),
    ]
